/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Wed Nov 26 13:26:23 EST 2014
 * 
 */
extern "C" {
  void bluenoc_close_tcp_socket(unsigned int );
  unsigned int bluenoc_open_tcp_socket(unsigned int );
  void bluenoc_recv_tcp_beat(unsigned int *, unsigned int , char , char , unsigned int *);
  char bluenoc_send_tcp_beat(unsigned int , char , char , unsigned int *);
}
