/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Tue Nov 25 02:07:28 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "mkCop.h"


/* String declarations */
static std::string const __str_literal_1("\nCycle %d ----------------------------------------------------",
					 62u);


/* Constructor */
MOD_mkCop::MOD_mkCop(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_causeReg(simHdl, "causeReg", this, 32u, 0u, (tUInt8)0u),
    INST_copFifo_clearReq_ehrReg(simHdl, "copFifo_clearReq_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_copFifo_clearReq_ignored_wires_0(simHdl,
					  "copFifo_clearReq_ignored_wires_0",
					  this,
					  1u,
					  (tUInt8)0u),
    INST_copFifo_clearReq_ignored_wires_1(simHdl,
					  "copFifo_clearReq_ignored_wires_1",
					  this,
					  1u,
					  (tUInt8)0u),
    INST_copFifo_clearReq_virtual_reg_0(simHdl, "copFifo_clearReq_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_copFifo_clearReq_virtual_reg_1(simHdl, "copFifo_clearReq_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_copFifo_clearReq_wires_0(simHdl, "copFifo_clearReq_wires_0", this, 1u, (tUInt8)0u),
    INST_copFifo_clearReq_wires_1(simHdl, "copFifo_clearReq_wires_1", this, 1u, (tUInt8)0u),
    INST_copFifo_data_0(simHdl, "copFifo_data_0", this, 37u),
    INST_copFifo_data_1(simHdl, "copFifo_data_1", this, 37u),
    INST_copFifo_deqP(simHdl, "copFifo_deqP", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_copFifo_deqReq_ehrReg(simHdl, "copFifo_deqReq_ehrReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_copFifo_deqReq_ignored_wires_0(simHdl, "copFifo_deqReq_ignored_wires_0", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_ignored_wires_1(simHdl, "copFifo_deqReq_ignored_wires_1", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_ignored_wires_2(simHdl, "copFifo_deqReq_ignored_wires_2", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_virtual_reg_0(simHdl, "copFifo_deqReq_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_virtual_reg_1(simHdl, "copFifo_deqReq_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_virtual_reg_2(simHdl, "copFifo_deqReq_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_wires_0(simHdl, "copFifo_deqReq_wires_0", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_wires_1(simHdl, "copFifo_deqReq_wires_1", this, 1u, (tUInt8)0u),
    INST_copFifo_deqReq_wires_2(simHdl, "copFifo_deqReq_wires_2", this, 1u, (tUInt8)0u),
    INST_copFifo_empty(simHdl, "copFifo_empty", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_copFifo_enqP(simHdl, "copFifo_enqP", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_copFifo_enqReq_ehrReg(simHdl, "copFifo_enqReq_ehrReg", this, 38u, 45812984490llu, (tUInt8)0u),
    INST_copFifo_enqReq_ignored_wires_0(simHdl,
					"copFifo_enqReq_ignored_wires_0",
					this,
					38u,
					(tUInt8)0u),
    INST_copFifo_enqReq_ignored_wires_1(simHdl,
					"copFifo_enqReq_ignored_wires_1",
					this,
					38u,
					(tUInt8)0u),
    INST_copFifo_enqReq_ignored_wires_2(simHdl,
					"copFifo_enqReq_ignored_wires_2",
					this,
					38u,
					(tUInt8)0u),
    INST_copFifo_enqReq_virtual_reg_0(simHdl, "copFifo_enqReq_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_copFifo_enqReq_virtual_reg_1(simHdl, "copFifo_enqReq_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_copFifo_enqReq_virtual_reg_2(simHdl, "copFifo_enqReq_virtual_reg_2", this, 1u, (tUInt8)0u),
    INST_copFifo_enqReq_wires_0(simHdl, "copFifo_enqReq_wires_0", this, 38u, (tUInt8)0u),
    INST_copFifo_enqReq_wires_1(simHdl, "copFifo_enqReq_wires_1", this, 38u, (tUInt8)0u),
    INST_copFifo_enqReq_wires_2(simHdl, "copFifo_enqReq_wires_2", this, 38u, (tUInt8)0u),
    INST_copFifo_full(simHdl, "copFifo_full", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_cycles(simHdl, "cycles", this, 32u, 0u, (tUInt8)0u),
    INST_epcReg_ehrReg(simHdl, "epcReg_ehrReg", this, 32u, 0u, (tUInt8)0u),
    INST_epcReg_ignored_wires_0(simHdl, "epcReg_ignored_wires_0", this, 32u, (tUInt8)0u),
    INST_epcReg_ignored_wires_1(simHdl, "epcReg_ignored_wires_1", this, 32u, (tUInt8)0u),
    INST_epcReg_virtual_reg_0(simHdl, "epcReg_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_epcReg_virtual_reg_1(simHdl, "epcReg_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_epcReg_wires_0(simHdl, "epcReg_wires_0", this, 32u, (tUInt8)0u),
    INST_epcReg_wires_1(simHdl, "epcReg_wires_1", this, 32u, (tUInt8)0u),
    INST_numInsts(simHdl, "numInsts", this, 32u, 0u, (tUInt8)0u),
    INST_startReg(simHdl, "startReg", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_statusReg_ehrReg(simHdl, "statusReg_ehrReg", this, 32u, 2u, (tUInt8)0u),
    INST_statusReg_ignored_wires_0(simHdl, "statusReg_ignored_wires_0", this, 32u, (tUInt8)0u),
    INST_statusReg_ignored_wires_1(simHdl, "statusReg_ignored_wires_1", this, 32u, (tUInt8)0u),
    INST_statusReg_virtual_reg_0(simHdl, "statusReg_virtual_reg_0", this, 1u, (tUInt8)0u),
    INST_statusReg_virtual_reg_1(simHdl, "statusReg_virtual_reg_1", this, 1u, (tUInt8)0u),
    INST_statusReg_wires_0(simHdl, "statusReg_wires_0", this, 32u, (tUInt8)0u),
    INST_statusReg_wires_1(simHdl, "statusReg_wires_1", this, 32u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  PORT_EN_cpuToHost = false;
  PORT_EN_start = false;
  PORT_EN_wr = false;
  PORT_EN_causeException = false;
  PORT_EN_returnFromException = false;
  PORT_rd_idx = 0u;
  PORT_wr_idx = 0u;
  PORT_wr_val = 0u;
  PORT_causeException_current_pc = 0u;
  PORT_causeException_cause = 0u;
  PORT_cpuToHost = 0llu;
  PORT_RDY_cpuToHost = false;
  PORT_RDY_start = false;
  PORT_started = false;
  PORT_RDY_started = false;
  PORT_rd = 0u;
  PORT_RDY_rd = false;
  PORT_RDY_wr = false;
  PORT_RDY_causeException = false;
  PORT_RDY_returnFromException = false;
  PORT_getEPC = 0u;
  PORT_RDY_getEPC = false;
  PORT_isUserMode = false;
  PORT_RDY_isUserMode = false;
  symbol_count = 112u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkCop::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_causeException", SYM_DEF, &DEF_CAN_FIRE_causeException, 1u);
  init_symbol(&symbols[1u], "CAN_FIRE_cpuToHost", SYM_DEF, &DEF_CAN_FIRE_cpuToHost, 1u);
  init_symbol(&symbols[2u], "CAN_FIRE_getEPC", SYM_DEF, &DEF_CAN_FIRE_getEPC, 1u);
  init_symbol(&symbols[3u], "CAN_FIRE_isUserMode", SYM_DEF, &DEF_CAN_FIRE_isUserMode, 1u);
  init_symbol(&symbols[4u],
	      "CAN_FIRE_RL_copFifo_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_copFifo_canonicalize,
	      1u);
  init_symbol(&symbols[5u],
	      "CAN_FIRE_RL_copFifo_clearReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize,
	      1u);
  init_symbol(&symbols[6u],
	      "CAN_FIRE_RL_copFifo_deqReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize,
	      1u);
  init_symbol(&symbols[7u],
	      "CAN_FIRE_RL_copFifo_enqReq_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize,
	      1u);
  init_symbol(&symbols[8u], "CAN_FIRE_RL_count", SYM_DEF, &DEF_CAN_FIRE_RL_count, 1u);
  init_symbol(&symbols[9u],
	      "CAN_FIRE_RL_epcReg_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_epcReg_canonicalize,
	      1u);
  init_symbol(&symbols[10u],
	      "CAN_FIRE_RL_statusReg_canonicalize",
	      SYM_DEF,
	      &DEF_CAN_FIRE_RL_statusReg_canonicalize,
	      1u);
  init_symbol(&symbols[11u], "CAN_FIRE_rd", SYM_DEF, &DEF_CAN_FIRE_rd, 1u);
  init_symbol(&symbols[12u],
	      "CAN_FIRE_returnFromException",
	      SYM_DEF,
	      &DEF_CAN_FIRE_returnFromException,
	      1u);
  init_symbol(&symbols[13u], "CAN_FIRE_start", SYM_DEF, &DEF_CAN_FIRE_start, 1u);
  init_symbol(&symbols[14u], "CAN_FIRE_started", SYM_DEF, &DEF_CAN_FIRE_started, 1u);
  init_symbol(&symbols[15u], "CAN_FIRE_wr", SYM_DEF, &DEF_CAN_FIRE_wr, 1u);
  init_symbol(&symbols[16u], "causeException_cause", SYM_PORT, &PORT_causeException_cause, 5u);
  init_symbol(&symbols[17u],
	      "causeException_current_pc",
	      SYM_PORT,
	      &PORT_causeException_current_pc,
	      32u);
  init_symbol(&symbols[18u], "causeReg", SYM_MODULE, &INST_causeReg);
  init_symbol(&symbols[19u], "copFifo_clearReq_ehrReg", SYM_MODULE, &INST_copFifo_clearReq_ehrReg);
  init_symbol(&symbols[20u],
	      "copFifo_clearReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_copFifo_clearReq_ignored_wires_0);
  init_symbol(&symbols[21u],
	      "copFifo_clearReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_copFifo_clearReq_ignored_wires_1);
  init_symbol(&symbols[22u],
	      "copFifo_clearReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_copFifo_clearReq_virtual_reg_0);
  init_symbol(&symbols[23u],
	      "copFifo_clearReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_copFifo_clearReq_virtual_reg_1);
  init_symbol(&symbols[24u], "copFifo_clearReq_wires_0", SYM_MODULE, &INST_copFifo_clearReq_wires_0);
  init_symbol(&symbols[25u], "copFifo_clearReq_wires_1", SYM_MODULE, &INST_copFifo_clearReq_wires_1);
  init_symbol(&symbols[26u], "copFifo_data_0", SYM_MODULE, &INST_copFifo_data_0);
  init_symbol(&symbols[27u], "copFifo_data_1", SYM_MODULE, &INST_copFifo_data_1);
  init_symbol(&symbols[28u], "copFifo_deqP", SYM_MODULE, &INST_copFifo_deqP);
  init_symbol(&symbols[29u], "copFifo_deqReq_ehrReg", SYM_MODULE, &INST_copFifo_deqReq_ehrReg);
  init_symbol(&symbols[30u],
	      "copFifo_deqReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_copFifo_deqReq_ignored_wires_0);
  init_symbol(&symbols[31u],
	      "copFifo_deqReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_copFifo_deqReq_ignored_wires_1);
  init_symbol(&symbols[32u],
	      "copFifo_deqReq_ignored_wires_2",
	      SYM_MODULE,
	      &INST_copFifo_deqReq_ignored_wires_2);
  init_symbol(&symbols[33u],
	      "copFifo_deqReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_copFifo_deqReq_virtual_reg_0);
  init_symbol(&symbols[34u],
	      "copFifo_deqReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_copFifo_deqReq_virtual_reg_1);
  init_symbol(&symbols[35u],
	      "copFifo_deqReq_virtual_reg_2",
	      SYM_MODULE,
	      &INST_copFifo_deqReq_virtual_reg_2);
  init_symbol(&symbols[36u], "copFifo_deqReq_wires_0", SYM_MODULE, &INST_copFifo_deqReq_wires_0);
  init_symbol(&symbols[37u], "copFifo_deqReq_wires_1", SYM_MODULE, &INST_copFifo_deqReq_wires_1);
  init_symbol(&symbols[38u], "copFifo_deqReq_wires_2", SYM_MODULE, &INST_copFifo_deqReq_wires_2);
  init_symbol(&symbols[39u], "copFifo_empty", SYM_MODULE, &INST_copFifo_empty);
  init_symbol(&symbols[40u], "copFifo_empty__h5662", SYM_DEF, &DEF_copFifo_empty__h5662, 1u);
  init_symbol(&symbols[41u], "copFifo_enqP", SYM_MODULE, &INST_copFifo_enqP);
  init_symbol(&symbols[42u], "copFifo_enqReq_ehrReg", SYM_MODULE, &INST_copFifo_enqReq_ehrReg);
  init_symbol(&symbols[43u],
	      "copFifo_enqReq_ignored_wires_0",
	      SYM_MODULE,
	      &INST_copFifo_enqReq_ignored_wires_0);
  init_symbol(&symbols[44u],
	      "copFifo_enqReq_ignored_wires_1",
	      SYM_MODULE,
	      &INST_copFifo_enqReq_ignored_wires_1);
  init_symbol(&symbols[45u],
	      "copFifo_enqReq_ignored_wires_2",
	      SYM_MODULE,
	      &INST_copFifo_enqReq_ignored_wires_2);
  init_symbol(&symbols[46u],
	      "copFifo_enqReq_virtual_reg_0",
	      SYM_MODULE,
	      &INST_copFifo_enqReq_virtual_reg_0);
  init_symbol(&symbols[47u],
	      "copFifo_enqReq_virtual_reg_1",
	      SYM_MODULE,
	      &INST_copFifo_enqReq_virtual_reg_1);
  init_symbol(&symbols[48u],
	      "copFifo_enqReq_virtual_reg_2",
	      SYM_MODULE,
	      &INST_copFifo_enqReq_virtual_reg_2);
  init_symbol(&symbols[49u], "copFifo_enqReq_wires_0", SYM_MODULE, &INST_copFifo_enqReq_wires_0);
  init_symbol(&symbols[50u], "copFifo_enqReq_wires_1", SYM_MODULE, &INST_copFifo_enqReq_wires_1);
  init_symbol(&symbols[51u], "copFifo_enqReq_wires_2", SYM_MODULE, &INST_copFifo_enqReq_wires_2);
  init_symbol(&symbols[52u], "copFifo_full", SYM_MODULE, &INST_copFifo_full);
  init_symbol(&symbols[53u], "copFifo_full__h5630", SYM_DEF, &DEF_copFifo_full__h5630, 1u);
  init_symbol(&symbols[54u], "cpuToHost", SYM_PORT, &PORT_cpuToHost, 37u);
  init_symbol(&symbols[55u], "cycles", SYM_MODULE, &INST_cycles);
  init_symbol(&symbols[56u], "EN_causeException", SYM_PORT, &PORT_EN_causeException, 1u);
  init_symbol(&symbols[57u], "EN_cpuToHost", SYM_PORT, &PORT_EN_cpuToHost, 1u);
  init_symbol(&symbols[58u], "EN_returnFromException", SYM_PORT, &PORT_EN_returnFromException, 1u);
  init_symbol(&symbols[59u], "EN_start", SYM_PORT, &PORT_EN_start, 1u);
  init_symbol(&symbols[60u], "EN_wr", SYM_PORT, &PORT_EN_wr, 1u);
  init_symbol(&symbols[61u], "epcReg_ehrReg", SYM_MODULE, &INST_epcReg_ehrReg);
  init_symbol(&symbols[62u], "epcReg_ignored_wires_0", SYM_MODULE, &INST_epcReg_ignored_wires_0);
  init_symbol(&symbols[63u], "epcReg_ignored_wires_1", SYM_MODULE, &INST_epcReg_ignored_wires_1);
  init_symbol(&symbols[64u], "epcReg_virtual_reg_0", SYM_MODULE, &INST_epcReg_virtual_reg_0);
  init_symbol(&symbols[65u], "epcReg_virtual_reg_1", SYM_MODULE, &INST_epcReg_virtual_reg_1);
  init_symbol(&symbols[66u], "epcReg_wires_0", SYM_MODULE, &INST_epcReg_wires_0);
  init_symbol(&symbols[67u], "epcReg_wires_1", SYM_MODULE, &INST_epcReg_wires_1);
  init_symbol(&symbols[68u], "getEPC", SYM_PORT, &PORT_getEPC, 32u);
  init_symbol(&symbols[69u], "isUserMode", SYM_PORT, &PORT_isUserMode, 1u);
  init_symbol(&symbols[70u], "numInsts", SYM_MODULE, &INST_numInsts);
  init_symbol(&symbols[71u], "RDY_causeException", SYM_PORT, &PORT_RDY_causeException, 1u);
  init_symbol(&symbols[72u], "RDY_cpuToHost", SYM_PORT, &PORT_RDY_cpuToHost, 1u);
  init_symbol(&symbols[73u], "RDY_getEPC", SYM_PORT, &PORT_RDY_getEPC, 1u);
  init_symbol(&symbols[74u], "RDY_isUserMode", SYM_PORT, &PORT_RDY_isUserMode, 1u);
  init_symbol(&symbols[75u], "RDY_rd", SYM_PORT, &PORT_RDY_rd, 1u);
  init_symbol(&symbols[76u], "RDY_returnFromException", SYM_PORT, &PORT_RDY_returnFromException, 1u);
  init_symbol(&symbols[77u], "RDY_start", SYM_PORT, &PORT_RDY_start, 1u);
  init_symbol(&symbols[78u], "RDY_started", SYM_PORT, &PORT_RDY_started, 1u);
  init_symbol(&symbols[79u], "RDY_wr", SYM_PORT, &PORT_RDY_wr, 1u);
  init_symbol(&symbols[80u], "RL_copFifo_canonicalize", SYM_RULE);
  init_symbol(&symbols[81u], "RL_copFifo_clearReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[82u], "RL_copFifo_deqReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[83u], "RL_copFifo_enqReq_canonicalize", SYM_RULE);
  init_symbol(&symbols[84u], "RL_count", SYM_RULE);
  init_symbol(&symbols[85u], "RL_epcReg_canonicalize", SYM_RULE);
  init_symbol(&symbols[86u], "RL_statusReg_canonicalize", SYM_RULE);
  init_symbol(&symbols[87u], "rd", SYM_PORT, &PORT_rd, 32u);
  init_symbol(&symbols[88u], "rd_idx", SYM_PORT, &PORT_rd_idx, 5u);
  init_symbol(&symbols[89u], "started", SYM_PORT, &PORT_started, 1u);
  init_symbol(&symbols[90u], "startReg", SYM_MODULE, &INST_startReg);
  init_symbol(&symbols[91u], "statusReg_ehrReg", SYM_MODULE, &INST_statusReg_ehrReg);
  init_symbol(&symbols[92u],
	      "statusReg_ignored_wires_0",
	      SYM_MODULE,
	      &INST_statusReg_ignored_wires_0);
  init_symbol(&symbols[93u],
	      "statusReg_ignored_wires_1",
	      SYM_MODULE,
	      &INST_statusReg_ignored_wires_1);
  init_symbol(&symbols[94u], "statusReg_virtual_reg_0", SYM_MODULE, &INST_statusReg_virtual_reg_0);
  init_symbol(&symbols[95u], "statusReg_virtual_reg_1", SYM_MODULE, &INST_statusReg_virtual_reg_1);
  init_symbol(&symbols[96u], "statusReg_wires_0", SYM_MODULE, &INST_statusReg_wires_0);
  init_symbol(&symbols[97u], "statusReg_wires_1", SYM_MODULE, &INST_statusReg_wires_1);
  init_symbol(&symbols[98u], "WILL_FIRE_causeException", SYM_DEF, &DEF_WILL_FIRE_causeException, 1u);
  init_symbol(&symbols[99u], "WILL_FIRE_cpuToHost", SYM_DEF, &DEF_WILL_FIRE_cpuToHost, 1u);
  init_symbol(&symbols[100u],
	      "WILL_FIRE_RL_copFifo_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_copFifo_canonicalize,
	      1u);
  init_symbol(&symbols[101u],
	      "WILL_FIRE_RL_copFifo_clearReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize,
	      1u);
  init_symbol(&symbols[102u],
	      "WILL_FIRE_RL_copFifo_deqReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize,
	      1u);
  init_symbol(&symbols[103u],
	      "WILL_FIRE_RL_copFifo_enqReq_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize,
	      1u);
  init_symbol(&symbols[104u], "WILL_FIRE_RL_count", SYM_DEF, &DEF_WILL_FIRE_RL_count, 1u);
  init_symbol(&symbols[105u],
	      "WILL_FIRE_RL_epcReg_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_epcReg_canonicalize,
	      1u);
  init_symbol(&symbols[106u],
	      "WILL_FIRE_RL_statusReg_canonicalize",
	      SYM_DEF,
	      &DEF_WILL_FIRE_RL_statusReg_canonicalize,
	      1u);
  init_symbol(&symbols[107u],
	      "WILL_FIRE_returnFromException",
	      SYM_DEF,
	      &DEF_WILL_FIRE_returnFromException,
	      1u);
  init_symbol(&symbols[108u], "WILL_FIRE_start", SYM_DEF, &DEF_WILL_FIRE_start, 1u);
  init_symbol(&symbols[109u], "WILL_FIRE_wr", SYM_DEF, &DEF_WILL_FIRE_wr, 1u);
  init_symbol(&symbols[110u], "wr_idx", SYM_PORT, &PORT_wr_idx, 7u);
  init_symbol(&symbols[111u], "wr_val", SYM_PORT, &PORT_wr_val, 32u);
}


/* Rule actions */

void MOD_mkCop::RL_copFifo_enqReq_canonicalize()
{
  tUInt64 DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d30;
  tUInt64 DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d28;
  tUInt8 DEF_copFifo_enqReq_wires_2_wget_BIT_37___d3;
  tUInt8 DEF_copFifo_enqReq_wires_2_whas____d1;
  tUInt64 DEF_copFifo_enqReq_wires_2_wget____d2;
  DEF_copFifo_enqReq_wires_2_wget____d2 = INST_copFifo_enqReq_wires_2.METH_wget();
  DEF_copFifo_enqReq_wires_1_wget____d5 = INST_copFifo_enqReq_wires_1.METH_wget();
  DEF_copFifo_enqReq_wires_0_wget____d8 = INST_copFifo_enqReq_wires_0.METH_wget();
  DEF_copFifo_enqReq_ehrReg___d10 = INST_copFifo_enqReq_ehrReg.METH_read();
  DEF_copFifo_enqReq_wires_2_whas____d1 = INST_copFifo_enqReq_wires_2.METH_whas();
  DEF_copFifo_enqReq_wires_1_whas____d4 = INST_copFifo_enqReq_wires_1.METH_whas();
  DEF_copFifo_enqReq_wires_0_whas____d7 = INST_copFifo_enqReq_wires_0.METH_whas();
  DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25 = (tUInt64)(137438953471llu & DEF_copFifo_enqReq_ehrReg___d10);
  DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11 = (tUInt8)(DEF_copFifo_enqReq_ehrReg___d10 >> 37u);
  DEF_copFifo_enqReq_wires_2_wget_BIT_37___d3 = (tUInt8)(DEF_copFifo_enqReq_wires_2_wget____d2 >> 37u);
  DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 = (tUInt8)(DEF_copFifo_enqReq_wires_0_wget____d8 >> 37u);
  DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 = (tUInt8)(DEF_copFifo_enqReq_wires_1_wget____d5 >> 37u);
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13 = DEF_copFifo_enqReq_wires_1_whas____d4 ? DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 : (DEF_copFifo_enqReq_wires_0_whas____d7 ? DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 : DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11);
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27 = DEF_copFifo_enqReq_wires_1_whas____d4 ? (tUInt64)(137438953471llu & DEF_copFifo_enqReq_wires_1_wget____d5) : (DEF_copFifo_enqReq_wires_0_whas____d7 ? (tUInt64)(137438953471llu & DEF_copFifo_enqReq_wires_0_wget____d8) : DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25);
  DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d28 = DEF_copFifo_enqReq_wires_2_whas____d1 ? (tUInt64)(137438953471llu & DEF_copFifo_enqReq_wires_2_wget____d2) : DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27;
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20 = DEF_copFifo_enqReq_wires_1_whas____d4 ? !DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 : (DEF_copFifo_enqReq_wires_0_whas____d7 ? !DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 : !DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11);
  DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d30 = 274877906943llu & ((((tUInt64)(DEF_copFifo_enqReq_wires_2_whas____d1 ? DEF_copFifo_enqReq_wires_2_wget_BIT_37___d3 : DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13)) << 37u) | ((DEF_copFifo_enqReq_wires_2_whas____d1 ? !DEF_copFifo_enqReq_wires_2_wget_BIT_37___d3 : DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20) ? DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d28 : DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d28));
  INST_copFifo_enqReq_ehrReg.METH_write(DEF_IF_copFifo_enqReq_wires_2_whas_THEN_copFifo_en_ETC___d30);
}

void MOD_mkCop::RL_copFifo_deqReq_canonicalize()
{
  tUInt8 DEF_IF_copFifo_deqReq_wires_2_whas__1_THEN_copFifo_ETC___d40;
  DEF_copFifo_deqReq_ehrReg___d37 = INST_copFifo_deqReq_ehrReg.METH_read();
  DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39 = INST_copFifo_deqReq_wires_1.METH_whas() ? INST_copFifo_deqReq_wires_1.METH_wget() : (INST_copFifo_deqReq_wires_0.METH_whas() ? INST_copFifo_deqReq_wires_0.METH_wget() : DEF_copFifo_deqReq_ehrReg___d37);
  DEF_IF_copFifo_deqReq_wires_2_whas__1_THEN_copFifo_ETC___d40 = INST_copFifo_deqReq_wires_2.METH_whas() ? INST_copFifo_deqReq_wires_2.METH_wget() : DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39;
  INST_copFifo_deqReq_ehrReg.METH_write(DEF_IF_copFifo_deqReq_wires_2_whas__1_THEN_copFifo_ETC___d40);
}

void MOD_mkCop::RL_copFifo_clearReq_canonicalize()
{
  tUInt8 DEF_IF_copFifo_clearReq_wires_1_whas__1_THEN_copFi_ETC___d47;
  DEF_copFifo_clearReq_wires_0_whas____d43 = INST_copFifo_clearReq_wires_0.METH_whas();
  DEF_copFifo_clearReq_wires_0_wget____d44 = INST_copFifo_clearReq_wires_0.METH_wget();
  DEF_copFifo_clearReq_ehrReg___d45 = INST_copFifo_clearReq_ehrReg.METH_read();
  DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46 = DEF_copFifo_clearReq_wires_0_whas____d43 ? DEF_copFifo_clearReq_wires_0_wget____d44 : DEF_copFifo_clearReq_ehrReg___d45;
  DEF_IF_copFifo_clearReq_wires_1_whas__1_THEN_copFi_ETC___d47 = INST_copFifo_clearReq_wires_1.METH_whas() ? INST_copFifo_clearReq_wires_1.METH_wget() : DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46;
  INST_copFifo_clearReq_ehrReg.METH_write(DEF_IF_copFifo_clearReq_wires_1_whas__1_THEN_copFi_ETC___d47);
}

void MOD_mkCop::RL_copFifo_canonicalize()
{
  tUInt64 DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d92;
  tUInt64 DEF__0_CONCAT_DONTCARE___d90;
  tUInt8 DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d70;
  tUInt8 DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d61;
  tUInt8 DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d75;
  tUInt8 DEF_copFifo_enqP_6_EQ_0_3_AND_copFifo_clearReq_vir_ETC___d85;
  tUInt8 DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d84;
  tUInt8 DEF_copFifo_enqP_6_EQ_1_8_AND_copFifo_clearReq_vir_ETC___d89;
  tUInt8 DEF_NOT_copFifo_clearReq_virtual_reg_1_read__8_6_A_ETC___d82;
  tUInt8 DEF_v__h4858;
  tUInt8 DEF_NOT_copFifo_enqReq_virtual_reg_2_read__3_4_AND_ETC___d55;
  tUInt8 DEF_next_deqP___1__h5553;
  tUInt8 DEF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3_AND_ETC___d64;
  tUInt64 DEF_IF_copFifo_enqReq_virtual_reg_2_read__3_OR_IF__ETC___d87;
  tUInt8 DEF_copFifo_clearReq_virtual_reg_1_read____d48;
  tUInt8 DEF_copFifo_enqReq_virtual_reg_2_read____d53;
  tUInt8 DEF_v__h4499;
  tUInt8 DEF__theResult_____2__h5148;
  tUInt8 DEF_IF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3__ETC___d71;
  tUInt8 DEF_copFifo_enqP__h5131;
  tUInt8 DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d52;
  DEF_copFifo_empty__h5662 = INST_copFifo_empty.METH_read();
  DEF_copFifo_full__h5630 = INST_copFifo_full.METH_read();
  DEF_copFifo_enqP__h5131 = INST_copFifo_enqP.METH_read();
  DEF_copFifo_enqReq_virtual_reg_2_read____d53 = INST_copFifo_enqReq_virtual_reg_2.METH_read();
  DEF_copFifo_enqReq_wires_1_wget____d5 = INST_copFifo_enqReq_wires_1.METH_wget();
  DEF_copFifo_enqReq_wires_0_wget____d8 = INST_copFifo_enqReq_wires_0.METH_wget();
  DEF_copFifo_enqReq_ehrReg___d10 = INST_copFifo_enqReq_ehrReg.METH_read();
  DEF_copFifo_clearReq_wires_0_whas____d43 = INST_copFifo_clearReq_wires_0.METH_whas();
  DEF_copFifo_clearReq_virtual_reg_1_read____d48 = INST_copFifo_clearReq_virtual_reg_1.METH_read();
  DEF_copFifo_clearReq_wires_0_wget____d44 = INST_copFifo_clearReq_wires_0.METH_wget();
  DEF_copFifo_clearReq_ehrReg___d45 = INST_copFifo_clearReq_ehrReg.METH_read();
  DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d52 = DEF_copFifo_clearReq_virtual_reg_1_read____d48 || (DEF_copFifo_clearReq_wires_0_whas____d43 ? !DEF_copFifo_clearReq_wires_0_wget____d44 : !DEF_copFifo_clearReq_ehrReg___d45);
  DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46 = DEF_copFifo_clearReq_wires_0_whas____d43 ? DEF_copFifo_clearReq_wires_0_wget____d44 : DEF_copFifo_clearReq_ehrReg___d45;
  DEF_copFifo_deqReq_ehrReg___d37 = INST_copFifo_deqReq_ehrReg.METH_read();
  DEF_copFifo_enqReq_wires_1_whas____d4 = INST_copFifo_enqReq_wires_1.METH_whas();
  DEF_copFifo_enqReq_wires_0_whas____d7 = INST_copFifo_enqReq_wires_0.METH_whas();
  DEF_x__h9899 = INST_copFifo_deqP.METH_read();
  DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25 = (tUInt64)(137438953471llu & DEF_copFifo_enqReq_ehrReg___d10);
  DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11 = (tUInt8)(DEF_copFifo_enqReq_ehrReg___d10 >> 37u);
  DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 = (tUInt8)(DEF_copFifo_enqReq_wires_0_wget____d8 >> 37u);
  DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 = (tUInt8)(DEF_copFifo_enqReq_wires_1_wget____d5 >> 37u);
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13 = DEF_copFifo_enqReq_wires_1_whas____d4 ? DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 : (DEF_copFifo_enqReq_wires_0_whas____d7 ? DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 : DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11);
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27 = DEF_copFifo_enqReq_wires_1_whas____d4 ? (tUInt64)(137438953471llu & DEF_copFifo_enqReq_wires_1_wget____d5) : (DEF_copFifo_enqReq_wires_0_whas____d7 ? (tUInt64)(137438953471llu & DEF_copFifo_enqReq_wires_0_wget____d8) : DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25);
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20 = DEF_copFifo_enqReq_wires_1_whas____d4 ? !DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 : (DEF_copFifo_enqReq_wires_0_whas____d7 ? !DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 : !DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11);
  DEF_IF_copFifo_enqReq_virtual_reg_2_read__3_OR_IF__ETC___d87 = DEF_copFifo_enqReq_virtual_reg_2_read____d53 || DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20 ? DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27 : DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27;
  DEF_next_deqP___1__h5553 = !DEF_x__h9899 && (tUInt8)1u & (DEF_x__h9899 + (tUInt8)1u);
  DEF_NOT_copFifo_enqReq_virtual_reg_2_read__3_4_AND_ETC___d55 = !DEF_copFifo_enqReq_virtual_reg_2_read____d53 && DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13;
  DEF_v__h4858 = !DEF_copFifo_enqP__h5131 && (tUInt8)1u & (DEF_copFifo_enqP__h5131 + (tUInt8)1u);
  DEF_v__h4499 = DEF_NOT_copFifo_enqReq_virtual_reg_2_read__3_4_AND_ETC___d55 ? DEF_v__h4858 : DEF_copFifo_enqP__h5131;
  DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39 = INST_copFifo_deqReq_wires_1.METH_whas() ? INST_copFifo_deqReq_wires_1.METH_wget() : (INST_copFifo_deqReq_wires_0.METH_whas() ? INST_copFifo_deqReq_wires_0.METH_wget() : DEF_copFifo_deqReq_ehrReg___d37);
  DEF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3_AND_ETC___d64 = !INST_copFifo_deqReq_virtual_reg_2.METH_read() && DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39;
  DEF__theResult_____2__h5148 = DEF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3_AND_ETC___d64 ? DEF_next_deqP___1__h5553 : DEF_x__h9899;
  DEF_IF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3__ETC___d71 = DEF__theResult_____2__h5148 == DEF_v__h4499;
  DEF_NOT_copFifo_clearReq_virtual_reg_1_read__8_6_A_ETC___d82 = (!DEF_copFifo_clearReq_virtual_reg_1_read____d48 && DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46) || (DEF_IF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3__ETC___d71 && (DEF_NOT_copFifo_enqReq_virtual_reg_2_read__3_4_AND_ETC___d55 ? DEF_copFifo_empty__h5662 : DEF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3_AND_ETC___d64 || DEF_copFifo_empty__h5662));
  DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d84 = DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d52 && DEF_NOT_copFifo_enqReq_virtual_reg_2_read__3_4_AND_ETC___d55;
  DEF_copFifo_enqP_6_EQ_1_8_AND_copFifo_clearReq_vir_ETC___d89 = DEF_copFifo_enqP__h5131 == (tUInt8)1u && DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d84;
  DEF_copFifo_enqP_6_EQ_0_3_AND_copFifo_clearReq_vir_ETC___d85 = DEF_copFifo_enqP__h5131 == (tUInt8)0u && DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d84;
  DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d75 = DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d52 && (DEF_IF_NOT_copFifo_deqReq_virtual_reg_2_read__2_3__ETC___d71 && (DEF_NOT_copFifo_enqReq_virtual_reg_2_read__3_4_AND_ETC___d55 || DEF_copFifo_full__h5630));
  DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d61 = DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d52 && DEF_v__h4499;
  DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d70 = DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d52 && DEF__theResult_____2__h5148;
  DEF__0_CONCAT_DONTCARE___d90 = 45812984490llu;
  DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d92 = 274877906943llu & ((((tUInt64)(DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13)) << 37u) | (DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20 ? DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27 : DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27));
  INST_copFifo_enqP.METH_write(DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d61);
  INST_copFifo_deqP.METH_write(DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d70);
  INST_copFifo_full.METH_write(DEF_copFifo_clearReq_virtual_reg_1_read__8_OR_IF_c_ETC___d75);
  INST_copFifo_empty.METH_write(DEF_NOT_copFifo_clearReq_virtual_reg_1_read__8_6_A_ETC___d82);
  if (DEF_copFifo_enqP_6_EQ_0_3_AND_copFifo_clearReq_vir_ETC___d85)
    INST_copFifo_data_0.METH_write(DEF_IF_copFifo_enqReq_virtual_reg_2_read__3_OR_IF__ETC___d87);
  if (DEF_copFifo_enqP_6_EQ_1_8_AND_copFifo_clearReq_vir_ETC___d89)
    INST_copFifo_data_1.METH_write(DEF_IF_copFifo_enqReq_virtual_reg_2_read__3_OR_IF__ETC___d87);
  INST_copFifo_clearReq_ignored_wires_1.METH_wset(DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46);
  INST_copFifo_clearReq_wires_1.METH_wset((tUInt8)0u);
  INST_copFifo_clearReq_virtual_reg_1.METH_write((tUInt8)0u);
  INST_copFifo_enqReq_wires_2.METH_wset(DEF__0_CONCAT_DONTCARE___d90);
  INST_copFifo_enqReq_ignored_wires_2.METH_wset(DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d92);
  INST_copFifo_enqReq_virtual_reg_2.METH_write((tUInt8)0u);
  INST_copFifo_deqReq_wires_2.METH_wset((tUInt8)0u);
  INST_copFifo_deqReq_virtual_reg_2.METH_write((tUInt8)0u);
  INST_copFifo_deqReq_ignored_wires_2.METH_wset(DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39);
}

void MOD_mkCop::RL_statusReg_canonicalize()
{
  tUInt32 DEF_x__h7518;
  DEF_statusReg_ehrReg___d97 = INST_statusReg_ehrReg.METH_read();
  DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98 = INST_statusReg_wires_0.METH_whas() ? INST_statusReg_wires_0.METH_wget() : DEF_statusReg_ehrReg___d97;
  DEF_x__h7518 = INST_statusReg_wires_1.METH_whas() ? INST_statusReg_wires_1.METH_wget() : DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98;
  INST_statusReg_ehrReg.METH_write(DEF_x__h7518);
}

void MOD_mkCop::RL_epcReg_canonicalize()
{
  tUInt32 DEF_x__h8423;
  DEF_epcReg_ehrReg___d104 = INST_epcReg_ehrReg.METH_read();
  DEF_x__h10209 = INST_epcReg_wires_0.METH_whas() ? INST_epcReg_wires_0.METH_wget() : DEF_epcReg_ehrReg___d104;
  DEF_x__h8423 = INST_epcReg_wires_1.METH_whas() ? INST_epcReg_wires_1.METH_wget() : DEF_x__h10209;
  INST_epcReg_ehrReg.METH_write(DEF_x__h8423);
}

void MOD_mkCop::RL_count()
{
  tUInt32 DEF_x__h8649;
  DEF__read__h6794 = INST_cycles.METH_read();
  DEF_x__h8649 = DEF__read__h6794 + 1u;
  INST_cycles.METH_write(DEF_x__h8649);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF__read__h6794);
}


/* Methods */

void MOD_mkCop::METH_start()
{
  PORT_EN_start = (tUInt8)1u;
  DEF_WILL_FIRE_start = (tUInt8)1u;
  INST_startReg.METH_write((tUInt8)1u);
  INST_cycles.METH_write(0u);
}

tUInt8 MOD_mkCop::METH_RDY_start()
{
  DEF_CAN_FIRE_start = (tUInt8)1u;
  PORT_RDY_start = DEF_CAN_FIRE_start;
  return PORT_RDY_start;
}

tUInt8 MOD_mkCop::METH_started()
{
  DEF_startReg___d107 = INST_startReg.METH_read();
  PORT_started = DEF_startReg___d107;
  return PORT_started;
}

tUInt8 MOD_mkCop::METH_RDY_started()
{
  DEF_CAN_FIRE_started = (tUInt8)1u;
  PORT_RDY_started = DEF_CAN_FIRE_started;
  return PORT_RDY_started;
}

tUInt32 MOD_mkCop::METH_rd(tUInt8 ARG_rd_idx)
{
  tUInt8 DEF_rd_idx_EQ_10___d110;
  PORT_rd_idx = ARG_rd_idx;
  DEF_numInsts__h8772 = INST_numInsts.METH_read();
  DEF__read__h6794 = INST_cycles.METH_read();
  DEF_rd_idx_EQ_10___d110 = ARG_rd_idx == (tUInt8)10u;
  PORT_rd = DEF_rd_idx_EQ_10___d110 ? DEF__read__h6794 : DEF_numInsts__h8772;
  return PORT_rd;
}

tUInt8 MOD_mkCop::METH_RDY_rd()
{
  DEF_CAN_FIRE_rd = (tUInt8)1u;
  PORT_RDY_rd = DEF_CAN_FIRE_rd;
  return PORT_RDY_rd;
}

void MOD_mkCop::METH_wr(tUInt8 ARG_wr_idx, tUInt32 ARG_wr_val)
{
  tUInt64 DEF_copFifo_enqReq_ehrReg_0_BIT_37_1_CONCAT_IF_cop_ETC___d127;
  tUInt64 DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d125;
  tUInt32 DEF_x__h9684;
  tUInt8 DEF_wr_idx_BIT_6_12_AND_wr_idx_BIT_5_13_14_AND_IF__ETC___d122;
  tUInt8 DEF_x__h8930;
  tUInt8 DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d124;
  tUInt8 DEF_wr_idx_BIT_6___d112;
  tUInt8 DEF_wr_idx_BITS_4_TO_0___d115;
  PORT_EN_wr = (tUInt8)1u;
  DEF_WILL_FIRE_wr = (tUInt8)1u;
  PORT_wr_idx = ARG_wr_idx;
  PORT_wr_val = ARG_wr_val;
  DEF_copFifo_enqReq_ehrReg___d10 = INST_copFifo_enqReq_ehrReg.METH_read();
  DEF_numInsts__h8772 = INST_numInsts.METH_read();
  DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25 = (tUInt64)(137438953471llu & DEF_copFifo_enqReq_ehrReg___d10);
  DEF_wr_idx_BITS_4_TO_0___d115 = (tUInt8)((tUInt8)31u & ARG_wr_idx);
  DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11 = (tUInt8)(DEF_copFifo_enqReq_ehrReg___d10 >> 37u);
  DEF_wr_idx_BIT_6___d112 = (tUInt8)(ARG_wr_idx >> 6u);
  DEF_x__h8930 = DEF_wr_idx_BIT_6___d112 ? DEF_wr_idx_BITS_4_TO_0___d115 : DEF_wr_idx_BITS_4_TO_0___d115;
  switch (DEF_x__h8930) {
  case (tUInt8)18u:
    DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d124 = (tUInt8)50u;
    break;
  case (tUInt8)19u:
    DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d124 = (tUInt8)51u;
    break;
  default:
    DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d124 = (tUInt8)53u;
  }
  DEF_wr_idx_BIT_6_12_AND_wr_idx_BIT_5_13_14_AND_IF__ETC___d122 = (DEF_wr_idx_BIT_6___d112 && (tUInt8)((tUInt8)1u & (ARG_wr_idx >> 5u))) && (DEF_x__h8930 == (tUInt8)18u || (DEF_x__h8930 == (tUInt8)19u || DEF_x__h8930 == (tUInt8)21u));
  DEF_x__h9684 = DEF_numInsts__h8772 + 1u;
  DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d125 = 274877906943llu & ((((tUInt64)(DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d124)) << 32u) | (tUInt64)(ARG_wr_val));
  DEF_copFifo_enqReq_ehrReg_0_BIT_37_1_CONCAT_IF_cop_ETC___d127 = 274877906943llu & ((((tUInt64)(DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11)) << 37u) | (DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11 ? DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25 : DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25));
  if (DEF_wr_idx_BIT_6_12_AND_wr_idx_BIT_5_13_14_AND_IF__ETC___d122)
    INST_copFifo_enqReq_wires_0.METH_wset(DEF_IF_IF_wr_idx_BIT_6_12_THEN_wr_idx_BITS_4_TO_0__ETC___d125);
  if (DEF_wr_idx_BIT_6_12_AND_wr_idx_BIT_5_13_14_AND_IF__ETC___d122)
    INST_copFifo_enqReq_ignored_wires_0.METH_wset(DEF_copFifo_enqReq_ehrReg_0_BIT_37_1_CONCAT_IF_cop_ETC___d127);
  if (DEF_wr_idx_BIT_6_12_AND_wr_idx_BIT_5_13_14_AND_IF__ETC___d122)
    INST_copFifo_enqReq_virtual_reg_0.METH_write((tUInt8)0u);
  INST_numInsts.METH_write(DEF_x__h9684);
}

tUInt8 MOD_mkCop::METH_RDY_wr()
{
  DEF_copFifo_full__h5630 = INST_copFifo_full.METH_read();
  DEF_CAN_FIRE_wr = !DEF_copFifo_full__h5630;
  PORT_RDY_wr = DEF_CAN_FIRE_wr;
  return PORT_RDY_wr;
}

tUInt64 MOD_mkCop::METH_cpuToHost()
{
  tUInt8 DEF_x__h9704;
  tUInt32 DEF_x__h9924;
  tUInt8 DEF__read_fst__h9916;
  tUInt8 DEF__read_fst__h9912;
  tUInt32 DEF__read_snd__h9917;
  tUInt32 DEF__read_snd__h9913;
  tUInt64 DEF_ab__h9910;
  tUInt64 DEF_ab__h9914;
  PORT_EN_cpuToHost = (tUInt8)1u;
  DEF_WILL_FIRE_cpuToHost = (tUInt8)1u;
  DEF_ab__h9914 = INST_copFifo_data_1.METH_read();
  DEF_ab__h9910 = INST_copFifo_data_0.METH_read();
  DEF_copFifo_deqReq_ehrReg___d37 = INST_copFifo_deqReq_ehrReg.METH_read();
  DEF_x__h9899 = INST_copFifo_deqP.METH_read();
  DEF__read_snd__h9917 = (tUInt32)(DEF_ab__h9914);
  DEF__read_snd__h9913 = (tUInt32)(DEF_ab__h9910);
  DEF__read_fst__h9912 = (tUInt8)(DEF_ab__h9910 >> 32u);
  DEF__read_fst__h9916 = (tUInt8)(DEF_ab__h9914 >> 32u);
  switch (DEF_x__h9899) {
  case (tUInt8)0u:
    DEF_x__h9924 = DEF__read_snd__h9913;
    break;
  case (tUInt8)1u:
    DEF_x__h9924 = DEF__read_snd__h9917;
    break;
  default:
    DEF_x__h9924 = 2863311530u;
  }
  switch (DEF_x__h9899) {
  case (tUInt8)0u:
    DEF_x__h9704 = DEF__read_fst__h9912;
    break;
  case (tUInt8)1u:
    DEF_x__h9704 = DEF__read_fst__h9916;
    break;
  default:
    DEF_x__h9704 = (tUInt8)10u;
  }
  PORT_cpuToHost = 137438953471llu & ((((tUInt64)(DEF_x__h9704)) << 32u) | (tUInt64)(DEF_x__h9924));
  INST_copFifo_deqReq_wires_0.METH_wset((tUInt8)1u);
  INST_copFifo_deqReq_virtual_reg_0.METH_write((tUInt8)0u);
  INST_copFifo_deqReq_ignored_wires_0.METH_wset(DEF_copFifo_deqReq_ehrReg___d37);
  return PORT_cpuToHost;
}

tUInt8 MOD_mkCop::METH_RDY_cpuToHost()
{
  DEF_copFifo_empty__h5662 = INST_copFifo_empty.METH_read();
  DEF_CAN_FIRE_cpuToHost = !DEF_copFifo_empty__h5662;
  PORT_RDY_cpuToHost = DEF_CAN_FIRE_cpuToHost;
  return PORT_RDY_cpuToHost;
}

void MOD_mkCop::METH_causeException(tUInt32 ARG_causeException_current_pc,
				    tUInt8 ARG_causeException_cause)
{
  tUInt32 DEF_newCause__h10359;
  tUInt32 DEF_x__h10500;
  PORT_EN_causeException = (tUInt8)1u;
  DEF_WILL_FIRE_causeException = (tUInt8)1u;
  PORT_causeException_current_pc = ARG_causeException_current_pc;
  PORT_causeException_cause = ARG_causeException_cause;
  DEF_epcReg_ehrReg___d104 = INST_epcReg_ehrReg.METH_read();
  DEF_statusReg_ehrReg___d97 = INST_statusReg_ehrReg.METH_read();
  DEF_statusReg_virtual_reg_1_read____d140 = INST_statusReg_virtual_reg_1.METH_read();
  DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98 = INST_statusReg_wires_0.METH_whas() ? INST_statusReg_wires_0.METH_wget() : DEF_statusReg_ehrReg___d97;
  DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141 = DEF_statusReg_virtual_reg_1_read____d140 ? 0u : DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98;
  DEF_x__h10209 = INST_epcReg_wires_0.METH_whas() ? INST_epcReg_wires_0.METH_wget() : DEF_epcReg_ehrReg___d104;
  DEF_x__h10500 = (((tUInt32)((tUInt8)((tUInt8)15u & DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141))) << 2u) | (tUInt32)((tUInt8)0u);
  DEF_newCause__h10359 = (((tUInt32)(ARG_causeException_cause)) << 2u) | (tUInt32)((tUInt8)0u);
  INST_epcReg_wires_1.METH_wset(ARG_causeException_current_pc);
  INST_epcReg_ignored_wires_1.METH_wset(DEF_x__h10209);
  INST_epcReg_virtual_reg_1.METH_write((tUInt8)0u);
  INST_causeReg.METH_write(DEF_newCause__h10359);
  INST_statusReg_wires_1.METH_wset(DEF_x__h10500);
  INST_statusReg_virtual_reg_1.METH_write((tUInt8)0u);
  INST_statusReg_ignored_wires_1.METH_wset(DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98);
}

tUInt8 MOD_mkCop::METH_RDY_causeException()
{
  DEF_CAN_FIRE_causeException = (tUInt8)1u;
  PORT_RDY_causeException = DEF_CAN_FIRE_causeException;
  return PORT_RDY_causeException;
}

void MOD_mkCop::METH_returnFromException()
{
  tUInt32 DEF_x__h10919;
  PORT_EN_returnFromException = (tUInt8)1u;
  DEF_WILL_FIRE_returnFromException = (tUInt8)1u;
  DEF_statusReg_ehrReg___d97 = INST_statusReg_ehrReg.METH_read();
  DEF_statusReg_virtual_reg_1_read____d140 = INST_statusReg_virtual_reg_1.METH_read();
  DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98 = INST_statusReg_wires_0.METH_whas() ? INST_statusReg_wires_0.METH_wget() : DEF_statusReg_ehrReg___d97;
  DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141 = DEF_statusReg_virtual_reg_1_read____d140 ? 0u : DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98;
  DEF_x__h10919 = (((tUInt32)((tUInt8)0u)) << 30u) | (tUInt32)(DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141 >> 2u);
  INST_statusReg_wires_1.METH_wset(DEF_x__h10919);
  INST_statusReg_ignored_wires_1.METH_wset(DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98);
  INST_statusReg_virtual_reg_1.METH_write((tUInt8)0u);
}

tUInt8 MOD_mkCop::METH_RDY_returnFromException()
{
  DEF_CAN_FIRE_returnFromException = (tUInt8)1u;
  PORT_RDY_returnFromException = DEF_CAN_FIRE_returnFromException;
  return PORT_RDY_returnFromException;
}

tUInt32 MOD_mkCop::METH_getEPC()
{
  tUInt8 DEF_epcReg_virtual_reg_1_read__46_OR_epcReg_virtua_ETC___d148;
  DEF_epcReg_ehrReg___d104 = INST_epcReg_ehrReg.METH_read();
  DEF_epcReg_virtual_reg_1_read__46_OR_epcReg_virtua_ETC___d148 = INST_epcReg_virtual_reg_1.METH_read() || INST_epcReg_virtual_reg_0.METH_read();
  PORT_getEPC = DEF_epcReg_virtual_reg_1_read__46_OR_epcReg_virtua_ETC___d148 ? 0u : DEF_epcReg_ehrReg___d104;
  return PORT_getEPC;
}

tUInt8 MOD_mkCop::METH_RDY_getEPC()
{
  DEF_CAN_FIRE_getEPC = (tUInt8)1u;
  PORT_RDY_getEPC = DEF_CAN_FIRE_getEPC;
  return PORT_RDY_getEPC;
}

tUInt8 MOD_mkCop::METH_isUserMode()
{
  tUInt32 DEF_IF_statusReg_virtual_reg_1_read__40_OR_statusR_ETC___d151;
  DEF_statusReg_ehrReg___d97 = INST_statusReg_ehrReg.METH_read();
  DEF_statusReg_virtual_reg_1_read____d140 = INST_statusReg_virtual_reg_1.METH_read();
  DEF_IF_statusReg_virtual_reg_1_read__40_OR_statusR_ETC___d151 = DEF_statusReg_virtual_reg_1_read____d140 || INST_statusReg_virtual_reg_0.METH_read() ? 0u : DEF_statusReg_ehrReg___d97;
  PORT_isUserMode = (tUInt8)((tUInt8)1u & DEF_IF_statusReg_virtual_reg_1_read__40_OR_statusR_ETC___d151);
  return PORT_isUserMode;
}

tUInt8 MOD_mkCop::METH_RDY_isUserMode()
{
  DEF_CAN_FIRE_isUserMode = (tUInt8)1u;
  PORT_RDY_isUserMode = DEF_CAN_FIRE_isUserMode;
  return PORT_RDY_isUserMode;
}


/* Reset routines */

void MOD_mkCop::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_statusReg_ehrReg.reset_RST(ARG_rst_in);
  INST_startReg.reset_RST(ARG_rst_in);
  INST_numInsts.reset_RST(ARG_rst_in);
  INST_epcReg_ehrReg.reset_RST(ARG_rst_in);
  INST_cycles.reset_RST(ARG_rst_in);
  INST_copFifo_full.reset_RST(ARG_rst_in);
  INST_copFifo_enqReq_ehrReg.reset_RST(ARG_rst_in);
  INST_copFifo_enqP.reset_RST(ARG_rst_in);
  INST_copFifo_empty.reset_RST(ARG_rst_in);
  INST_copFifo_deqReq_ehrReg.reset_RST(ARG_rst_in);
  INST_copFifo_deqP.reset_RST(ARG_rst_in);
  INST_copFifo_clearReq_ehrReg.reset_RST(ARG_rst_in);
  INST_causeReg.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkCop::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkCop::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_causeReg.dump_state(indent + 2u);
  INST_copFifo_clearReq_ehrReg.dump_state(indent + 2u);
  INST_copFifo_clearReq_ignored_wires_0.dump_state(indent + 2u);
  INST_copFifo_clearReq_ignored_wires_1.dump_state(indent + 2u);
  INST_copFifo_clearReq_virtual_reg_0.dump_state(indent + 2u);
  INST_copFifo_clearReq_virtual_reg_1.dump_state(indent + 2u);
  INST_copFifo_clearReq_wires_0.dump_state(indent + 2u);
  INST_copFifo_clearReq_wires_1.dump_state(indent + 2u);
  INST_copFifo_data_0.dump_state(indent + 2u);
  INST_copFifo_data_1.dump_state(indent + 2u);
  INST_copFifo_deqP.dump_state(indent + 2u);
  INST_copFifo_deqReq_ehrReg.dump_state(indent + 2u);
  INST_copFifo_deqReq_ignored_wires_0.dump_state(indent + 2u);
  INST_copFifo_deqReq_ignored_wires_1.dump_state(indent + 2u);
  INST_copFifo_deqReq_ignored_wires_2.dump_state(indent + 2u);
  INST_copFifo_deqReq_virtual_reg_0.dump_state(indent + 2u);
  INST_copFifo_deqReq_virtual_reg_1.dump_state(indent + 2u);
  INST_copFifo_deqReq_virtual_reg_2.dump_state(indent + 2u);
  INST_copFifo_deqReq_wires_0.dump_state(indent + 2u);
  INST_copFifo_deqReq_wires_1.dump_state(indent + 2u);
  INST_copFifo_deqReq_wires_2.dump_state(indent + 2u);
  INST_copFifo_empty.dump_state(indent + 2u);
  INST_copFifo_enqP.dump_state(indent + 2u);
  INST_copFifo_enqReq_ehrReg.dump_state(indent + 2u);
  INST_copFifo_enqReq_ignored_wires_0.dump_state(indent + 2u);
  INST_copFifo_enqReq_ignored_wires_1.dump_state(indent + 2u);
  INST_copFifo_enqReq_ignored_wires_2.dump_state(indent + 2u);
  INST_copFifo_enqReq_virtual_reg_0.dump_state(indent + 2u);
  INST_copFifo_enqReq_virtual_reg_1.dump_state(indent + 2u);
  INST_copFifo_enqReq_virtual_reg_2.dump_state(indent + 2u);
  INST_copFifo_enqReq_wires_0.dump_state(indent + 2u);
  INST_copFifo_enqReq_wires_1.dump_state(indent + 2u);
  INST_copFifo_enqReq_wires_2.dump_state(indent + 2u);
  INST_copFifo_full.dump_state(indent + 2u);
  INST_cycles.dump_state(indent + 2u);
  INST_epcReg_ehrReg.dump_state(indent + 2u);
  INST_epcReg_ignored_wires_0.dump_state(indent + 2u);
  INST_epcReg_ignored_wires_1.dump_state(indent + 2u);
  INST_epcReg_virtual_reg_0.dump_state(indent + 2u);
  INST_epcReg_virtual_reg_1.dump_state(indent + 2u);
  INST_epcReg_wires_0.dump_state(indent + 2u);
  INST_epcReg_wires_1.dump_state(indent + 2u);
  INST_numInsts.dump_state(indent + 2u);
  INST_startReg.dump_state(indent + 2u);
  INST_statusReg_ehrReg.dump_state(indent + 2u);
  INST_statusReg_ignored_wires_0.dump_state(indent + 2u);
  INST_statusReg_ignored_wires_1.dump_state(indent + 2u);
  INST_statusReg_virtual_reg_0.dump_state(indent + 2u);
  INST_statusReg_virtual_reg_1.dump_state(indent + 2u);
  INST_statusReg_wires_0.dump_state(indent + 2u);
  INST_statusReg_wires_1.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkCop::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 134u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_copFifo_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_copFifo_clearReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_copFifo_deqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_copFifo_enqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_count", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_epcReg_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_statusReg_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_causeException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_getEPC", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_isUserMode", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_rd", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_returnFromException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_started", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27", 37u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98", 32u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_copFifo_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_copFifo_clearReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_copFifo_deqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_copFifo_enqReq_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_count", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_epcReg_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_statusReg_canonicalize", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_causeException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_returnFromException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h6794", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_clearReq_ehrReg___d45", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_clearReq_wires_0_wget____d44", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_clearReq_wires_0_whas____d43", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_deqReq_ehrReg___d37", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_empty__h5662", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25", 37u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_ehrReg_0_BIT_37___d11", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_ehrReg___d10", 38u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_wires_0_wget_BIT_37___d9", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_wires_0_wget____d8", 38u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_wires_0_whas____d7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_wires_1_wget_BIT_37___d6", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_wires_1_wget____d5", 38u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_enqReq_wires_1_whas____d4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "copFifo_full__h5630", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "epcReg_ehrReg___d104", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "numInsts__h8772", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "startReg___d107", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "statusReg_ehrReg___d97", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "statusReg_virtual_reg_1_read____d140", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h10209", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h9899", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_causeException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_returnFromException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_causeException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_cpuToHost", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_getEPC", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_isUserMode", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_rd", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_returnFromException", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_start", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_started", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_wr", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "causeException_cause", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "causeException_current_pc", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "cpuToHost", 37u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "getEPC", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "isUserMode", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "rd", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "rd_idx", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "started", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "wr_idx", 7u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "wr_val", 32u);
  num = INST_causeReg.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_ehrReg.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_wires_0.dump_VCD_defs(num);
  num = INST_copFifo_clearReq_wires_1.dump_VCD_defs(num);
  num = INST_copFifo_data_0.dump_VCD_defs(num);
  num = INST_copFifo_data_1.dump_VCD_defs(num);
  num = INST_copFifo_deqP.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_ehrReg.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_ignored_wires_2.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_virtual_reg_2.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_wires_0.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_wires_1.dump_VCD_defs(num);
  num = INST_copFifo_deqReq_wires_2.dump_VCD_defs(num);
  num = INST_copFifo_empty.dump_VCD_defs(num);
  num = INST_copFifo_enqP.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_ehrReg.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_ignored_wires_0.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_ignored_wires_1.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_ignored_wires_2.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_virtual_reg_0.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_virtual_reg_1.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_virtual_reg_2.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_wires_0.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_wires_1.dump_VCD_defs(num);
  num = INST_copFifo_enqReq_wires_2.dump_VCD_defs(num);
  num = INST_copFifo_full.dump_VCD_defs(num);
  num = INST_cycles.dump_VCD_defs(num);
  num = INST_epcReg_ehrReg.dump_VCD_defs(num);
  num = INST_epcReg_ignored_wires_0.dump_VCD_defs(num);
  num = INST_epcReg_ignored_wires_1.dump_VCD_defs(num);
  num = INST_epcReg_virtual_reg_0.dump_VCD_defs(num);
  num = INST_epcReg_virtual_reg_1.dump_VCD_defs(num);
  num = INST_epcReg_wires_0.dump_VCD_defs(num);
  num = INST_epcReg_wires_1.dump_VCD_defs(num);
  num = INST_numInsts.dump_VCD_defs(num);
  num = INST_startReg.dump_VCD_defs(num);
  num = INST_statusReg_ehrReg.dump_VCD_defs(num);
  num = INST_statusReg_ignored_wires_0.dump_VCD_defs(num);
  num = INST_statusReg_ignored_wires_1.dump_VCD_defs(num);
  num = INST_statusReg_virtual_reg_0.dump_VCD_defs(num);
  num = INST_statusReg_virtual_reg_1.dump_VCD_defs(num);
  num = INST_statusReg_wires_0.dump_VCD_defs(num);
  num = INST_statusReg_wires_1.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkCop::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCop &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkCop::vcd_defs(tVCDDumpType dt, MOD_mkCop &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 37u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 37u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 38u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 38u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 38u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 37u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 7u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_copFifo_canonicalize) != DEF_CAN_FIRE_RL_copFifo_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_copFifo_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_copFifo_canonicalize = DEF_CAN_FIRE_RL_copFifo_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize) != DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize = DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize) != DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize = DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize) != DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize = DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_count) != DEF_CAN_FIRE_RL_count)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_count, 1u);
	backing.DEF_CAN_FIRE_RL_count = DEF_CAN_FIRE_RL_count;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_epcReg_canonicalize) != DEF_CAN_FIRE_RL_epcReg_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_epcReg_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_epcReg_canonicalize = DEF_CAN_FIRE_RL_epcReg_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_RL_statusReg_canonicalize) != DEF_CAN_FIRE_RL_statusReg_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_statusReg_canonicalize, 1u);
	backing.DEF_CAN_FIRE_RL_statusReg_canonicalize = DEF_CAN_FIRE_RL_statusReg_canonicalize;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_causeException) != DEF_CAN_FIRE_causeException)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_causeException, 1u);
	backing.DEF_CAN_FIRE_causeException = DEF_CAN_FIRE_causeException;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_cpuToHost) != DEF_CAN_FIRE_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_cpuToHost, 1u);
	backing.DEF_CAN_FIRE_cpuToHost = DEF_CAN_FIRE_cpuToHost;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_getEPC) != DEF_CAN_FIRE_getEPC)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_getEPC, 1u);
	backing.DEF_CAN_FIRE_getEPC = DEF_CAN_FIRE_getEPC;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_isUserMode) != DEF_CAN_FIRE_isUserMode)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_isUserMode, 1u);
	backing.DEF_CAN_FIRE_isUserMode = DEF_CAN_FIRE_isUserMode;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_rd) != DEF_CAN_FIRE_rd)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_rd, 1u);
	backing.DEF_CAN_FIRE_rd = DEF_CAN_FIRE_rd;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_returnFromException) != DEF_CAN_FIRE_returnFromException)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_returnFromException, 1u);
	backing.DEF_CAN_FIRE_returnFromException = DEF_CAN_FIRE_returnFromException;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_start) != DEF_CAN_FIRE_start)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_start, 1u);
	backing.DEF_CAN_FIRE_start = DEF_CAN_FIRE_start;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_started) != DEF_CAN_FIRE_started)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_started, 1u);
	backing.DEF_CAN_FIRE_started = DEF_CAN_FIRE_started;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_wr) != DEF_CAN_FIRE_wr)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_wr, 1u);
	backing.DEF_CAN_FIRE_wr = DEF_CAN_FIRE_wr;
      }
      ++num;
      if ((backing.DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46) != DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46, 1u);
	backing.DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46 = DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46;
      }
      ++num;
      if ((backing.DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39) != DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39, 1u);
	backing.DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39 = DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39;
      }
      ++num;
      if ((backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20) != DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20, 1u);
	backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20 = DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20;
      }
      ++num;
      if ((backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13) != DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13, 1u);
	backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13 = DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13;
      }
      ++num;
      if ((backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27) != DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27, 37u);
	backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27 = DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27;
      }
      ++num;
      if ((backing.DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141) != DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141, 32u);
	backing.DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141 = DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141;
      }
      ++num;
      if ((backing.DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98) != DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98, 32u);
	backing.DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98 = DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_copFifo_canonicalize) != DEF_WILL_FIRE_RL_copFifo_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_copFifo_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_copFifo_canonicalize = DEF_WILL_FIRE_RL_copFifo_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize) != DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize = DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize) != DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize = DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize) != DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize = DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_count) != DEF_WILL_FIRE_RL_count)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_count, 1u);
	backing.DEF_WILL_FIRE_RL_count = DEF_WILL_FIRE_RL_count;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_epcReg_canonicalize) != DEF_WILL_FIRE_RL_epcReg_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_epcReg_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_epcReg_canonicalize = DEF_WILL_FIRE_RL_epcReg_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_statusReg_canonicalize) != DEF_WILL_FIRE_RL_statusReg_canonicalize)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_statusReg_canonicalize, 1u);
	backing.DEF_WILL_FIRE_RL_statusReg_canonicalize = DEF_WILL_FIRE_RL_statusReg_canonicalize;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_causeException) != DEF_WILL_FIRE_causeException)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_causeException, 1u);
	backing.DEF_WILL_FIRE_causeException = DEF_WILL_FIRE_causeException;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_cpuToHost) != DEF_WILL_FIRE_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_cpuToHost, 1u);
	backing.DEF_WILL_FIRE_cpuToHost = DEF_WILL_FIRE_cpuToHost;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_returnFromException) != DEF_WILL_FIRE_returnFromException)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_returnFromException, 1u);
	backing.DEF_WILL_FIRE_returnFromException = DEF_WILL_FIRE_returnFromException;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_start) != DEF_WILL_FIRE_start)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_start, 1u);
	backing.DEF_WILL_FIRE_start = DEF_WILL_FIRE_start;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_wr) != DEF_WILL_FIRE_wr)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_wr, 1u);
	backing.DEF_WILL_FIRE_wr = DEF_WILL_FIRE_wr;
      }
      ++num;
      if ((backing.DEF__read__h6794) != DEF__read__h6794)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h6794, 32u);
	backing.DEF__read__h6794 = DEF__read__h6794;
      }
      ++num;
      if ((backing.DEF_copFifo_clearReq_ehrReg___d45) != DEF_copFifo_clearReq_ehrReg___d45)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_clearReq_ehrReg___d45, 1u);
	backing.DEF_copFifo_clearReq_ehrReg___d45 = DEF_copFifo_clearReq_ehrReg___d45;
      }
      ++num;
      if ((backing.DEF_copFifo_clearReq_wires_0_wget____d44) != DEF_copFifo_clearReq_wires_0_wget____d44)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_clearReq_wires_0_wget____d44, 1u);
	backing.DEF_copFifo_clearReq_wires_0_wget____d44 = DEF_copFifo_clearReq_wires_0_wget____d44;
      }
      ++num;
      if ((backing.DEF_copFifo_clearReq_wires_0_whas____d43) != DEF_copFifo_clearReq_wires_0_whas____d43)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_clearReq_wires_0_whas____d43, 1u);
	backing.DEF_copFifo_clearReq_wires_0_whas____d43 = DEF_copFifo_clearReq_wires_0_whas____d43;
      }
      ++num;
      if ((backing.DEF_copFifo_deqReq_ehrReg___d37) != DEF_copFifo_deqReq_ehrReg___d37)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_deqReq_ehrReg___d37, 1u);
	backing.DEF_copFifo_deqReq_ehrReg___d37 = DEF_copFifo_deqReq_ehrReg___d37;
      }
      ++num;
      if ((backing.DEF_copFifo_empty__h5662) != DEF_copFifo_empty__h5662)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_empty__h5662, 1u);
	backing.DEF_copFifo_empty__h5662 = DEF_copFifo_empty__h5662;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25) != DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25, 37u);
	backing.DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25 = DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11) != DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11, 1u);
	backing.DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11 = DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_ehrReg___d10) != DEF_copFifo_enqReq_ehrReg___d10)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_ehrReg___d10, 38u);
	backing.DEF_copFifo_enqReq_ehrReg___d10 = DEF_copFifo_enqReq_ehrReg___d10;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9) != DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9, 1u);
	backing.DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 = DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_wires_0_wget____d8) != DEF_copFifo_enqReq_wires_0_wget____d8)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_wires_0_wget____d8, 38u);
	backing.DEF_copFifo_enqReq_wires_0_wget____d8 = DEF_copFifo_enqReq_wires_0_wget____d8;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_wires_0_whas____d7) != DEF_copFifo_enqReq_wires_0_whas____d7)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_wires_0_whas____d7, 1u);
	backing.DEF_copFifo_enqReq_wires_0_whas____d7 = DEF_copFifo_enqReq_wires_0_whas____d7;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6) != DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6, 1u);
	backing.DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 = DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_wires_1_wget____d5) != DEF_copFifo_enqReq_wires_1_wget____d5)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_wires_1_wget____d5, 38u);
	backing.DEF_copFifo_enqReq_wires_1_wget____d5 = DEF_copFifo_enqReq_wires_1_wget____d5;
      }
      ++num;
      if ((backing.DEF_copFifo_enqReq_wires_1_whas____d4) != DEF_copFifo_enqReq_wires_1_whas____d4)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_enqReq_wires_1_whas____d4, 1u);
	backing.DEF_copFifo_enqReq_wires_1_whas____d4 = DEF_copFifo_enqReq_wires_1_whas____d4;
      }
      ++num;
      if ((backing.DEF_copFifo_full__h5630) != DEF_copFifo_full__h5630)
      {
	vcd_write_val(sim_hdl, num, DEF_copFifo_full__h5630, 1u);
	backing.DEF_copFifo_full__h5630 = DEF_copFifo_full__h5630;
      }
      ++num;
      if ((backing.DEF_epcReg_ehrReg___d104) != DEF_epcReg_ehrReg___d104)
      {
	vcd_write_val(sim_hdl, num, DEF_epcReg_ehrReg___d104, 32u);
	backing.DEF_epcReg_ehrReg___d104 = DEF_epcReg_ehrReg___d104;
      }
      ++num;
      if ((backing.DEF_numInsts__h8772) != DEF_numInsts__h8772)
      {
	vcd_write_val(sim_hdl, num, DEF_numInsts__h8772, 32u);
	backing.DEF_numInsts__h8772 = DEF_numInsts__h8772;
      }
      ++num;
      if ((backing.DEF_startReg___d107) != DEF_startReg___d107)
      {
	vcd_write_val(sim_hdl, num, DEF_startReg___d107, 1u);
	backing.DEF_startReg___d107 = DEF_startReg___d107;
      }
      ++num;
      if ((backing.DEF_statusReg_ehrReg___d97) != DEF_statusReg_ehrReg___d97)
      {
	vcd_write_val(sim_hdl, num, DEF_statusReg_ehrReg___d97, 32u);
	backing.DEF_statusReg_ehrReg___d97 = DEF_statusReg_ehrReg___d97;
      }
      ++num;
      if ((backing.DEF_statusReg_virtual_reg_1_read____d140) != DEF_statusReg_virtual_reg_1_read____d140)
      {
	vcd_write_val(sim_hdl, num, DEF_statusReg_virtual_reg_1_read____d140, 1u);
	backing.DEF_statusReg_virtual_reg_1_read____d140 = DEF_statusReg_virtual_reg_1_read____d140;
      }
      ++num;
      if ((backing.DEF_x__h10209) != DEF_x__h10209)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h10209, 32u);
	backing.DEF_x__h10209 = DEF_x__h10209;
      }
      ++num;
      if ((backing.DEF_x__h9899) != DEF_x__h9899)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h9899, 1u);
	backing.DEF_x__h9899 = DEF_x__h9899;
      }
      ++num;
      if ((backing.PORT_EN_causeException) != PORT_EN_causeException)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_causeException, 1u);
	backing.PORT_EN_causeException = PORT_EN_causeException;
      }
      ++num;
      if ((backing.PORT_EN_cpuToHost) != PORT_EN_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_cpuToHost, 1u);
	backing.PORT_EN_cpuToHost = PORT_EN_cpuToHost;
      }
      ++num;
      if ((backing.PORT_EN_returnFromException) != PORT_EN_returnFromException)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_returnFromException, 1u);
	backing.PORT_EN_returnFromException = PORT_EN_returnFromException;
      }
      ++num;
      if ((backing.PORT_EN_start) != PORT_EN_start)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_start, 1u);
	backing.PORT_EN_start = PORT_EN_start;
      }
      ++num;
      if ((backing.PORT_EN_wr) != PORT_EN_wr)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_wr, 1u);
	backing.PORT_EN_wr = PORT_EN_wr;
      }
      ++num;
      if ((backing.PORT_RDY_causeException) != PORT_RDY_causeException)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_causeException, 1u);
	backing.PORT_RDY_causeException = PORT_RDY_causeException;
      }
      ++num;
      if ((backing.PORT_RDY_cpuToHost) != PORT_RDY_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_cpuToHost, 1u);
	backing.PORT_RDY_cpuToHost = PORT_RDY_cpuToHost;
      }
      ++num;
      if ((backing.PORT_RDY_getEPC) != PORT_RDY_getEPC)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_getEPC, 1u);
	backing.PORT_RDY_getEPC = PORT_RDY_getEPC;
      }
      ++num;
      if ((backing.PORT_RDY_isUserMode) != PORT_RDY_isUserMode)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_isUserMode, 1u);
	backing.PORT_RDY_isUserMode = PORT_RDY_isUserMode;
      }
      ++num;
      if ((backing.PORT_RDY_rd) != PORT_RDY_rd)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_rd, 1u);
	backing.PORT_RDY_rd = PORT_RDY_rd;
      }
      ++num;
      if ((backing.PORT_RDY_returnFromException) != PORT_RDY_returnFromException)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_returnFromException, 1u);
	backing.PORT_RDY_returnFromException = PORT_RDY_returnFromException;
      }
      ++num;
      if ((backing.PORT_RDY_start) != PORT_RDY_start)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_start, 1u);
	backing.PORT_RDY_start = PORT_RDY_start;
      }
      ++num;
      if ((backing.PORT_RDY_started) != PORT_RDY_started)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_started, 1u);
	backing.PORT_RDY_started = PORT_RDY_started;
      }
      ++num;
      if ((backing.PORT_RDY_wr) != PORT_RDY_wr)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_wr, 1u);
	backing.PORT_RDY_wr = PORT_RDY_wr;
      }
      ++num;
      if ((backing.PORT_causeException_cause) != PORT_causeException_cause)
      {
	vcd_write_val(sim_hdl, num, PORT_causeException_cause, 5u);
	backing.PORT_causeException_cause = PORT_causeException_cause;
      }
      ++num;
      if ((backing.PORT_causeException_current_pc) != PORT_causeException_current_pc)
      {
	vcd_write_val(sim_hdl, num, PORT_causeException_current_pc, 32u);
	backing.PORT_causeException_current_pc = PORT_causeException_current_pc;
      }
      ++num;
      if ((backing.PORT_cpuToHost) != PORT_cpuToHost)
      {
	vcd_write_val(sim_hdl, num, PORT_cpuToHost, 37u);
	backing.PORT_cpuToHost = PORT_cpuToHost;
      }
      ++num;
      if ((backing.PORT_getEPC) != PORT_getEPC)
      {
	vcd_write_val(sim_hdl, num, PORT_getEPC, 32u);
	backing.PORT_getEPC = PORT_getEPC;
      }
      ++num;
      if ((backing.PORT_isUserMode) != PORT_isUserMode)
      {
	vcd_write_val(sim_hdl, num, PORT_isUserMode, 1u);
	backing.PORT_isUserMode = PORT_isUserMode;
      }
      ++num;
      if ((backing.PORT_rd) != PORT_rd)
      {
	vcd_write_val(sim_hdl, num, PORT_rd, 32u);
	backing.PORT_rd = PORT_rd;
      }
      ++num;
      if ((backing.PORT_rd_idx) != PORT_rd_idx)
      {
	vcd_write_val(sim_hdl, num, PORT_rd_idx, 5u);
	backing.PORT_rd_idx = PORT_rd_idx;
      }
      ++num;
      if ((backing.PORT_started) != PORT_started)
      {
	vcd_write_val(sim_hdl, num, PORT_started, 1u);
	backing.PORT_started = PORT_started;
      }
      ++num;
      if ((backing.PORT_wr_idx) != PORT_wr_idx)
      {
	vcd_write_val(sim_hdl, num, PORT_wr_idx, 7u);
	backing.PORT_wr_idx = PORT_wr_idx;
      }
      ++num;
      if ((backing.PORT_wr_val) != PORT_wr_val)
      {
	vcd_write_val(sim_hdl, num, PORT_wr_val, 32u);
	backing.PORT_wr_val = PORT_wr_val;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_copFifo_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_copFifo_canonicalize = DEF_CAN_FIRE_RL_copFifo_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize = DEF_CAN_FIRE_RL_copFifo_clearReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize = DEF_CAN_FIRE_RL_copFifo_deqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize = DEF_CAN_FIRE_RL_copFifo_enqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_count, 1u);
      backing.DEF_CAN_FIRE_RL_count = DEF_CAN_FIRE_RL_count;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_epcReg_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_epcReg_canonicalize = DEF_CAN_FIRE_RL_epcReg_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_statusReg_canonicalize, 1u);
      backing.DEF_CAN_FIRE_RL_statusReg_canonicalize = DEF_CAN_FIRE_RL_statusReg_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_causeException, 1u);
      backing.DEF_CAN_FIRE_causeException = DEF_CAN_FIRE_causeException;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_cpuToHost, 1u);
      backing.DEF_CAN_FIRE_cpuToHost = DEF_CAN_FIRE_cpuToHost;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_getEPC, 1u);
      backing.DEF_CAN_FIRE_getEPC = DEF_CAN_FIRE_getEPC;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_isUserMode, 1u);
      backing.DEF_CAN_FIRE_isUserMode = DEF_CAN_FIRE_isUserMode;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_rd, 1u);
      backing.DEF_CAN_FIRE_rd = DEF_CAN_FIRE_rd;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_returnFromException, 1u);
      backing.DEF_CAN_FIRE_returnFromException = DEF_CAN_FIRE_returnFromException;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_start, 1u);
      backing.DEF_CAN_FIRE_start = DEF_CAN_FIRE_start;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_started, 1u);
      backing.DEF_CAN_FIRE_started = DEF_CAN_FIRE_started;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_wr, 1u);
      backing.DEF_CAN_FIRE_wr = DEF_CAN_FIRE_wr;
      vcd_write_val(sim_hdl, num++, DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46, 1u);
      backing.DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46 = DEF_IF_copFifo_clearReq_wires_0_whas__3_THEN_copFi_ETC___d46;
      vcd_write_val(sim_hdl, num++, DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39, 1u);
      backing.DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39 = DEF_IF_copFifo_deqReq_wires_1_whas__3_THEN_copFifo_ETC___d39;
      vcd_write_val(sim_hdl, num++, DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20, 1u);
      backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20 = DEF_IF_copFifo_enqReq_wires_1_whas_THEN_NOT_copFif_ETC___d20;
      vcd_write_val(sim_hdl, num++, DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13, 1u);
      backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13 = DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d13;
      vcd_write_val(sim_hdl, num++, DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27, 37u);
      backing.DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27 = DEF_IF_copFifo_enqReq_wires_1_whas_THEN_copFifo_en_ETC___d27;
      vcd_write_val(sim_hdl, num++, DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141, 32u);
      backing.DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141 = DEF_IF_statusReg_virtual_reg_1_read__40_THEN_0_ELS_ETC___d141;
      vcd_write_val(sim_hdl, num++, DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98, 32u);
      backing.DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98 = DEF_IF_statusReg_wires_0_whas__5_THEN_statusReg_wi_ETC___d98;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_copFifo_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_copFifo_canonicalize = DEF_WILL_FIRE_RL_copFifo_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize = DEF_WILL_FIRE_RL_copFifo_clearReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize = DEF_WILL_FIRE_RL_copFifo_deqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize = DEF_WILL_FIRE_RL_copFifo_enqReq_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_count, 1u);
      backing.DEF_WILL_FIRE_RL_count = DEF_WILL_FIRE_RL_count;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_epcReg_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_epcReg_canonicalize = DEF_WILL_FIRE_RL_epcReg_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_statusReg_canonicalize, 1u);
      backing.DEF_WILL_FIRE_RL_statusReg_canonicalize = DEF_WILL_FIRE_RL_statusReg_canonicalize;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_causeException, 1u);
      backing.DEF_WILL_FIRE_causeException = DEF_WILL_FIRE_causeException;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_cpuToHost, 1u);
      backing.DEF_WILL_FIRE_cpuToHost = DEF_WILL_FIRE_cpuToHost;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_returnFromException, 1u);
      backing.DEF_WILL_FIRE_returnFromException = DEF_WILL_FIRE_returnFromException;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_start, 1u);
      backing.DEF_WILL_FIRE_start = DEF_WILL_FIRE_start;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_wr, 1u);
      backing.DEF_WILL_FIRE_wr = DEF_WILL_FIRE_wr;
      vcd_write_val(sim_hdl, num++, DEF__read__h6794, 32u);
      backing.DEF__read__h6794 = DEF__read__h6794;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_clearReq_ehrReg___d45, 1u);
      backing.DEF_copFifo_clearReq_ehrReg___d45 = DEF_copFifo_clearReq_ehrReg___d45;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_clearReq_wires_0_wget____d44, 1u);
      backing.DEF_copFifo_clearReq_wires_0_wget____d44 = DEF_copFifo_clearReq_wires_0_wget____d44;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_clearReq_wires_0_whas____d43, 1u);
      backing.DEF_copFifo_clearReq_wires_0_whas____d43 = DEF_copFifo_clearReq_wires_0_whas____d43;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_deqReq_ehrReg___d37, 1u);
      backing.DEF_copFifo_deqReq_ehrReg___d37 = DEF_copFifo_deqReq_ehrReg___d37;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_empty__h5662, 1u);
      backing.DEF_copFifo_empty__h5662 = DEF_copFifo_empty__h5662;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25, 37u);
      backing.DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25 = DEF_copFifo_enqReq_ehrReg_0_BITS_36_TO_0___d25;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11, 1u);
      backing.DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11 = DEF_copFifo_enqReq_ehrReg_0_BIT_37___d11;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_ehrReg___d10, 38u);
      backing.DEF_copFifo_enqReq_ehrReg___d10 = DEF_copFifo_enqReq_ehrReg___d10;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9, 1u);
      backing.DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9 = DEF_copFifo_enqReq_wires_0_wget_BIT_37___d9;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_wires_0_wget____d8, 38u);
      backing.DEF_copFifo_enqReq_wires_0_wget____d8 = DEF_copFifo_enqReq_wires_0_wget____d8;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_wires_0_whas____d7, 1u);
      backing.DEF_copFifo_enqReq_wires_0_whas____d7 = DEF_copFifo_enqReq_wires_0_whas____d7;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6, 1u);
      backing.DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6 = DEF_copFifo_enqReq_wires_1_wget_BIT_37___d6;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_wires_1_wget____d5, 38u);
      backing.DEF_copFifo_enqReq_wires_1_wget____d5 = DEF_copFifo_enqReq_wires_1_wget____d5;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_enqReq_wires_1_whas____d4, 1u);
      backing.DEF_copFifo_enqReq_wires_1_whas____d4 = DEF_copFifo_enqReq_wires_1_whas____d4;
      vcd_write_val(sim_hdl, num++, DEF_copFifo_full__h5630, 1u);
      backing.DEF_copFifo_full__h5630 = DEF_copFifo_full__h5630;
      vcd_write_val(sim_hdl, num++, DEF_epcReg_ehrReg___d104, 32u);
      backing.DEF_epcReg_ehrReg___d104 = DEF_epcReg_ehrReg___d104;
      vcd_write_val(sim_hdl, num++, DEF_numInsts__h8772, 32u);
      backing.DEF_numInsts__h8772 = DEF_numInsts__h8772;
      vcd_write_val(sim_hdl, num++, DEF_startReg___d107, 1u);
      backing.DEF_startReg___d107 = DEF_startReg___d107;
      vcd_write_val(sim_hdl, num++, DEF_statusReg_ehrReg___d97, 32u);
      backing.DEF_statusReg_ehrReg___d97 = DEF_statusReg_ehrReg___d97;
      vcd_write_val(sim_hdl, num++, DEF_statusReg_virtual_reg_1_read____d140, 1u);
      backing.DEF_statusReg_virtual_reg_1_read____d140 = DEF_statusReg_virtual_reg_1_read____d140;
      vcd_write_val(sim_hdl, num++, DEF_x__h10209, 32u);
      backing.DEF_x__h10209 = DEF_x__h10209;
      vcd_write_val(sim_hdl, num++, DEF_x__h9899, 1u);
      backing.DEF_x__h9899 = DEF_x__h9899;
      vcd_write_val(sim_hdl, num++, PORT_EN_causeException, 1u);
      backing.PORT_EN_causeException = PORT_EN_causeException;
      vcd_write_val(sim_hdl, num++, PORT_EN_cpuToHost, 1u);
      backing.PORT_EN_cpuToHost = PORT_EN_cpuToHost;
      vcd_write_val(sim_hdl, num++, PORT_EN_returnFromException, 1u);
      backing.PORT_EN_returnFromException = PORT_EN_returnFromException;
      vcd_write_val(sim_hdl, num++, PORT_EN_start, 1u);
      backing.PORT_EN_start = PORT_EN_start;
      vcd_write_val(sim_hdl, num++, PORT_EN_wr, 1u);
      backing.PORT_EN_wr = PORT_EN_wr;
      vcd_write_val(sim_hdl, num++, PORT_RDY_causeException, 1u);
      backing.PORT_RDY_causeException = PORT_RDY_causeException;
      vcd_write_val(sim_hdl, num++, PORT_RDY_cpuToHost, 1u);
      backing.PORT_RDY_cpuToHost = PORT_RDY_cpuToHost;
      vcd_write_val(sim_hdl, num++, PORT_RDY_getEPC, 1u);
      backing.PORT_RDY_getEPC = PORT_RDY_getEPC;
      vcd_write_val(sim_hdl, num++, PORT_RDY_isUserMode, 1u);
      backing.PORT_RDY_isUserMode = PORT_RDY_isUserMode;
      vcd_write_val(sim_hdl, num++, PORT_RDY_rd, 1u);
      backing.PORT_RDY_rd = PORT_RDY_rd;
      vcd_write_val(sim_hdl, num++, PORT_RDY_returnFromException, 1u);
      backing.PORT_RDY_returnFromException = PORT_RDY_returnFromException;
      vcd_write_val(sim_hdl, num++, PORT_RDY_start, 1u);
      backing.PORT_RDY_start = PORT_RDY_start;
      vcd_write_val(sim_hdl, num++, PORT_RDY_started, 1u);
      backing.PORT_RDY_started = PORT_RDY_started;
      vcd_write_val(sim_hdl, num++, PORT_RDY_wr, 1u);
      backing.PORT_RDY_wr = PORT_RDY_wr;
      vcd_write_val(sim_hdl, num++, PORT_causeException_cause, 5u);
      backing.PORT_causeException_cause = PORT_causeException_cause;
      vcd_write_val(sim_hdl, num++, PORT_causeException_current_pc, 32u);
      backing.PORT_causeException_current_pc = PORT_causeException_current_pc;
      vcd_write_val(sim_hdl, num++, PORT_cpuToHost, 37u);
      backing.PORT_cpuToHost = PORT_cpuToHost;
      vcd_write_val(sim_hdl, num++, PORT_getEPC, 32u);
      backing.PORT_getEPC = PORT_getEPC;
      vcd_write_val(sim_hdl, num++, PORT_isUserMode, 1u);
      backing.PORT_isUserMode = PORT_isUserMode;
      vcd_write_val(sim_hdl, num++, PORT_rd, 32u);
      backing.PORT_rd = PORT_rd;
      vcd_write_val(sim_hdl, num++, PORT_rd_idx, 5u);
      backing.PORT_rd_idx = PORT_rd_idx;
      vcd_write_val(sim_hdl, num++, PORT_started, 1u);
      backing.PORT_started = PORT_started;
      vcd_write_val(sim_hdl, num++, PORT_wr_idx, 7u);
      backing.PORT_wr_idx = PORT_wr_idx;
      vcd_write_val(sim_hdl, num++, PORT_wr_val, 32u);
      backing.PORT_wr_val = PORT_wr_val;
    }
}

void MOD_mkCop::vcd_prims(tVCDDumpType dt, MOD_mkCop &backing)
{
  INST_causeReg.dump_VCD(dt, backing.INST_causeReg);
  INST_copFifo_clearReq_ehrReg.dump_VCD(dt, backing.INST_copFifo_clearReq_ehrReg);
  INST_copFifo_clearReq_ignored_wires_0.dump_VCD(dt, backing.INST_copFifo_clearReq_ignored_wires_0);
  INST_copFifo_clearReq_ignored_wires_1.dump_VCD(dt, backing.INST_copFifo_clearReq_ignored_wires_1);
  INST_copFifo_clearReq_virtual_reg_0.dump_VCD(dt, backing.INST_copFifo_clearReq_virtual_reg_0);
  INST_copFifo_clearReq_virtual_reg_1.dump_VCD(dt, backing.INST_copFifo_clearReq_virtual_reg_1);
  INST_copFifo_clearReq_wires_0.dump_VCD(dt, backing.INST_copFifo_clearReq_wires_0);
  INST_copFifo_clearReq_wires_1.dump_VCD(dt, backing.INST_copFifo_clearReq_wires_1);
  INST_copFifo_data_0.dump_VCD(dt, backing.INST_copFifo_data_0);
  INST_copFifo_data_1.dump_VCD(dt, backing.INST_copFifo_data_1);
  INST_copFifo_deqP.dump_VCD(dt, backing.INST_copFifo_deqP);
  INST_copFifo_deqReq_ehrReg.dump_VCD(dt, backing.INST_copFifo_deqReq_ehrReg);
  INST_copFifo_deqReq_ignored_wires_0.dump_VCD(dt, backing.INST_copFifo_deqReq_ignored_wires_0);
  INST_copFifo_deqReq_ignored_wires_1.dump_VCD(dt, backing.INST_copFifo_deqReq_ignored_wires_1);
  INST_copFifo_deqReq_ignored_wires_2.dump_VCD(dt, backing.INST_copFifo_deqReq_ignored_wires_2);
  INST_copFifo_deqReq_virtual_reg_0.dump_VCD(dt, backing.INST_copFifo_deqReq_virtual_reg_0);
  INST_copFifo_deqReq_virtual_reg_1.dump_VCD(dt, backing.INST_copFifo_deqReq_virtual_reg_1);
  INST_copFifo_deqReq_virtual_reg_2.dump_VCD(dt, backing.INST_copFifo_deqReq_virtual_reg_2);
  INST_copFifo_deqReq_wires_0.dump_VCD(dt, backing.INST_copFifo_deqReq_wires_0);
  INST_copFifo_deqReq_wires_1.dump_VCD(dt, backing.INST_copFifo_deqReq_wires_1);
  INST_copFifo_deqReq_wires_2.dump_VCD(dt, backing.INST_copFifo_deqReq_wires_2);
  INST_copFifo_empty.dump_VCD(dt, backing.INST_copFifo_empty);
  INST_copFifo_enqP.dump_VCD(dt, backing.INST_copFifo_enqP);
  INST_copFifo_enqReq_ehrReg.dump_VCD(dt, backing.INST_copFifo_enqReq_ehrReg);
  INST_copFifo_enqReq_ignored_wires_0.dump_VCD(dt, backing.INST_copFifo_enqReq_ignored_wires_0);
  INST_copFifo_enqReq_ignored_wires_1.dump_VCD(dt, backing.INST_copFifo_enqReq_ignored_wires_1);
  INST_copFifo_enqReq_ignored_wires_2.dump_VCD(dt, backing.INST_copFifo_enqReq_ignored_wires_2);
  INST_copFifo_enqReq_virtual_reg_0.dump_VCD(dt, backing.INST_copFifo_enqReq_virtual_reg_0);
  INST_copFifo_enqReq_virtual_reg_1.dump_VCD(dt, backing.INST_copFifo_enqReq_virtual_reg_1);
  INST_copFifo_enqReq_virtual_reg_2.dump_VCD(dt, backing.INST_copFifo_enqReq_virtual_reg_2);
  INST_copFifo_enqReq_wires_0.dump_VCD(dt, backing.INST_copFifo_enqReq_wires_0);
  INST_copFifo_enqReq_wires_1.dump_VCD(dt, backing.INST_copFifo_enqReq_wires_1);
  INST_copFifo_enqReq_wires_2.dump_VCD(dt, backing.INST_copFifo_enqReq_wires_2);
  INST_copFifo_full.dump_VCD(dt, backing.INST_copFifo_full);
  INST_cycles.dump_VCD(dt, backing.INST_cycles);
  INST_epcReg_ehrReg.dump_VCD(dt, backing.INST_epcReg_ehrReg);
  INST_epcReg_ignored_wires_0.dump_VCD(dt, backing.INST_epcReg_ignored_wires_0);
  INST_epcReg_ignored_wires_1.dump_VCD(dt, backing.INST_epcReg_ignored_wires_1);
  INST_epcReg_virtual_reg_0.dump_VCD(dt, backing.INST_epcReg_virtual_reg_0);
  INST_epcReg_virtual_reg_1.dump_VCD(dt, backing.INST_epcReg_virtual_reg_1);
  INST_epcReg_wires_0.dump_VCD(dt, backing.INST_epcReg_wires_0);
  INST_epcReg_wires_1.dump_VCD(dt, backing.INST_epcReg_wires_1);
  INST_numInsts.dump_VCD(dt, backing.INST_numInsts);
  INST_startReg.dump_VCD(dt, backing.INST_startReg);
  INST_statusReg_ehrReg.dump_VCD(dt, backing.INST_statusReg_ehrReg);
  INST_statusReg_ignored_wires_0.dump_VCD(dt, backing.INST_statusReg_ignored_wires_0);
  INST_statusReg_ignored_wires_1.dump_VCD(dt, backing.INST_statusReg_ignored_wires_1);
  INST_statusReg_virtual_reg_0.dump_VCD(dt, backing.INST_statusReg_virtual_reg_0);
  INST_statusReg_virtual_reg_1.dump_VCD(dt, backing.INST_statusReg_virtual_reg_1);
  INST_statusReg_wires_0.dump_VCD(dt, backing.INST_statusReg_wires_0);
  INST_statusReg_wires_1.dump_VCD(dt, backing.INST_statusReg_wires_1);
}
