/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Tue Nov 25 02:07:28 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "module_decodeRFToMemoryFetch.h"


/* Constructor */
MOD_module_decodeRFToMemoryFetch::MOD_module_decodeRFToMemoryFetch(tSimStateHdl simHdl,
								   char const *name,
								   Module *parent)
  : Module(simHdl, name, parent),
    DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105(73u),
    DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108(129u),
    DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107(119u),
    DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106(83u)
{
  PORT_decodeRFToMemoryFetch_pdInst.setSize(173u);
  PORT_decodeRFToMemoryFetch_pdInst.clear();
  PORT_decodeRFToMemoryFetch.setSize(173u);
  PORT_decodeRFToMemoryFetch.clear();
  PORT_RDY_decodeRFToMemoryFetch = false;
  symbol_count = 4u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_decodeRFToMemoryFetch::init_symbols_0()
{
  init_symbol(&symbols[0u],
	      "CAN_FIRE_decodeRFToMemoryFetch",
	      SYM_DEF,
	      &DEF_CAN_FIRE_decodeRFToMemoryFetch,
	      1u);
  init_symbol(&symbols[1u], "decodeRFToMemoryFetch", SYM_PORT, &PORT_decodeRFToMemoryFetch, 173u);
  init_symbol(&symbols[2u],
	      "decodeRFToMemoryFetch_pdInst",
	      SYM_PORT,
	      &PORT_decodeRFToMemoryFetch_pdInst,
	      173u);
  init_symbol(&symbols[3u],
	      "RDY_decodeRFToMemoryFetch",
	      SYM_PORT,
	      &PORT_RDY_decodeRFToMemoryFetch,
	      1u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_decodeRFToMemoryFetch::METH_decodeRFToMemoryFetch(tUWide ARG_decodeRFToMemoryFetch_pdInst)
{
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_133_CONCAT_IF_ETC___d5;
  tUInt32 DEF_y__h1252;
  tUInt32 DEF_y__h1250;
  tUInt8 DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d51;
  tUInt8 DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d56;
  tUInt8 DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31;
  tUInt8 DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d59;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d26;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d34;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d37;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_154_TO_152_7_ETC___d28;
  tUInt8 DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d47;
  tUInt8 DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d69;
  tUInt8 DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_101_9___d50;
  tUInt8 DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d67;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d45;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d38;
  tUInt32 DEF_x__h1249;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d36;
  tUInt32 DEF_x__h1191;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d35;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d33;
  tUInt32 DEF_x__h1193;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d32;
  tUInt32 DEF__0_CONCAT_decodeRFToMemoryFetch_pdInst_BITS_149_ETC___d76;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d29;
  tUInt32 DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150_1_ETC___d92;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_165_4_ETC___d15;
  tUInt32 DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_77___d101;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_82___d98;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_101___d19;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_123___d9;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_128___d6;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_133___d2;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150___d71;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158___d25;
  tUInt8 DEF_x__h159;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_76_TO_73___d102;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_81_TO_78___d99;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_122_TO_119___d10;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_127_TO_124___d7;
  tUInt8 DEF_decodeRFToMemoryFetch_pdInst_BITS_132_TO_129___d3;
  tUInt8 DEF_x__h1267;
  tUInt8 DEF_x__h1266;
  tUInt8 DEF_x__h108;
  tUInt32 DEF_decodeRFToMemoryFetch_pdInst_BITS_54_TO_39___d79;
  tUInt32 DEF_decodeRFToMemoryFetch_pdInst_BITS_100_TO_83___d78;
  tUInt64 DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_134___d1;
  PORT_decodeRFToMemoryFetch_pdInst = ARG_decodeRFToMemoryFetch_pdInst;
  wop_primExtractWide(73u,
		      173u,
		      ARG_decodeRFToMemoryFetch_pdInst,
		      32u,
		      72u,
		      32u,
		      0u,
		      DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_134___d1 = primExtract64(39u,
									173u,
									ARG_decodeRFToMemoryFetch_pdInst,
									32u,
									172u,
									32u,
									134u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_100_TO_83___d78 = primExtract32(18u,
									173u,
									ARG_decodeRFToMemoryFetch_pdInst,
									32u,
									100u,
									32u,
									83u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_54_TO_39___d79 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word32(1u,
													     7u,
													     16u);
  DEF_x__h1266 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u, 14u, 8u);
  DEF_x__h108 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(5u, 5u, 8u);
  DEF_x__h1267 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u, 6u, 8u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_132_TO_129___d3 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u,
													     1u,
													     4u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_127_TO_124___d7 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(3u,
													     28u,
													     4u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_122_TO_119___d10 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(3u,
													      23u,
													      4u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_81_TO_78___d99 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(2u,
													    14u,
													    4u);
  DEF_x__h159 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u, 24u, 3u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_76_TO_73___d102 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(2u,
													     9u,
													     4u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158___d25 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u,
													      30u,
													      2u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u,
												      26u,
												      1u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150___d71 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u,
													      22u,
													      2u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_133___d2 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u,
												     5u,
												     1u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_128___d6 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(4u,
												     0u,
												     1u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_101___d19 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(3u,
												      5u,
												      1u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_123___d9 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(3u,
												     27u,
												     1u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_82___d98 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(2u,
												     18u,
												     1u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_77___d101 = ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word8(2u,
												      13u,
												      1u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_165_4_ETC___d15 = DEF_x__h108 == (tUInt8)161u;
  DEF_x__h1193 = 65535u & (DEF_decodeRFToMemoryFetch_pdInst_BITS_54_TO_39___d79 + primExtract32(16u,
												173u,
												ARG_decodeRFToMemoryFetch_pdInst,
												32u,
												37u,
												32u,
												22u));
  DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_101_9___d50 = !DEF_decodeRFToMemoryFetch_pdInst_BIT_101___d19;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_154_TO_152_7_ETC___d28 = DEF_x__h159 == (tUInt8)6u;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d37 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158___d25 == (tUInt8)2u;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d34 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158___d25 == (tUInt8)1u;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d36 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d34 && DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d26 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158___d25 == (tUInt8)0u;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d29 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d26 && DEF_decodeRFToMemoryFetch_pdInst_BITS_154_TO_152_7_ETC___d28;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d33 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d26 && DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30;
  DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d59 = !DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d37;
  DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31 = !DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d32 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d26 && DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d35 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d34 && DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d38 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d37 && DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31;
  DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d45 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d29 || (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d32 || (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d33 || (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d35 || (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d36 || (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d38 || (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d37 && DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30))))));
  switch (DEF_x__h108) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d47 = DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d45;
    break;
  default:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d47 = DEF_decodeRFToMemoryFetch_pdInst_BIT_101___d19;
  }
  DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d56 = !DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d34;
  DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d51 = !DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d26;
  DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d67 = (DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d51 || !DEF_decodeRFToMemoryFetch_pdInst_BITS_154_TO_152_7_ETC___d28) && ((DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d51 || DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30) && ((DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d51 || DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31) && ((DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d56 || DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30) && ((DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d56 || DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31) && ((DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d59 || DEF_decodeRFToMemoryFetch_pdInst_BIT_154___d30) && (DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d59 || DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_154_0___d31))))));
  switch (DEF_x__h108) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d69 = DEF_NOT_decodeRFToMemoryFetch_pdInst_BITS_159_TO_1_ETC___d67;
    break;
  default:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d69 = DEF_NOT_decodeRFToMemoryFetch_pdInst_BIT_101_9___d50;
  }
  DEF_y__h1250 = 65535u & ((((tUInt32)(DEF_x__h1267)) << 8u) | (tUInt32)((tUInt8)0u));
  DEF_y__h1252 = 65535u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_x__h1266));
  DEF__0_CONCAT_decodeRFToMemoryFetch_pdInst_BITS_149_ETC___d76 = 65535u & (DEF_y__h1252 + DEF_y__h1250);
  DEF_x__h1191 = 65535u & (DEF_x__h1193 + DEF_y__h1252);
  DEF_x__h1249 = 65535u & (DEF_decodeRFToMemoryFetch_pdInst_BITS_54_TO_39___d79 + DEF_y__h1252);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150_1_ETC___d92 = 262143u & ((((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150___d71)) << 16u) | (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d29 ? DEF__0_CONCAT_decodeRFToMemoryFetch_pdInst_BITS_149_ETC___d76 : (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d32 ? DEF_x__h1193 : (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d33 ? DEF_decodeRFToMemoryFetch_pdInst_BITS_54_TO_39___d79 : (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d35 ? DEF_x__h1191 : (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d36 ? DEF_x__h1249 : (DEF_decodeRFToMemoryFetch_pdInst_BITS_159_TO_158_5_ETC___d38 ? 65535u & (DEF_x__h1191 + DEF_y__h1250) : 65535u & (DEF_x__h1249 + DEF_y__h1250))))))));
  switch (DEF_x__h108) {
  case (tUInt8)161u:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95 = 262143u & ((((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150___d71)) << 16u) | DEF__0_CONCAT_decodeRFToMemoryFetch_pdInst_BITS_149_ETC___d76);
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95 = DEF_decodeRFToMemoryFetch_pdInst_BITS_151_TO_150_1_ETC___d92;
    break;
  default:
    DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95 = DEF_decodeRFToMemoryFetch_pdInst_BITS_100_TO_83___d78;
  }
  DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106.set_bits_in_word(524287u & (((((((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BIT_82___d98)) << 18u) | (((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BIT_82___d98 ? DEF_decodeRFToMemoryFetch_pdInst_BITS_81_TO_78___d99 : DEF_decodeRFToMemoryFetch_pdInst_BITS_81_TO_78___d99)) << 14u)) | (((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BIT_77___d101)) << 13u)) | (((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BIT_77___d101 ? DEF_decodeRFToMemoryFetch_pdInst_BITS_76_TO_73___d102 : DEF_decodeRFToMemoryFetch_pdInst_BITS_76_TO_73___d102)) << 9u)) | DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105.get_bits_in_word32(2u,
																																																																																				 0u,
																																																																																				 9u)),
										 2u,
										 0u,
										 19u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105.get_whole_word(1u),
												     1u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105.get_whole_word(0u),
															0u);
  DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107.set_bits_in_word(8388607u & (((ARG_decodeRFToMemoryFetch_pdInst.get_bits_in_word32(3u,
																		   6u,
																		   17u) << 6u) | (((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_165_4_ETC___d15 || DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d47)) << 5u)) | (tUInt32)((tUInt8)((!DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_165_4_ETC___d15 && DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d69 ? DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95 : DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95) >> 13u))),
										 3u,
										 0u,
										 23u).set_whole_word((((tUInt32)(8191u & (!DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_165_4_ETC___d15 && DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d69 ? DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95 : DEF_IF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_16_ETC___d95))) << 19u) | DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106.get_bits_in_word32(2u,
																																																										    0u,
																																																										    19u),
												     2u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106.get_whole_word(1u),
															1u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106.get_whole_word(0u),
																	   0u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108.build_concat(8589934591llu & (((((((tUInt64)(DEF_decodeRFToMemoryFetch_pdInst_BIT_128___d6)) << 32u) | (((tUInt64)(DEF_decodeRFToMemoryFetch_pdInst_BIT_128___d6 ? DEF_decodeRFToMemoryFetch_pdInst_BITS_127_TO_124___d7 : DEF_decodeRFToMemoryFetch_pdInst_BITS_127_TO_124___d7)) << 28u)) | (((tUInt64)(DEF_decodeRFToMemoryFetch_pdInst_BIT_123___d9)) << 27u)) | (((tUInt64)(DEF_decodeRFToMemoryFetch_pdInst_BIT_123___d9 ? DEF_decodeRFToMemoryFetch_pdInst_BITS_122_TO_119___d10 : DEF_decodeRFToMemoryFetch_pdInst_BITS_122_TO_119___d10)) << 23u)) | (tUInt64)(DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107.get_bits_in_word32(3u,
																																																																																							 0u,
																																																																																							 23u))),
									     96u,
									     33u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107.get_whole_word(2u),
												 2u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107.get_whole_word(1u),
														    1u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107.get_whole_word(0u),
																       0u);
  DEF_decodeRFToMemoryFetch_pdInst_BIT_133_CONCAT_IF_ETC___d5 = (tUInt8)31u & ((DEF_decodeRFToMemoryFetch_pdInst_BIT_133___d2 << 4u) | (DEF_decodeRFToMemoryFetch_pdInst_BIT_133___d2 ? DEF_decodeRFToMemoryFetch_pdInst_BITS_132_TO_129___d3 : DEF_decodeRFToMemoryFetch_pdInst_BITS_132_TO_129___d3));
  PORT_decodeRFToMemoryFetch.set_bits_in_word((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_134___d1 >> 26u),
					      5u,
					      0u,
					      13u).set_whole_word(((((tUInt32)(67108863u & DEF_decodeRFToMemoryFetch_pdInst_BITS_172_TO_134___d1)) << 6u) | (((tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BIT_133_CONCAT_IF_ETC___d5)) << 1u)) | (tUInt32)(DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108.get_bits_in_word8(4u,
																																									  0u,
																																									  1u)),
								  4u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108.get_whole_word(3u),
										     3u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108.get_whole_word(2u),
													2u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108.get_whole_word(1u),
															   1u).set_whole_word(DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108.get_whole_word(0u),
																	      0u);
  return PORT_decodeRFToMemoryFetch;
}

tUInt8 MOD_module_decodeRFToMemoryFetch::METH_RDY_decodeRFToMemoryFetch()
{
  DEF_CAN_FIRE_decodeRFToMemoryFetch = (tUInt8)1u;
  PORT_RDY_decodeRFToMemoryFetch = DEF_CAN_FIRE_decodeRFToMemoryFetch;
  return PORT_RDY_decodeRFToMemoryFetch;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_decodeRFToMemoryFetch::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_decodeRFToMemoryFetch::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 8u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_decodeRFToMemoryFetch", 1u);
  vcd_write_def(sim_hdl, num++, "decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107", 119u);
  vcd_write_def(sim_hdl, num++, "decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105", 73u);
  vcd_write_def(sim_hdl, num++, "decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108", 129u);
  vcd_write_def(sim_hdl, num++, "decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106", 83u);
  vcd_write_def(sim_hdl, num++, "RDY_decodeRFToMemoryFetch", 1u);
  vcd_write_def(sim_hdl, num++, "decodeRFToMemoryFetch", 173u);
  vcd_write_def(sim_hdl, num++, "decodeRFToMemoryFetch_pdInst", 173u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_decodeRFToMemoryFetch::dump_VCD(tVCDDumpType dt,
						unsigned int levels,
						MOD_module_decodeRFToMemoryFetch &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_decodeRFToMemoryFetch::vcd_defs(tVCDDumpType dt,
						MOD_module_decodeRFToMemoryFetch &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 119u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 83u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 173u);
    vcd_write_x(sim_hdl, num++, 173u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_decodeRFToMemoryFetch) != DEF_CAN_FIRE_decodeRFToMemoryFetch)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_decodeRFToMemoryFetch, 1u);
	backing.DEF_CAN_FIRE_decodeRFToMemoryFetch = DEF_CAN_FIRE_decodeRFToMemoryFetch;
      }
      ++num;
      if ((backing.DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107) != DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107, 119u);
	backing.DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107 = DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107;
      }
      ++num;
      if ((backing.DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105) != DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105, 73u);
	backing.DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105 = DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105;
      }
      ++num;
      if ((backing.DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108) != DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108, 129u);
	backing.DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108 = DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108;
      }
      ++num;
      if ((backing.DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106) != DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106, 83u);
	backing.DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106 = DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106;
      }
      ++num;
      if ((backing.PORT_RDY_decodeRFToMemoryFetch) != PORT_RDY_decodeRFToMemoryFetch)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_decodeRFToMemoryFetch, 1u);
	backing.PORT_RDY_decodeRFToMemoryFetch = PORT_RDY_decodeRFToMemoryFetch;
      }
      ++num;
      if ((backing.PORT_decodeRFToMemoryFetch) != PORT_decodeRFToMemoryFetch)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeRFToMemoryFetch, 173u);
	backing.PORT_decodeRFToMemoryFetch = PORT_decodeRFToMemoryFetch;
      }
      ++num;
      if ((backing.PORT_decodeRFToMemoryFetch_pdInst) != PORT_decodeRFToMemoryFetch_pdInst)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeRFToMemoryFetch_pdInst, 173u);
	backing.PORT_decodeRFToMemoryFetch_pdInst = PORT_decodeRFToMemoryFetch_pdInst;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_decodeRFToMemoryFetch, 1u);
      backing.DEF_CAN_FIRE_decodeRFToMemoryFetch = DEF_CAN_FIRE_decodeRFToMemoryFetch;
      vcd_write_val(sim_hdl, num++, DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107, 119u);
      backing.DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107 = DEF_decodeRFToMemoryFetch_pdInst_BITS_118_TO_102_3_ETC___d107;
      vcd_write_val(sim_hdl, num++, DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105, 73u);
      backing.DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105 = DEF_decodeRFToMemoryFetch_pdInst_BITS_72_TO_0___d105;
      vcd_write_val(sim_hdl, num++, DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108, 129u);
      backing.DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108 = DEF_decodeRFToMemoryFetch_pdInst_BIT_128_CONCAT_IF_ETC___d108;
      vcd_write_val(sim_hdl, num++, DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106, 83u);
      backing.DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106 = DEF_decodeRFToMemoryFetch_pdInst_BIT_82_8_CONCAT_I_ETC___d106;
      vcd_write_val(sim_hdl, num++, PORT_RDY_decodeRFToMemoryFetch, 1u);
      backing.PORT_RDY_decodeRFToMemoryFetch = PORT_RDY_decodeRFToMemoryFetch;
      vcd_write_val(sim_hdl, num++, PORT_decodeRFToMemoryFetch, 173u);
      backing.PORT_decodeRFToMemoryFetch = PORT_decodeRFToMemoryFetch;
      vcd_write_val(sim_hdl, num++, PORT_decodeRFToMemoryFetch_pdInst, 173u);
      backing.PORT_decodeRFToMemoryFetch_pdInst = PORT_decodeRFToMemoryFetch_pdInst;
    }
}
