/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Tue Nov 25 02:07:28 EST 2014
 * 
 */

/* Generation options: keep-fires */
#ifndef __module_decodeHighData_h__
#define __module_decodeHighData_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the module_decodeHighData module */
class MOD_module_decodeHighData : public Module {
 
 /* Clock handles */
 private:
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_module_decodeHighData(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
 
 /* Port definitions */
 public:
  tUWide PORT_decodeHighData_pdInst;
  tUInt8 PORT_decodeHighData_highData;
  tUWide PORT_decodeHighData;
  tUInt8 PORT_RDY_decodeHighData;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_CAN_FIRE_decodeHighData;
 
 /* Local definitions */
 private:
  tUWide DEF_decodeHighData_pdInst_BITS_72_TO_0___d26;
  tUWide DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29;
  tUWide DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28;
  tUWide DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUWide METH_decodeHighData(tUWide ARG_decodeHighData_pdInst, tUInt8 ARG_decodeHighData_highData);
  tUInt8 METH_RDY_decodeHighData();
 
 /* Reset routines */
 public:
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_module_decodeHighData &backing);
  void vcd_defs(tVCDDumpType dt, MOD_module_decodeHighData &backing);
};

#endif /* ifndef __module_decodeHighData_h__ */
