/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Wed Nov 26 13:26:23 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "module_decodeHighData.h"


/* Constructor */
MOD_module_decodeHighData::MOD_module_decodeHighData(tSimStateHdl simHdl,
						     char const *name,
						     Module *parent)
  : Module(simHdl, name, parent),
    DEF_decodeHighData_pdInst_BITS_105_TO_0___d36(106u),
    DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41(215u),
    DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40(205u),
    DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39(169u),
    DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38(147u),
    DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37(123u)
{
  PORT_decodeHighData_pdInst.setSize(260u);
  PORT_decodeHighData_pdInst.clear();
  PORT_decodeHighData_highData = 0u;
  PORT_decodeHighData.setSize(260u);
  PORT_decodeHighData.clear();
  PORT_RDY_decodeHighData = false;
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_decodeHighData::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_decodeHighData", SYM_DEF, &DEF_CAN_FIRE_decodeHighData, 1u);
  init_symbol(&symbols[1u], "decodeHighData", SYM_PORT, &PORT_decodeHighData, 260u);
  init_symbol(&symbols[2u], "decodeHighData_highData", SYM_PORT, &PORT_decodeHighData_highData, 8u);
  init_symbol(&symbols[3u], "decodeHighData_pdInst", SYM_PORT, &PORT_decodeHighData_pdInst, 260u);
  init_symbol(&symbols[4u], "RDY_decodeHighData", SYM_PORT, &PORT_RDY_decodeHighData, 1u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_decodeHighData::METH_decodeHighData(tUWide ARG_decodeHighData_pdInst,
						      tUInt8 ARG_decodeHighData_highData)
{
  tUInt8 DEF_decodeHighData_pdInst_BIT_219_CONCAT_IF_decode_ETC___d5;
  tUInt8 DEF_decodeHighData_pdInst_BIT_122___d33;
  tUInt8 DEF_decodeHighData_pdInst_BIT_141___d29;
  tUInt8 DEF_decodeHighData_pdInst_BIT_146___d26;
  tUInt8 DEF_decodeHighData_pdInst_BIT_151___d22;
  tUInt8 DEF_decodeHighData_pdInst_BIT_168___d19;
  tUInt8 DEF_decodeHighData_pdInst_BIT_187___d15;
  tUInt8 DEF_decodeHighData_pdInst_BIT_209___d9;
  tUInt8 DEF_decodeHighData_pdInst_BIT_214___d6;
  tUInt8 DEF_decodeHighData_pdInst_BIT_219___d2;
  tUInt8 DEF_decodeHighData_pdInst_BITS_145_TO_142___d27;
  tUInt8 DEF_decodeHighData_pdInst_BITS_150_TO_147___d23;
  tUInt8 DEF_decodeHighData_pdInst_BITS_208_TO_205___d10;
  tUInt8 DEF_decodeHighData_pdInst_BITS_213_TO_210___d7;
  tUInt8 DEF_decodeHighData_pdInst_BITS_218_TO_215___d3;
  tUInt32 DEF_decodeHighData_pdInst_BITS_121_TO_106___d34;
  tUInt32 DEF_decodeHighData_pdInst_BITS_167_TO_152___d20;
  tUInt32 DEF_decodeHighData_pdInst_BITS_140_TO_123___d30;
  tUInt32 DEF_decodeHighData_pdInst_BITS_186_TO_169___d16;
  tUInt64 DEF_decodeHighData_pdInst_BITS_259_TO_220___d1;
  PORT_decodeHighData_pdInst = ARG_decodeHighData_pdInst;
  PORT_decodeHighData_highData = ARG_decodeHighData_highData;
  wop_primExtractWide(106u,
		      260u,
		      ARG_decodeHighData_pdInst,
		      32u,
		      105u,
		      32u,
		      0u,
		      DEF_decodeHighData_pdInst_BITS_105_TO_0___d36);
  DEF_decodeHighData_pdInst_BITS_259_TO_220___d1 = primExtract64(40u,
								 260u,
								 ARG_decodeHighData_pdInst,
								 32u,
								 259u,
								 32u,
								 220u);
  DEF_decodeHighData_pdInst_BITS_186_TO_169___d16 = ARG_decodeHighData_pdInst.get_bits_in_word32(5u,
												 9u,
												 18u);
  DEF_decodeHighData_pdInst_BITS_140_TO_123___d30 = primExtract32(18u,
								  260u,
								  ARG_decodeHighData_pdInst,
								  32u,
								  140u,
								  32u,
								  123u);
  DEF_decodeHighData_pdInst_BITS_121_TO_106___d34 = ARG_decodeHighData_pdInst.get_bits_in_word32(3u,
												 10u,
												 16u);
  DEF_decodeHighData_pdInst_BITS_167_TO_152___d20 = primExtract32(16u,
								  260u,
								  ARG_decodeHighData_pdInst,
								  32u,
								  167u,
								  32u,
								  152u);
  DEF_decodeHighData_pdInst_BITS_218_TO_215___d3 = ARG_decodeHighData_pdInst.get_bits_in_word8(6u,
											       23u,
											       4u);
  DEF_decodeHighData_pdInst_BITS_213_TO_210___d7 = ARG_decodeHighData_pdInst.get_bits_in_word8(6u,
											       18u,
											       4u);
  DEF_decodeHighData_pdInst_BITS_208_TO_205___d10 = ARG_decodeHighData_pdInst.get_bits_in_word8(6u,
												13u,
												4u);
  DEF_decodeHighData_pdInst_BITS_150_TO_147___d23 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u,
												19u,
												4u);
  DEF_decodeHighData_pdInst_BITS_145_TO_142___d27 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u,
												14u,
												4u);
  DEF_decodeHighData_pdInst_BIT_214___d6 = ARG_decodeHighData_pdInst.get_bits_in_word8(6u, 22u, 1u);
  DEF_decodeHighData_pdInst_BIT_219___d2 = ARG_decodeHighData_pdInst.get_bits_in_word8(6u, 27u, 1u);
  DEF_decodeHighData_pdInst_BIT_209___d9 = ARG_decodeHighData_pdInst.get_bits_in_word8(6u, 17u, 1u);
  DEF_decodeHighData_pdInst_BIT_168___d19 = ARG_decodeHighData_pdInst.get_bits_in_word8(5u, 8u, 1u);
  DEF_decodeHighData_pdInst_BIT_187___d15 = ARG_decodeHighData_pdInst.get_bits_in_word8(5u, 27u, 1u);
  DEF_decodeHighData_pdInst_BIT_151___d22 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u, 23u, 1u);
  DEF_decodeHighData_pdInst_BIT_146___d26 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u, 18u, 1u);
  DEF_decodeHighData_pdInst_BIT_122___d33 = ARG_decodeHighData_pdInst.get_bits_in_word8(3u, 26u, 1u);
  DEF_decodeHighData_pdInst_BIT_141___d29 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u, 13u, 1u);
  DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37.set_bits_in_word(134217727u & (((((tUInt32)(DEF_decodeHighData_pdInst_BIT_122___d33)) << 26u) | ((DEF_decodeHighData_pdInst_BIT_122___d33 ? DEF_decodeHighData_pdInst_BITS_121_TO_106___d34 : DEF_decodeHighData_pdInst_BITS_121_TO_106___d34) << 10u)) | DEF_decodeHighData_pdInst_BITS_105_TO_0___d36.get_bits_in_word32(3u,
																																															  0u,
																																															  10u)),
										3u,
										0u,
										27u).set_whole_word(DEF_decodeHighData_pdInst_BITS_105_TO_0___d36.get_whole_word(2u),
												    2u).set_whole_word(DEF_decodeHighData_pdInst_BITS_105_TO_0___d36.get_whole_word(1u),
														       1u).set_whole_word(DEF_decodeHighData_pdInst_BITS_105_TO_0___d36.get_whole_word(0u),
																	  0u);
  DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38.set_bits_in_word(524287u & ((((((tUInt32)(DEF_decodeHighData_pdInst_BIT_146___d26)) << 18u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_146___d26 ? DEF_decodeHighData_pdInst_BITS_145_TO_142___d27 : DEF_decodeHighData_pdInst_BITS_145_TO_142___d27)) << 14u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_141___d29)) << 13u)) | (tUInt32)((DEF_decodeHighData_pdInst_BIT_141___d29 ? DEF_decodeHighData_pdInst_BITS_140_TO_123___d30 : DEF_decodeHighData_pdInst_BITS_140_TO_123___d30) >> 5u)),
										4u,
										0u,
										19u).set_whole_word((((tUInt32)((tUInt8)((tUInt8)31u & (DEF_decodeHighData_pdInst_BIT_141___d29 ? DEF_decodeHighData_pdInst_BITS_140_TO_123___d30 : DEF_decodeHighData_pdInst_BITS_140_TO_123___d30)))) << 27u) | DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37.get_bits_in_word32(3u,
																																														  0u,
																																														  27u),
												    3u).set_whole_word(DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37.get_whole_word(2u),
														       2u).set_whole_word(DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37.get_whole_word(1u),
																	  1u).set_whole_word(DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37.get_whole_word(0u),
																			     0u);
  DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.set_bits_in_word(511u & ((((tUInt32)(DEF_decodeHighData_pdInst_BIT_168___d19)) << 8u) | (tUInt32)((tUInt8)((DEF_decodeHighData_pdInst_BIT_168___d19 ? DEF_decodeHighData_pdInst_BITS_167_TO_152___d20 : DEF_decodeHighData_pdInst_BITS_167_TO_152___d20) >> 8u))),
										5u,
										0u,
										9u).set_whole_word((((((tUInt32)((tUInt8)((tUInt8)255u & (DEF_decodeHighData_pdInst_BIT_168___d19 ? DEF_decodeHighData_pdInst_BITS_167_TO_152___d20 : DEF_decodeHighData_pdInst_BITS_167_TO_152___d20)))) << 24u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_151___d22)) << 23u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_151___d22 ? DEF_decodeHighData_pdInst_BITS_150_TO_147___d23 : DEF_decodeHighData_pdInst_BITS_150_TO_147___d23)) << 19u)) | DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38.get_bits_in_word32(4u,
																																																																											  0u,
																																																																											  19u),
												   4u).set_whole_word(DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38.get_whole_word(3u),
														      3u).set_whole_word(DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38.get_whole_word(2u),
																	 2u).set_whole_word(DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38.get_whole_word(1u),
																			    1u).set_whole_word(DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38.get_whole_word(0u),
																					       0u);
  DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.set_bits_in_word(8191u & (((((tUInt32)((tUInt8)1u)) << 12u) | (((tUInt32)(ARG_decodeHighData_highData)) << 4u)) | (tUInt32)(ARG_decodeHighData_pdInst.get_bits_in_word8(6u,
																													0u,
																													4u))),
										 6u,
										 0u,
										 13u).set_whole_word((((((tUInt32)(ARG_decodeHighData_pdInst.get_bits_in_word8(5u,
																			       28u,
																			       4u))) << 28u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_187___d15)) << 27u)) | ((DEF_decodeHighData_pdInst_BIT_187___d15 ? DEF_decodeHighData_pdInst_BITS_186_TO_169___d16 : DEF_decodeHighData_pdInst_BITS_186_TO_169___d16) << 9u)) | DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.get_bits_in_word32(5u,
																																																											 0u,
																																																											 9u),
												     5u).set_whole_word(DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.get_whole_word(4u),
															4u).set_whole_word(DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.get_whole_word(3u),
																	   3u).set_whole_word(DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.get_whole_word(2u),
																			      2u).set_whole_word(DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.get_whole_word(1u),
																						 1u).set_whole_word(DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39.get_whole_word(0u),
																								    0u);
  DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.set_bits_in_word(8388607u & (((((((tUInt32)(DEF_decodeHighData_pdInst_BIT_214___d6)) << 22u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_214___d6 ? DEF_decodeHighData_pdInst_BITS_213_TO_210___d7 : DEF_decodeHighData_pdInst_BITS_213_TO_210___d7)) << 18u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_209___d9)) << 17u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_209___d9 ? DEF_decodeHighData_pdInst_BITS_208_TO_205___d10 : DEF_decodeHighData_pdInst_BITS_208_TO_205___d10)) << 13u)) | DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_bits_in_word32(6u,
																																																																														     0u,
																																																																														     13u)),
										6u,
										0u,
										23u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_whole_word(5u),
												    5u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_whole_word(4u),
														       4u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_whole_word(3u),
																	  3u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_whole_word(2u),
																			     2u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_whole_word(1u),
																						1u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40.get_whole_word(0u),
																								   0u);
  DEF_decodeHighData_pdInst_BIT_219_CONCAT_IF_decode_ETC___d5 = (tUInt8)31u & ((DEF_decodeHighData_pdInst_BIT_219___d2 << 4u) | (DEF_decodeHighData_pdInst_BIT_219___d2 ? DEF_decodeHighData_pdInst_BITS_218_TO_215___d3 : DEF_decodeHighData_pdInst_BITS_218_TO_215___d3));
  PORT_decodeHighData.set_bits_in_word((tUInt8)(DEF_decodeHighData_pdInst_BITS_259_TO_220___d1 >> 36u),
				       8u,
				       0u,
				       4u).set_whole_word((tUInt32)(DEF_decodeHighData_pdInst_BITS_259_TO_220___d1 >> 4u),
							  7u).set_whole_word(((((tUInt32)((tUInt8)((tUInt8)15u & DEF_decodeHighData_pdInst_BITS_259_TO_220___d1))) << 28u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_219_CONCAT_IF_decode_ETC___d5)) << 23u)) | DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_bits_in_word32(6u,
																																										  0u,
																																										  23u),
									     6u).set_whole_word(DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_whole_word(5u),
												5u).set_whole_word(DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_whole_word(4u),
														   4u).set_whole_word(DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_whole_word(3u),
																      3u).set_whole_word(DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_whole_word(2u),
																			 2u).set_whole_word(DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_whole_word(1u),
																					    1u).set_whole_word(DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41.get_whole_word(0u),
																							       0u);
  return PORT_decodeHighData;
}

tUInt8 MOD_module_decodeHighData::METH_RDY_decodeHighData()
{
  DEF_CAN_FIRE_decodeHighData = (tUInt8)1u;
  PORT_RDY_decodeHighData = DEF_CAN_FIRE_decodeHighData;
  return PORT_RDY_decodeHighData;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_decodeHighData::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_decodeHighData::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 11u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_decodeHighData", 1u);
  vcd_write_def(sim_hdl, num++, "_1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40", 205u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BITS_105_TO_0___d36", 106u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37", 123u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38", 147u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39", 169u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41", 215u);
  vcd_write_def(sim_hdl, num++, "RDY_decodeHighData", 1u);
  vcd_write_def(sim_hdl, num++, "decodeHighData", 260u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_highData", 8u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst", 260u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_decodeHighData::dump_VCD(tVCDDumpType dt,
					 unsigned int levels,
					 MOD_module_decodeHighData &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_decodeHighData::vcd_defs(tVCDDumpType dt, MOD_module_decodeHighData &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 205u);
    vcd_write_x(sim_hdl, num++, 106u);
    vcd_write_x(sim_hdl, num++, 123u);
    vcd_write_x(sim_hdl, num++, 147u);
    vcd_write_x(sim_hdl, num++, 169u);
    vcd_write_x(sim_hdl, num++, 215u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 260u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 260u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_decodeHighData) != DEF_CAN_FIRE_decodeHighData)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_decodeHighData, 1u);
	backing.DEF_CAN_FIRE_decodeHighData = DEF_CAN_FIRE_decodeHighData;
      }
      ++num;
      if ((backing.DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40) != DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40)
      {
	vcd_write_val(sim_hdl, num, DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40, 205u);
	backing.DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40 = DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BITS_105_TO_0___d36) != DEF_decodeHighData_pdInst_BITS_105_TO_0___d36)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BITS_105_TO_0___d36, 106u);
	backing.DEF_decodeHighData_pdInst_BITS_105_TO_0___d36 = DEF_decodeHighData_pdInst_BITS_105_TO_0___d36;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37) != DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37, 123u);
	backing.DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37 = DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38) != DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38, 147u);
	backing.DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38 = DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39) != DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39, 169u);
	backing.DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39 = DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41) != DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41, 215u);
	backing.DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41 = DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41;
      }
      ++num;
      if ((backing.PORT_RDY_decodeHighData) != PORT_RDY_decodeHighData)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_decodeHighData, 1u);
	backing.PORT_RDY_decodeHighData = PORT_RDY_decodeHighData;
      }
      ++num;
      if ((backing.PORT_decodeHighData) != PORT_decodeHighData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeHighData, 260u);
	backing.PORT_decodeHighData = PORT_decodeHighData;
      }
      ++num;
      if ((backing.PORT_decodeHighData_highData) != PORT_decodeHighData_highData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeHighData_highData, 8u);
	backing.PORT_decodeHighData_highData = PORT_decodeHighData_highData;
      }
      ++num;
      if ((backing.PORT_decodeHighData_pdInst) != PORT_decodeHighData_pdInst)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeHighData_pdInst, 260u);
	backing.PORT_decodeHighData_pdInst = PORT_decodeHighData_pdInst;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_decodeHighData, 1u);
      backing.DEF_CAN_FIRE_decodeHighData = DEF_CAN_FIRE_decodeHighData;
      vcd_write_val(sim_hdl, num++, DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40, 205u);
      backing.DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40 = DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d40;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BITS_105_TO_0___d36, 106u);
      backing.DEF_decodeHighData_pdInst_BITS_105_TO_0___d36 = DEF_decodeHighData_pdInst_BITS_105_TO_0___d36;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37, 123u);
      backing.DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37 = DEF_decodeHighData_pdInst_BIT_122_3_CONCAT_IF_deco_ETC___d37;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38, 147u);
      backing.DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38 = DEF_decodeHighData_pdInst_BIT_146_6_CONCAT_IF_deco_ETC___d38;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39, 169u);
      backing.DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39 = DEF_decodeHighData_pdInst_BIT_168_9_CONCAT_IF_deco_ETC___d39;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41, 215u);
      backing.DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41 = DEF_decodeHighData_pdInst_BIT_214_CONCAT_IF_decode_ETC___d41;
      vcd_write_val(sim_hdl, num++, PORT_RDY_decodeHighData, 1u);
      backing.PORT_RDY_decodeHighData = PORT_RDY_decodeHighData;
      vcd_write_val(sim_hdl, num++, PORT_decodeHighData, 260u);
      backing.PORT_decodeHighData = PORT_decodeHighData;
      vcd_write_val(sim_hdl, num++, PORT_decodeHighData_highData, 8u);
      backing.PORT_decodeHighData_highData = PORT_decodeHighData_highData;
      vcd_write_val(sim_hdl, num++, PORT_decodeHighData_pdInst, 260u);
      backing.PORT_decodeHighData_pdInst = PORT_decodeHighData_pdInst;
    }
}
