/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Tue Nov 25 02:07:28 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "module_decodeAddressingMode.h"


/* Constructor */
MOD_module_decodeAddressingMode::MOD_module_decodeAddressingMode(tSimStateHdl simHdl,
								 char const *name,
								 Module *parent)
  : Module(simHdl, name, parent),
    DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173(69u),
    DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185(152u),
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184(129u),
    DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183(119u),
    DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182(83u),
    DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181(73u)
{
  PORT_decodeAddressingMode_pdInst.setSize(173u);
  PORT_decodeAddressingMode_pdInst.clear();
  PORT_decodeAddressingMode_addressMode = 0u;
  PORT_decodeAddressingMode.setSize(173u);
  PORT_decodeAddressingMode.clear();
  PORT_RDY_decodeAddressingMode = false;
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_decodeAddressingMode::init_symbols_0()
{
  init_symbol(&symbols[0u],
	      "CAN_FIRE_decodeAddressingMode",
	      SYM_DEF,
	      &DEF_CAN_FIRE_decodeAddressingMode,
	      1u);
  init_symbol(&symbols[1u], "decodeAddressingMode", SYM_PORT, &PORT_decodeAddressingMode, 173u);
  init_symbol(&symbols[2u],
	      "decodeAddressingMode_addressMode",
	      SYM_PORT,
	      &PORT_decodeAddressingMode_addressMode,
	      8u);
  init_symbol(&symbols[3u],
	      "decodeAddressingMode_pdInst",
	      SYM_PORT,
	      &PORT_decodeAddressingMode_pdInst,
	      173u);
  init_symbol(&symbols[4u], "RDY_decodeAddressingMode", SYM_PORT, &PORT_RDY_decodeAddressingMode, 1u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_decodeAddressingMode::METH_decodeAddressingMode(tUWide ARG_decodeAddressingMode_pdInst,
								  tUInt8 ARG_decodeAddressingMode_addressMode)
{
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d15;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d11;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d53;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d160;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d156;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d51;
  tUInt8 DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_127_4_7___d68;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d31;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d176;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d78;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d79;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d83;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d84;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d34;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d4;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d5;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d37;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d38;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d58;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d46;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d49;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d72;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d131;
  tUInt8 DEF__0_OR_decodeAddressingMode_pdInst_BIT_128_2___d43;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d44;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d47;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d55;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d56;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BIT_128_2___d54;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d60;
  tUInt8 DEF__0_OR_0_OR_NOT_decodeAddressingMode_pdInst_BIT__ETC___d69;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d70;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BIT_127_4___d67;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d73;
  tUInt8 DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_122_2_ETC___d129;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d130;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BIT_122_25___d128;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d132;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d65;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d66;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d112;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d113;
  tUInt8 DEF_NOT_decodeAddressingMode_pdInst_BIT_123_11___d122;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d123;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d126;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d127;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d6;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d24;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d25;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d22;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d39;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d94;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d99;
  tUInt8 DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d95;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52;
  tUInt8 DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d77;
  tUInt8 DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d98;
  tUInt8 DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d91;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d76;
  tUInt8 DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d101;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d102;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d75;
  tUInt8 DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d103;
  tUInt8 DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d138;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d139;
  tUInt8 DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110;
  tUInt8 DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d140;
  tUInt8 DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d135;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d121;
  tUInt8 DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d136;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d141;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d134;
  tUInt8 DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d142;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d164;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d165;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d62;
  tUInt8 DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d124;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_77___d169;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_81___d159;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_82___d152;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_101___d148;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_122___d125;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_123___d111;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_127___d64;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_128___d42;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_132___d14;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_133___d7;
  tUInt8 DEF_decodeAddressingMode_pdInst_BIT_165___d18;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_7_TO_6___d30;
  tUInt8 DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_80_TO_78___d163;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_121_TO_119___d137;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_126_TO_124___d96;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_131_TO_129___d23;
  tUInt8 DEF_decodeAddressingMode_pdInst_BITS_76_TO_73___d170;
  tUInt8 DEF_x__h658;
  tUInt32 DEF_decodeAddressingMode_pdInst_BITS_172_TO_160___d1;
  tUInt32 DEF_decodeAddressingMode_pdInst_BITS_100_TO_83___d149;
  PORT_decodeAddressingMode_pdInst = ARG_decodeAddressingMode_pdInst;
  PORT_decodeAddressingMode_addressMode = ARG_decodeAddressingMode_addressMode;
  wop_primExtractWide(69u,
		      173u,
		      ARG_decodeAddressingMode_pdInst,
		      32u,
		      72u,
		      32u,
		      4u,
		      DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173);
  DEF_decodeAddressingMode_pdInst_BITS_100_TO_83___d149 = primExtract32(18u,
									173u,
									ARG_decodeAddressingMode_pdInst,
									32u,
									100u,
									32u,
									83u);
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_160___d1 = ARG_decodeAddressingMode_pdInst.get_bits_in_word32(5u,
													    0u,
													    13u);
  DEF_x__h658 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(5u, 5u, 8u);
  DEF_decodeAddressingMode_pdInst_BITS_131_TO_129___d23 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(4u,
													    1u,
													    3u);
  DEF_decodeAddressingMode_pdInst_BITS_76_TO_73___d170 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(2u,
													   9u,
													   4u);
  DEF_decodeAddressingMode_pdInst_BITS_126_TO_124___d96 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(3u,
													    28u,
													    3u);
  DEF_decodeAddressingMode_pdInst_BITS_121_TO_119___d137 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(3u,
													     23u,
													     3u);
  DEF_decodeAddressingMode_pdInst_BITS_80_TO_78___d163 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(2u,
													   14u,
													   3u);
  DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 = (tUInt8)((tUInt8)7u & ARG_decodeAddressingMode_addressMode);
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6___d30 = (tUInt8)(ARG_decodeAddressingMode_addressMode >> 6u);
  DEF_decodeAddressingMode_pdInst_BIT_133___d7 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(4u,
												   5u,
												   1u);
  DEF_decodeAddressingMode_pdInst_BIT_165___d18 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(5u,
												    5u,
												    1u);
  DEF_decodeAddressingMode_pdInst_BIT_132___d14 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(4u,
												    4u,
												    1u);
  DEF_decodeAddressingMode_pdInst_BIT_127___d64 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(3u,
												    31u,
												    1u);
  DEF_decodeAddressingMode_pdInst_BIT_128___d42 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(4u,
												    0u,
												    1u);
  DEF_decodeAddressingMode_pdInst_BIT_123___d111 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(3u,
												     27u,
												     1u);
  DEF_decodeAddressingMode_pdInst_BIT_122___d125 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(3u,
												     26u,
												     1u);
  DEF_decodeAddressingMode_pdInst_BIT_82___d152 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(2u,
												    18u,
												    1u);
  DEF_decodeAddressingMode_pdInst_BIT_101___d148 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(3u,
												     5u,
												     1u);
  DEF_decodeAddressingMode_pdInst_BIT_81___d159 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(2u,
												    17u,
												    1u);
  DEF_decodeAddressingMode_pdInst_BIT_77___d169 = ARG_decodeAddressingMode_pdInst.get_bits_in_word8(2u,
												    13u,
												    1u);
  switch (DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33) {
  case (tUInt8)0u:
  case (tUInt8)2u:
    DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d135 = (tUInt8)6u;
    break;
  default:
    DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d135 = (tUInt8)7u;
  }
  switch (DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33) {
  case (tUInt8)0u:
  case (tUInt8)1u:
  case (tUInt8)7u:
    DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90 = (tUInt8)3u;
    break;
  case (tUInt8)2u:
  case (tUInt8)3u:
  case (tUInt8)6u:
    DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90 = (tUInt8)5u;
    break;
  case (tUInt8)4u:
    DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90 = (tUInt8)6u;
    break;
  default:
    DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90 = (tUInt8)7u;
  }
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6___d30 == (tUInt8)3u;
  DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d94 = DEF_decodeAddressingMode_pdInst_BIT_165___d18 ? DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 : (tUInt8)7u & ((tUInt8)((tUInt8)3u & ARG_decodeAddressingMode_addressMode));
  DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d95 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52 ? DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d94 : DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d94;
  DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d22 = DEF_decodeAddressingMode_pdInst_BIT_165___d18 ? (tUInt8)((tUInt8)7u & (ARG_decodeAddressingMode_addressMode >> 3u)) : (tUInt8)7u & ((tUInt8)((tUInt8)3u & (ARG_decodeAddressingMode_addressMode >> 3u)));
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d164 = DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d22;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d164 = DEF_decodeAddressingMode_pdInst_BITS_80_TO_78___d163;
  }
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d24 = DEF_IF_decodeAddressingMode_pdInst_BIT_165_8_THEN__ETC___d22;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d24 = DEF_decodeAddressingMode_pdInst_BITS_131_TO_129___d23;
  }
  DEF_NOT_decodeAddressingMode_pdInst_BIT_123_11___d122 = !DEF_decodeAddressingMode_pdInst_BIT_123___d111;
  DEF_NOT_decodeAddressingMode_pdInst_BIT_122_25___d128 = !DEF_decodeAddressingMode_pdInst_BIT_122___d125;
  DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_122_2_ETC___d129 = DEF_NOT_decodeAddressingMode_pdInst_BIT_122_25___d128;
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d130 = DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_122_2_ETC___d129;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d130 = DEF_NOT_decodeAddressingMode_pdInst_BIT_122_25___d128;
  }
  DEF_NOT_decodeAddressingMode_pdInst_BIT_127_4___d67 = !DEF_decodeAddressingMode_pdInst_BIT_127___d64;
  DEF_NOT_decodeAddressingMode_pdInst_BIT_128_2___d54 = !DEF_decodeAddressingMode_pdInst_BIT_128___d42;
  DEF__0_OR_decodeAddressingMode_pdInst_BIT_128_2___d43 = DEF_decodeAddressingMode_pdInst_BIT_128___d42;
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d44 = DEF__0_OR_decodeAddressingMode_pdInst_BIT_128_2___d43;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d44 = DEF_decodeAddressingMode_pdInst_BIT_128___d42;
  }
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d38 = DEF_x__h658 == (tUInt8)139u;
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d37 = DEF_x__h658 == (tUInt8)138u;
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d39 = DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d37 || DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d38;
  DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d165 = DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d39 || !DEF_decodeAddressingMode_pdInst_BIT_81___d159 ? DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d164 : DEF_decodeAddressingMode_pdInst_BITS_80_TO_78___d163;
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d5 = DEF_x__h658 == (tUInt8)137u;
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d4 = DEF_x__h658 == (tUInt8)136u;
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d6 = DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d4 || DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d5;
  DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d25 = DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d6 || !DEF_decodeAddressingMode_pdInst_BIT_132___d14 ? DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d24 : DEF_decodeAddressingMode_pdInst_BITS_131_TO_129___d23;
  DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d34 = DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 == (tUInt8)6u;
  DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d84 = DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 == (tUInt8)3u;
  DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d83 = DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 == (tUInt8)2u;
  DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d79 = DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 == (tUInt8)1u;
  DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d78 = DEF_decodeAddressingMode_addressMode_BITS_2_TO_0___d33 == (tUInt8)0u;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d176 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6___d30 == (tUInt8)2u;
  DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_127_4_7___d68 = DEF_NOT_decodeAddressingMode_pdInst_BIT_127_4___d67;
  DEF__0_OR_0_OR_NOT_decodeAddressingMode_pdInst_BIT__ETC___d69 = DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_127_4_7___d68;
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d70 = DEF__0_OR_0_OR_NOT_decodeAddressingMode_pdInst_BIT__ETC___d69;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d70 = DEF_NOT_decodeAddressingMode_pdInst_BIT_127_4___d67;
  }
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d31 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6___d30 == (tUInt8)0u;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d31 && DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d34;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d77 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50 || DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d121 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d77 || ((!DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d78 && !DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d83) && (!DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d79 && !DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d84));
  DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d136 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d121 ? DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d135 : DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d135;
  DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d91 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d77 ? DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90 : DEF_IF_decodeAddressingMode_addressMode_BITS_2_TO__ETC___d90;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d126 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d121 && DEF_decodeAddressingMode_pdInst_BIT_122___d125;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d127 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d126;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d127 = DEF_decodeAddressingMode_pdInst_BIT_122___d125;
  }
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d123 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d121 && DEF_NOT_decodeAddressingMode_pdInst_BIT_123_11___d122;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d124 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d123;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d124 = DEF_NOT_decodeAddressingMode_pdInst_BIT_123_11___d122;
  }
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d65 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50 && DEF_decodeAddressingMode_pdInst_BIT_127___d64;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d66 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d65;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d66 = DEF_decodeAddressingMode_pdInst_BIT_127___d64;
  }
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d55 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50 && DEF_NOT_decodeAddressingMode_pdInst_BIT_128_2___d54;
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d56 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d55;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d56 = DEF_NOT_decodeAddressingMode_pdInst_BIT_128_2___d54;
  }
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d51 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36 = !DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d31 || !DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d34;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d73 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36 || DEF__0_OR_NOT_decodeAddressingMode_pdInst_BIT_127_4_7___d68;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d47 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36 || DEF__0_OR_decodeAddressingMode_pdInst_BIT_128_2___d43;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d72 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36 || DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d70;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d75 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d72;
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d75 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d73;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d75 = DEF_NOT_decodeAddressingMode_pdInst_BIT_127_4___d67;
  }
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d46 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36 || DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d44;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d49 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d46;
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d49 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d47;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d49 = DEF_decodeAddressingMode_pdInst_BIT_128___d42;
  }
  DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d156 = !DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d37 && !DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d38;
  DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d160 = DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d156 && DEF_decodeAddressingMode_pdInst_BIT_81___d159;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d53 = !DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d76 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d36 && DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d53;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d76 && ((DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d78 || DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d83) || (DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d79 || DEF_decodeAddressingMode_addressMode_BITS_2_TO_0_3_ETC___d84));
  DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d138 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110 ? DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d136 : DEF_decodeAddressingMode_pdInst_BITS_121_TO_119___d137;
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d139 = DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d138;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d139 = DEF_decodeAddressingMode_pdInst_BITS_121_TO_119___d137;
  }
  DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d140 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110 ? DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d136 : DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d139;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d141 = DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d140;
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d141 = DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d138;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d141 = DEF_decodeAddressingMode_pdInst_BITS_121_TO_119___d137;
  }
  DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d98 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d76 ? DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d91 : (DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52 ? DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d95 : DEF_decodeAddressingMode_pdInst_BITS_126_TO_124___d96);
  switch (DEF_x__h658) {
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d99 = DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d98;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d99 = DEF_decodeAddressingMode_pdInst_BITS_126_TO_124___d96;
  }
  DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d101 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d76 ? DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d91 : (DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d52 ? DEF_IF_decodeAddressingMode_addressMode_BITS_7_TO__ETC___d95 : DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d99);
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d102 = DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d101;
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d102 = DEF_IF_NOT_decodeAddressingMode_addressMode_BITS_7_ETC___d98;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d102 = DEF_decodeAddressingMode_pdInst_BITS_126_TO_124___d96;
  }
  DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d103 = DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d75 ? DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d102 : DEF_decodeAddressingMode_pdInst_BITS_126_TO_124___d96;
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d112 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110 || DEF_decodeAddressingMode_pdInst_BIT_123___d111;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d113 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d112;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d113 = DEF_decodeAddressingMode_pdInst_BIT_123___d111;
  }
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d132 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110 || DEF_NOT_decodeAddressingMode_pdInst_BIT_122_25___d128;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d60 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d51 && (DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d53 && DEF_NOT_decodeAddressingMode_pdInst_BIT_128_2___d54);
  DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d131 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d110 || DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d130;
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d134 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d131;
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d134 = DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d132;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d134 = DEF_NOT_decodeAddressingMode_pdInst_BIT_122_25___d128;
  }
  DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d142 = DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d134 ? DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d141 : DEF_decodeAddressingMode_pdInst_BITS_121_TO_119___d137;
  DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d58 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d51 && (DEF_NOT_decodeAddressingMode_addressMode_BITS_7_TO_ETC___d53 && DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d56);
  switch (DEF_x__h658) {
  case (tUInt8)136u:
  case (tUInt8)137u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d62 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d58;
    break;
  case (tUInt8)138u:
  case (tUInt8)139u:
  case (tUInt8)197u:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d62 = DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d60;
    break;
  default:
    DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d62 = DEF_NOT_decodeAddressingMode_pdInst_BIT_128_2___d54;
  }
  DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d11 = !DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d4 && !DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d5;
  DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d15 = DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d11 && DEF_decodeAddressingMode_pdInst_BIT_132___d14;
  DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181.set_bits_in_word(primExtract32(9u,
											       69u,
											       DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173,
											       32u,
											       68u,
											       32u,
											       60u),
										 2u,
										 0u,
										 9u).set_whole_word(primExtract32(32u,
														  69u,
														  DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173,
														  32u,
														  59u,
														  32u,
														  28u),
												    1u).set_whole_word((((DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173.get_bits_in_word32(0u,
																								 0u,
																								 28u) << 4u) | (((tUInt32)((DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50 || DEF_decodeAddressingMode_addressMode_BITS_7_TO_6___d30 == (tUInt8)1u) || DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d176)) << 3u)) | (((tUInt32)(DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d50 || DEF_decodeAddressingMode_addressMode_BITS_7_TO_6_0_ETC___d176)) << 2u)) | (tUInt32)(ARG_decodeAddressingMode_pdInst.get_bits_in_word8(0u,
																																																																																 0u,
																																																																																 2u)),
														       0u);
  DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182.set_bits_in_word(524287u & (((((((tUInt32)(DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d39 || DEF_decodeAddressingMode_pdInst_BIT_82___d152)) << 18u) | (((tUInt32)(DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d156 && !DEF_decodeAddressingMode_pdInst_BIT_82___d152 ? (tUInt8)15u & ((DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d160 << 3u) | DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d165) : (tUInt8)15u & ((DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d160 << 3u) | DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d165))) << 14u)) | (((tUInt32)(DEF_decodeAddressingMode_pdInst_BIT_77___d169)) << 13u)) | (((tUInt32)(DEF_decodeAddressingMode_pdInst_BIT_77___d169 ? DEF_decodeAddressingMode_pdInst_BITS_76_TO_73___d170 : DEF_decodeAddressingMode_pdInst_BITS_76_TO_73___d170)) << 9u)) | DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181.get_bits_in_word32(2u,
																																																																																																																													  0u,
																																																																																																																													  9u)),
										 2u,
										 0u,
										 19u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181.get_whole_word(1u),
												     1u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181.get_whole_word(0u),
															0u);
  DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183.set_bits_in_word(8388607u & (((ARG_decodeAddressingMode_pdInst.get_bits_in_word32(3u,
																		  6u,
																		  17u) << 6u) | (((tUInt32)(DEF_decodeAddressingMode_pdInst_BIT_101___d148)) << 5u)) | (tUInt32)((tUInt8)((DEF_decodeAddressingMode_pdInst_BIT_101___d148 ? DEF_decodeAddressingMode_pdInst_BITS_100_TO_83___d149 : DEF_decodeAddressingMode_pdInst_BITS_100_TO_83___d149) >> 13u))),
										 3u,
										 0u,
										 23u).set_whole_word((((tUInt32)(8191u & (DEF_decodeAddressingMode_pdInst_BIT_101___d148 ? DEF_decodeAddressingMode_pdInst_BITS_100_TO_83___d149 : DEF_decodeAddressingMode_pdInst_BITS_100_TO_83___d149))) << 19u) | DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182.get_bits_in_word32(2u,
																																														       0u,
																																														       19u),
												     2u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182.get_whole_word(1u),
															1u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182.get_whole_word(0u),
																	   0u);
  DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184.build_concat(8589934591llu & (((((((tUInt64)(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d49)) << 32u) | (((tUInt64)(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d62 ? (tUInt8)15u & ((DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d66 << 3u) | DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d103) : (tUInt8)15u & ((DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d66 << 3u) | DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d103))) << 28u)) | (((tUInt64)(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d113)) << 27u)) | (((tUInt64)(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d124 ? (tUInt8)15u & ((DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d127 << 3u) | DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d142) : (tUInt8)15u & ((DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d127 << 3u) | DEF_IF_IF_decodeAddressingMode_pdInst_BITS_172_TO__ETC___d142))) << 23u)) | (tUInt64)(DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183.get_bits_in_word32(3u,
																																																																																																																																														   0u,
																																																																																																																																														   23u))),
									     96u,
									     33u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183.get_whole_word(2u),
												 2u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183.get_whole_word(1u),
														    1u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183.get_whole_word(0u),
																       0u);
  DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185.set_bits_in_word(16777215u & ((((ARG_decodeAddressingMode_pdInst.get_bits_in_word32(4u,
																		    6u,
																		    18u) << 6u) | (((tUInt32)(DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d6 || DEF_decodeAddressingMode_pdInst_BIT_133___d7)) << 5u)) | (((tUInt32)(DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d11 && !DEF_decodeAddressingMode_pdInst_BIT_133___d7 ? (tUInt8)15u & ((DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d15 << 3u) | DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d25) : (tUInt8)15u & ((DEF_NOT_decodeAddressingMode_pdInst_BITS_172_TO_16_ETC___d15 << 3u) | DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d25))) << 1u)) | (tUInt32)(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184.get_bits_in_word8(4u,
																																																																																																						  0u,
																																																																																																						  1u))),
										 4u,
										 0u,
										 24u).set_whole_word(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184.get_whole_word(3u),
												     3u).set_whole_word(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184.get_whole_word(2u),
															2u).set_whole_word(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184.get_whole_word(1u),
																	   1u).set_whole_word(DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184.get_whole_word(0u),
																			      0u);
  PORT_decodeAddressingMode.build_concat(35184372088831llu & (((((tUInt64)(DEF_decodeAddressingMode_pdInst_BITS_172_TO_160___d1)) << 32u) | (((tUInt64)(ARG_decodeAddressingMode_addressMode)) << 24u)) | (tUInt64)(DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185.get_bits_in_word32(4u,
																																				     0u,
																																				     24u))),
					 128u,
					 45u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185.get_whole_word(3u),
							     3u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185.get_whole_word(2u),
										2u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185.get_whole_word(1u),
												   1u).set_whole_word(DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185.get_whole_word(0u),
														      0u);
  return PORT_decodeAddressingMode;
}

tUInt8 MOD_module_decodeAddressingMode::METH_RDY_decodeAddressingMode()
{
  DEF_CAN_FIRE_decodeAddressingMode = (tUInt8)1u;
  PORT_RDY_decodeAddressingMode = DEF_CAN_FIRE_decodeAddressingMode;
  return PORT_RDY_decodeAddressingMode;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_decodeAddressingMode::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_decodeAddressingMode::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 11u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_decodeAddressingMode", 1u);
  vcd_write_def(sim_hdl, num++, "IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184", 129u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183", 119u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185", 152u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182", 83u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181", 73u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_pdInst_BITS_72_TO_4___d173", 69u);
  vcd_write_def(sim_hdl, num++, "RDY_decodeAddressingMode", 1u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode", 173u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_addressMode", 8u);
  vcd_write_def(sim_hdl, num++, "decodeAddressingMode_pdInst", 173u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_decodeAddressingMode::dump_VCD(tVCDDumpType dt,
					       unsigned int levels,
					       MOD_module_decodeAddressingMode &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_decodeAddressingMode::vcd_defs(tVCDDumpType dt,
					       MOD_module_decodeAddressingMode &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 119u);
    vcd_write_x(sim_hdl, num++, 152u);
    vcd_write_x(sim_hdl, num++, 83u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 69u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 173u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 173u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_decodeAddressingMode) != DEF_CAN_FIRE_decodeAddressingMode)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_decodeAddressingMode, 1u);
	backing.DEF_CAN_FIRE_decodeAddressingMode = DEF_CAN_FIRE_decodeAddressingMode;
      }
      ++num;
      if ((backing.DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184) != DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184, 129u);
	backing.DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184 = DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184;
      }
      ++num;
      if ((backing.DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183) != DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183, 119u);
	backing.DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183 = DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183;
      }
      ++num;
      if ((backing.DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185) != DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185, 152u);
	backing.DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185 = DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185;
      }
      ++num;
      if ((backing.DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182) != DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182, 83u);
	backing.DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182 = DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182;
      }
      ++num;
      if ((backing.DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181) != DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181, 73u);
	backing.DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181 = DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181;
      }
      ++num;
      if ((backing.DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173) != DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173, 69u);
	backing.DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173 = DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173;
      }
      ++num;
      if ((backing.PORT_RDY_decodeAddressingMode) != PORT_RDY_decodeAddressingMode)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_decodeAddressingMode, 1u);
	backing.PORT_RDY_decodeAddressingMode = PORT_RDY_decodeAddressingMode;
      }
      ++num;
      if ((backing.PORT_decodeAddressingMode) != PORT_decodeAddressingMode)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeAddressingMode, 173u);
	backing.PORT_decodeAddressingMode = PORT_decodeAddressingMode;
      }
      ++num;
      if ((backing.PORT_decodeAddressingMode_addressMode) != PORT_decodeAddressingMode_addressMode)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeAddressingMode_addressMode, 8u);
	backing.PORT_decodeAddressingMode_addressMode = PORT_decodeAddressingMode_addressMode;
      }
      ++num;
      if ((backing.PORT_decodeAddressingMode_pdInst) != PORT_decodeAddressingMode_pdInst)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeAddressingMode_pdInst, 173u);
	backing.PORT_decodeAddressingMode_pdInst = PORT_decodeAddressingMode_pdInst;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_decodeAddressingMode, 1u);
      backing.DEF_CAN_FIRE_decodeAddressingMode = DEF_CAN_FIRE_decodeAddressingMode;
      vcd_write_val(sim_hdl, num++, DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184, 129u);
      backing.DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184 = DEF_IF_decodeAddressingMode_pdInst_BITS_172_TO_165_ETC___d184;
      vcd_write_val(sim_hdl, num++, DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183, 119u);
      backing.DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183 = DEF_decodeAddressingMode_pdInst_BITS_118_TO_102_47_ETC___d183;
      vcd_write_val(sim_hdl, num++, DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185, 152u);
      backing.DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185 = DEF_decodeAddressingMode_pdInst_BITS_151_TO_134_CO_ETC___d185;
      vcd_write_val(sim_hdl, num++, DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182, 83u);
      backing.DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182 = DEF_decodeAddressingMode_pdInst_BITS_172_TO_165_EQ_ETC___d182;
      vcd_write_val(sim_hdl, num++, DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181, 73u);
      backing.DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181 = DEF_decodeAddressingMode_pdInst_BITS_72_TO_4_73_CO_ETC___d181;
      vcd_write_val(sim_hdl, num++, DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173, 69u);
      backing.DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173 = DEF_decodeAddressingMode_pdInst_BITS_72_TO_4___d173;
      vcd_write_val(sim_hdl, num++, PORT_RDY_decodeAddressingMode, 1u);
      backing.PORT_RDY_decodeAddressingMode = PORT_RDY_decodeAddressingMode;
      vcd_write_val(sim_hdl, num++, PORT_decodeAddressingMode, 173u);
      backing.PORT_decodeAddressingMode = PORT_decodeAddressingMode;
      vcd_write_val(sim_hdl, num++, PORT_decodeAddressingMode_addressMode, 8u);
      backing.PORT_decodeAddressingMode_addressMode = PORT_decodeAddressingMode_addressMode;
      vcd_write_val(sim_hdl, num++, PORT_decodeAddressingMode_pdInst, 173u);
      backing.PORT_decodeAddressingMode_pdInst = PORT_decodeAddressingMode_pdInst;
    }
}
