/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Tue Nov 25 02:07:28 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "module_decodeHighData.h"


/* Constructor */
MOD_module_decodeHighData::MOD_module_decodeHighData(tSimStateHdl simHdl,
						     char const *name,
						     Module *parent)
  : Module(simHdl, name, parent),
    DEF_decodeHighData_pdInst_BITS_72_TO_0___d26(73u),
    DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29(129u),
    DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28(119u),
    DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27(83u)
{
  PORT_decodeHighData_pdInst.setSize(173u);
  PORT_decodeHighData_pdInst.clear();
  PORT_decodeHighData_highData = 0u;
  PORT_decodeHighData.setSize(173u);
  PORT_decodeHighData.clear();
  PORT_RDY_decodeHighData = false;
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_decodeHighData::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_decodeHighData", SYM_DEF, &DEF_CAN_FIRE_decodeHighData, 1u);
  init_symbol(&symbols[1u], "decodeHighData", SYM_PORT, &PORT_decodeHighData, 173u);
  init_symbol(&symbols[2u], "decodeHighData_highData", SYM_PORT, &PORT_decodeHighData_highData, 8u);
  init_symbol(&symbols[3u], "decodeHighData_pdInst", SYM_PORT, &PORT_decodeHighData_pdInst, 173u);
  init_symbol(&symbols[4u], "RDY_decodeHighData", SYM_PORT, &PORT_RDY_decodeHighData, 1u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_decodeHighData::METH_decodeHighData(tUWide ARG_decodeHighData_pdInst,
						      tUInt8 ARG_decodeHighData_highData)
{
  tUInt8 DEF_decodeHighData_pdInst_BIT_133_CONCAT_IF_decode_ETC___d5;
  tUInt8 DEF_decodeHighData_pdInst_BIT_77___d22;
  tUInt8 DEF_decodeHighData_pdInst_BIT_82___d19;
  tUInt8 DEF_decodeHighData_pdInst_BIT_101___d15;
  tUInt8 DEF_decodeHighData_pdInst_BIT_123___d9;
  tUInt8 DEF_decodeHighData_pdInst_BIT_128___d6;
  tUInt8 DEF_decodeHighData_pdInst_BIT_133___d2;
  tUInt8 DEF_decodeHighData_pdInst_BITS_76_TO_73___d23;
  tUInt8 DEF_decodeHighData_pdInst_BITS_81_TO_78___d20;
  tUInt8 DEF_decodeHighData_pdInst_BITS_122_TO_119___d10;
  tUInt8 DEF_decodeHighData_pdInst_BITS_127_TO_124___d7;
  tUInt8 DEF_decodeHighData_pdInst_BITS_132_TO_129___d3;
  tUInt32 DEF_decodeHighData_pdInst_BITS_100_TO_83___d16;
  tUInt64 DEF_decodeHighData_pdInst_BITS_172_TO_134___d1;
  PORT_decodeHighData_pdInst = ARG_decodeHighData_pdInst;
  PORT_decodeHighData_highData = ARG_decodeHighData_highData;
  wop_primExtractWide(73u,
		      173u,
		      ARG_decodeHighData_pdInst,
		      32u,
		      72u,
		      32u,
		      0u,
		      DEF_decodeHighData_pdInst_BITS_72_TO_0___d26);
  DEF_decodeHighData_pdInst_BITS_172_TO_134___d1 = primExtract64(39u,
								 173u,
								 ARG_decodeHighData_pdInst,
								 32u,
								 172u,
								 32u,
								 134u);
  DEF_decodeHighData_pdInst_BITS_100_TO_83___d16 = primExtract32(18u,
								 173u,
								 ARG_decodeHighData_pdInst,
								 32u,
								 100u,
								 32u,
								 83u);
  DEF_decodeHighData_pdInst_BITS_132_TO_129___d3 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u,
											       1u,
											       4u);
  DEF_decodeHighData_pdInst_BITS_127_TO_124___d7 = ARG_decodeHighData_pdInst.get_bits_in_word8(3u,
											       28u,
											       4u);
  DEF_decodeHighData_pdInst_BITS_122_TO_119___d10 = ARG_decodeHighData_pdInst.get_bits_in_word8(3u,
												23u,
												4u);
  DEF_decodeHighData_pdInst_BITS_76_TO_73___d23 = ARG_decodeHighData_pdInst.get_bits_in_word8(2u,
											      9u,
											      4u);
  DEF_decodeHighData_pdInst_BITS_81_TO_78___d20 = ARG_decodeHighData_pdInst.get_bits_in_word8(2u,
											      14u,
											      4u);
  DEF_decodeHighData_pdInst_BIT_133___d2 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u, 5u, 1u);
  DEF_decodeHighData_pdInst_BIT_128___d6 = ARG_decodeHighData_pdInst.get_bits_in_word8(4u, 0u, 1u);
  DEF_decodeHighData_pdInst_BIT_101___d15 = ARG_decodeHighData_pdInst.get_bits_in_word8(3u, 5u, 1u);
  DEF_decodeHighData_pdInst_BIT_123___d9 = ARG_decodeHighData_pdInst.get_bits_in_word8(3u, 27u, 1u);
  DEF_decodeHighData_pdInst_BIT_82___d19 = ARG_decodeHighData_pdInst.get_bits_in_word8(2u, 18u, 1u);
  DEF_decodeHighData_pdInst_BIT_77___d22 = ARG_decodeHighData_pdInst.get_bits_in_word8(2u, 13u, 1u);
  DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27.set_bits_in_word(524287u & (((((((tUInt32)(DEF_decodeHighData_pdInst_BIT_82___d19)) << 18u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_82___d19 ? DEF_decodeHighData_pdInst_BITS_81_TO_78___d20 : DEF_decodeHighData_pdInst_BITS_81_TO_78___d20)) << 14u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_77___d22)) << 13u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_77___d22 ? DEF_decodeHighData_pdInst_BITS_76_TO_73___d23 : DEF_decodeHighData_pdInst_BITS_76_TO_73___d23)) << 9u)) | DEF_decodeHighData_pdInst_BITS_72_TO_0___d26.get_bits_in_word32(2u,
																																																																											    0u,
																																																																											    9u)),
										2u,
										0u,
										19u).set_whole_word(DEF_decodeHighData_pdInst_BITS_72_TO_0___d26.get_whole_word(1u),
												    1u).set_whole_word(DEF_decodeHighData_pdInst_BITS_72_TO_0___d26.get_whole_word(0u),
														       0u);
  DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28.set_bits_in_word(8388607u & (((((((tUInt32)((tUInt8)1u)) << 22u) | (((tUInt32)(ARG_decodeHighData_highData)) << 14u)) | (((tUInt32)(ARG_decodeHighData_pdInst.get_bits_in_word8(3u,
																														6u,
																														8u))) << 6u)) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_101___d15)) << 5u)) | (tUInt32)((tUInt8)((DEF_decodeHighData_pdInst_BIT_101___d15 ? DEF_decodeHighData_pdInst_BITS_100_TO_83___d16 : DEF_decodeHighData_pdInst_BITS_100_TO_83___d16) >> 13u))),
										 3u,
										 0u,
										 23u).set_whole_word((((tUInt32)(8191u & (DEF_decodeHighData_pdInst_BIT_101___d15 ? DEF_decodeHighData_pdInst_BITS_100_TO_83___d16 : DEF_decodeHighData_pdInst_BITS_100_TO_83___d16))) << 19u) | DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27.get_bits_in_word32(2u,
																																												 0u,
																																												 19u),
												     2u).set_whole_word(DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27.get_whole_word(1u),
															1u).set_whole_word(DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27.get_whole_word(0u),
																	   0u);
  DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29.build_concat(8589934591llu & (((((((tUInt64)(DEF_decodeHighData_pdInst_BIT_128___d6)) << 32u) | (((tUInt64)(DEF_decodeHighData_pdInst_BIT_128___d6 ? DEF_decodeHighData_pdInst_BITS_127_TO_124___d7 : DEF_decodeHighData_pdInst_BITS_127_TO_124___d7)) << 28u)) | (((tUInt64)(DEF_decodeHighData_pdInst_BIT_123___d9)) << 27u)) | (((tUInt64)(DEF_decodeHighData_pdInst_BIT_123___d9 ? DEF_decodeHighData_pdInst_BITS_122_TO_119___d10 : DEF_decodeHighData_pdInst_BITS_122_TO_119___d10)) << 23u)) | (tUInt64)(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28.get_bits_in_word32(3u,
																																																																																0u,
																																																																																23u))),
									    96u,
									    33u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28.get_whole_word(2u),
												2u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28.get_whole_word(1u),
														   1u).set_whole_word(DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28.get_whole_word(0u),
																      0u);
  DEF_decodeHighData_pdInst_BIT_133_CONCAT_IF_decode_ETC___d5 = (tUInt8)31u & ((DEF_decodeHighData_pdInst_BIT_133___d2 << 4u) | (DEF_decodeHighData_pdInst_BIT_133___d2 ? DEF_decodeHighData_pdInst_BITS_132_TO_129___d3 : DEF_decodeHighData_pdInst_BITS_132_TO_129___d3));
  PORT_decodeHighData.set_bits_in_word((tUInt32)(DEF_decodeHighData_pdInst_BITS_172_TO_134___d1 >> 26u),
				       5u,
				       0u,
				       13u).set_whole_word(((((tUInt32)(67108863u & DEF_decodeHighData_pdInst_BITS_172_TO_134___d1)) << 6u) | (((tUInt32)(DEF_decodeHighData_pdInst_BIT_133_CONCAT_IF_decode_ETC___d5)) << 1u)) | (tUInt32)(DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29.get_bits_in_word8(4u,
																																							   0u,
																																							   1u)),
							   4u).set_whole_word(DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29.get_whole_word(3u),
									      3u).set_whole_word(DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29.get_whole_word(2u),
												 2u).set_whole_word(DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29.get_whole_word(1u),
														    1u).set_whole_word(DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29.get_whole_word(0u),
																       0u);
  return PORT_decodeHighData;
}

tUInt8 MOD_module_decodeHighData::METH_RDY_decodeHighData()
{
  DEF_CAN_FIRE_decodeHighData = (tUInt8)1u;
  PORT_RDY_decodeHighData = DEF_CAN_FIRE_decodeHighData;
  return PORT_RDY_decodeHighData;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_decodeHighData::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_decodeHighData::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 9u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_decodeHighData", 1u);
  vcd_write_def(sim_hdl, num++, "_1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28", 119u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BITS_72_TO_0___d26", 73u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29", 129u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27", 83u);
  vcd_write_def(sim_hdl, num++, "RDY_decodeHighData", 1u);
  vcd_write_def(sim_hdl, num++, "decodeHighData", 173u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_highData", 8u);
  vcd_write_def(sim_hdl, num++, "decodeHighData_pdInst", 173u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_decodeHighData::dump_VCD(tVCDDumpType dt,
					 unsigned int levels,
					 MOD_module_decodeHighData &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_decodeHighData::vcd_defs(tVCDDumpType dt, MOD_module_decodeHighData &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 119u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 83u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 173u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 173u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_decodeHighData) != DEF_CAN_FIRE_decodeHighData)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_decodeHighData, 1u);
	backing.DEF_CAN_FIRE_decodeHighData = DEF_CAN_FIRE_decodeHighData;
      }
      ++num;
      if ((backing.DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28) != DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28)
      {
	vcd_write_val(sim_hdl, num, DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28, 119u);
	backing.DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28 = DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BITS_72_TO_0___d26) != DEF_decodeHighData_pdInst_BITS_72_TO_0___d26)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BITS_72_TO_0___d26, 73u);
	backing.DEF_decodeHighData_pdInst_BITS_72_TO_0___d26 = DEF_decodeHighData_pdInst_BITS_72_TO_0___d26;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29) != DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29, 129u);
	backing.DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29 = DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29;
      }
      ++num;
      if ((backing.DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27) != DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27, 83u);
	backing.DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27 = DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27;
      }
      ++num;
      if ((backing.PORT_RDY_decodeHighData) != PORT_RDY_decodeHighData)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_decodeHighData, 1u);
	backing.PORT_RDY_decodeHighData = PORT_RDY_decodeHighData;
      }
      ++num;
      if ((backing.PORT_decodeHighData) != PORT_decodeHighData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeHighData, 173u);
	backing.PORT_decodeHighData = PORT_decodeHighData;
      }
      ++num;
      if ((backing.PORT_decodeHighData_highData) != PORT_decodeHighData_highData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeHighData_highData, 8u);
	backing.PORT_decodeHighData_highData = PORT_decodeHighData_highData;
      }
      ++num;
      if ((backing.PORT_decodeHighData_pdInst) != PORT_decodeHighData_pdInst)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeHighData_pdInst, 173u);
	backing.PORT_decodeHighData_pdInst = PORT_decodeHighData_pdInst;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_decodeHighData, 1u);
      backing.DEF_CAN_FIRE_decodeHighData = DEF_CAN_FIRE_decodeHighData;
      vcd_write_val(sim_hdl, num++, DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28, 119u);
      backing.DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28 = DEF__1_CONCAT_decodeHighData_highData_CONCAT_decode_ETC___d28;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BITS_72_TO_0___d26, 73u);
      backing.DEF_decodeHighData_pdInst_BITS_72_TO_0___d26 = DEF_decodeHighData_pdInst_BITS_72_TO_0___d26;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29, 129u);
      backing.DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29 = DEF_decodeHighData_pdInst_BIT_128_CONCAT_IF_decode_ETC___d29;
      vcd_write_val(sim_hdl, num++, DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27, 83u);
      backing.DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27 = DEF_decodeHighData_pdInst_BIT_82_9_CONCAT_IF_decod_ETC___d27;
      vcd_write_val(sim_hdl, num++, PORT_RDY_decodeHighData, 1u);
      backing.PORT_RDY_decodeHighData = PORT_RDY_decodeHighData;
      vcd_write_val(sim_hdl, num++, PORT_decodeHighData, 173u);
      backing.PORT_decodeHighData = PORT_decodeHighData;
      vcd_write_val(sim_hdl, num++, PORT_decodeHighData_highData, 8u);
      backing.PORT_decodeHighData_highData = PORT_decodeHighData_highData;
      vcd_write_val(sim_hdl, num++, PORT_decodeHighData_pdInst, 173u);
      backing.PORT_decodeHighData_pdInst = PORT_decodeHighData_pdInst;
    }
}
