/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Tue Nov 25 02:07:28 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "module_decodeLowData.h"


/* Constructor */
MOD_module_decodeLowData::MOD_module_decodeLowData(tSimStateHdl simHdl,
						   char const *name,
						   Module *parent)
  : Module(simHdl, name, parent),
    DEF_decodeLowData_pdInst_BITS_72_TO_0___d25(73u),
    DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28(129u),
    DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27(119u),
    DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26(83u)
{
  PORT_decodeLowData_pdInst.setSize(173u);
  PORT_decodeLowData_pdInst.clear();
  PORT_decodeLowData_lowData = 0u;
  PORT_decodeLowData.setSize(173u);
  PORT_decodeLowData.clear();
  PORT_RDY_decodeLowData = false;
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_decodeLowData::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_decodeLowData", SYM_DEF, &DEF_CAN_FIRE_decodeLowData, 1u);
  init_symbol(&symbols[1u], "decodeLowData", SYM_PORT, &PORT_decodeLowData, 173u);
  init_symbol(&symbols[2u], "decodeLowData_lowData", SYM_PORT, &PORT_decodeLowData_lowData, 8u);
  init_symbol(&symbols[3u], "decodeLowData_pdInst", SYM_PORT, &PORT_decodeLowData_pdInst, 173u);
  init_symbol(&symbols[4u], "RDY_decodeLowData", SYM_PORT, &PORT_RDY_decodeLowData, 1u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_decodeLowData::METH_decodeLowData(tUWide ARG_decodeLowData_pdInst,
						    tUInt8 ARG_decodeLowData_lowData)
{
  tUInt8 DEF_decodeLowData_pdInst_BIT_133_CONCAT_IF_decodeL_ETC___d5;
  tUInt8 DEF_decodeLowData_pdInst_BIT_77___d21;
  tUInt8 DEF_decodeLowData_pdInst_BIT_82___d18;
  tUInt8 DEF_decodeLowData_pdInst_BIT_101___d14;
  tUInt8 DEF_decodeLowData_pdInst_BIT_123___d9;
  tUInt8 DEF_decodeLowData_pdInst_BIT_128___d6;
  tUInt8 DEF_decodeLowData_pdInst_BIT_133___d2;
  tUInt8 DEF_decodeLowData_pdInst_BITS_76_TO_73___d22;
  tUInt8 DEF_decodeLowData_pdInst_BITS_81_TO_78___d19;
  tUInt8 DEF_decodeLowData_pdInst_BITS_122_TO_119___d10;
  tUInt8 DEF_decodeLowData_pdInst_BITS_127_TO_124___d7;
  tUInt8 DEF_decodeLowData_pdInst_BITS_132_TO_129___d3;
  tUInt32 DEF_decodeLowData_pdInst_BITS_100_TO_83___d15;
  tUInt64 DEF_decodeLowData_pdInst_BITS_172_TO_134___d1;
  PORT_decodeLowData_pdInst = ARG_decodeLowData_pdInst;
  PORT_decodeLowData_lowData = ARG_decodeLowData_lowData;
  wop_primExtractWide(73u,
		      173u,
		      ARG_decodeLowData_pdInst,
		      32u,
		      72u,
		      32u,
		      0u,
		      DEF_decodeLowData_pdInst_BITS_72_TO_0___d25);
  DEF_decodeLowData_pdInst_BITS_172_TO_134___d1 = primExtract64(39u,
								173u,
								ARG_decodeLowData_pdInst,
								32u,
								172u,
								32u,
								134u);
  DEF_decodeLowData_pdInst_BITS_100_TO_83___d15 = primExtract32(18u,
								173u,
								ARG_decodeLowData_pdInst,
								32u,
								100u,
								32u,
								83u);
  DEF_decodeLowData_pdInst_BITS_132_TO_129___d3 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u,
											     1u,
											     4u);
  DEF_decodeLowData_pdInst_BITS_127_TO_124___d7 = ARG_decodeLowData_pdInst.get_bits_in_word8(3u,
											     28u,
											     4u);
  DEF_decodeLowData_pdInst_BITS_122_TO_119___d10 = ARG_decodeLowData_pdInst.get_bits_in_word8(3u,
											      23u,
											      4u);
  DEF_decodeLowData_pdInst_BITS_76_TO_73___d22 = ARG_decodeLowData_pdInst.get_bits_in_word8(2u,
											    9u,
											    4u);
  DEF_decodeLowData_pdInst_BITS_81_TO_78___d19 = ARG_decodeLowData_pdInst.get_bits_in_word8(2u,
											    14u,
											    4u);
  DEF_decodeLowData_pdInst_BIT_133___d2 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u, 5u, 1u);
  DEF_decodeLowData_pdInst_BIT_128___d6 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u, 0u, 1u);
  DEF_decodeLowData_pdInst_BIT_101___d14 = ARG_decodeLowData_pdInst.get_bits_in_word8(3u, 5u, 1u);
  DEF_decodeLowData_pdInst_BIT_123___d9 = ARG_decodeLowData_pdInst.get_bits_in_word8(3u, 27u, 1u);
  DEF_decodeLowData_pdInst_BIT_82___d18 = ARG_decodeLowData_pdInst.get_bits_in_word8(2u, 18u, 1u);
  DEF_decodeLowData_pdInst_BIT_77___d21 = ARG_decodeLowData_pdInst.get_bits_in_word8(2u, 13u, 1u);
  DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26.set_bits_in_word(524287u & (((((((tUInt32)(DEF_decodeLowData_pdInst_BIT_82___d18)) << 18u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_82___d18 ? DEF_decodeLowData_pdInst_BITS_81_TO_78___d19 : DEF_decodeLowData_pdInst_BITS_81_TO_78___d19)) << 14u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_77___d21)) << 13u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_77___d21 ? DEF_decodeLowData_pdInst_BITS_76_TO_73___d22 : DEF_decodeLowData_pdInst_BITS_76_TO_73___d22)) << 9u)) | DEF_decodeLowData_pdInst_BITS_72_TO_0___d25.get_bits_in_word32(2u,
																																																																										   0u,
																																																																										   9u)),
										2u,
										0u,
										19u).set_whole_word(DEF_decodeLowData_pdInst_BITS_72_TO_0___d25.get_whole_word(1u),
												    1u).set_whole_word(DEF_decodeLowData_pdInst_BITS_72_TO_0___d25.get_whole_word(0u),
														       0u);
  DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27.set_bits_in_word(8388607u & ((((170u << 14u) | (((tUInt32)(ARG_decodeLowData_lowData)) << 6u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_101___d14)) << 5u)) | (tUInt32)((tUInt8)((DEF_decodeLowData_pdInst_BIT_101___d14 ? DEF_decodeLowData_pdInst_BITS_100_TO_83___d15 : DEF_decodeLowData_pdInst_BITS_100_TO_83___d15) >> 13u))),
										 3u,
										 0u,
										 23u).set_whole_word((((tUInt32)(8191u & (DEF_decodeLowData_pdInst_BIT_101___d14 ? DEF_decodeLowData_pdInst_BITS_100_TO_83___d15 : DEF_decodeLowData_pdInst_BITS_100_TO_83___d15))) << 19u) | DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26.get_bits_in_word32(2u,
																																											      0u,
																																											      19u),
												     2u).set_whole_word(DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26.get_whole_word(1u),
															1u).set_whole_word(DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26.get_whole_word(0u),
																	   0u);
  DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28.build_concat(8589934591llu & (((((((tUInt64)(DEF_decodeLowData_pdInst_BIT_128___d6)) << 32u) | (((tUInt64)(DEF_decodeLowData_pdInst_BIT_128___d6 ? DEF_decodeLowData_pdInst_BITS_127_TO_124___d7 : DEF_decodeLowData_pdInst_BITS_127_TO_124___d7)) << 28u)) | (((tUInt64)(DEF_decodeLowData_pdInst_BIT_123___d9)) << 27u)) | (((tUInt64)(DEF_decodeLowData_pdInst_BIT_123___d9 ? DEF_decodeLowData_pdInst_BITS_122_TO_119___d10 : DEF_decodeLowData_pdInst_BITS_122_TO_119___d10)) << 23u)) | (tUInt64)(DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27.get_bits_in_word32(3u,
																																																																															0u,
																																																																															23u))),
									    96u,
									    33u).set_whole_word(DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27.get_whole_word(2u),
												2u).set_whole_word(DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27.get_whole_word(1u),
														   1u).set_whole_word(DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27.get_whole_word(0u),
																      0u);
  DEF_decodeLowData_pdInst_BIT_133_CONCAT_IF_decodeL_ETC___d5 = (tUInt8)31u & ((DEF_decodeLowData_pdInst_BIT_133___d2 << 4u) | (DEF_decodeLowData_pdInst_BIT_133___d2 ? DEF_decodeLowData_pdInst_BITS_132_TO_129___d3 : DEF_decodeLowData_pdInst_BITS_132_TO_129___d3));
  PORT_decodeLowData.set_bits_in_word((tUInt32)(DEF_decodeLowData_pdInst_BITS_172_TO_134___d1 >> 26u),
				      5u,
				      0u,
				      13u).set_whole_word(((((tUInt32)(67108863u & DEF_decodeLowData_pdInst_BITS_172_TO_134___d1)) << 6u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_133_CONCAT_IF_decodeL_ETC___d5)) << 1u)) | (tUInt32)(DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28.get_bits_in_word8(4u,
																																							 0u,
																																							 1u)),
							  4u).set_whole_word(DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28.get_whole_word(3u),
									     3u).set_whole_word(DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28.get_whole_word(2u),
												2u).set_whole_word(DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28.get_whole_word(1u),
														   1u).set_whole_word(DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28.get_whole_word(0u),
																      0u);
  return PORT_decodeLowData;
}

tUInt8 MOD_module_decodeLowData::METH_RDY_decodeLowData()
{
  DEF_CAN_FIRE_decodeLowData = (tUInt8)1u;
  PORT_RDY_decodeLowData = DEF_CAN_FIRE_decodeLowData;
  return PORT_RDY_decodeLowData;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_decodeLowData::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_decodeLowData::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 9u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_decodeLowData", 1u);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27", 119u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BITS_72_TO_0___d25", 73u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28", 129u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26", 83u);
  vcd_write_def(sim_hdl, num++, "RDY_decodeLowData", 1u);
  vcd_write_def(sim_hdl, num++, "decodeLowData", 173u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_lowData", 8u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst", 173u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_decodeLowData::dump_VCD(tVCDDumpType dt,
					unsigned int levels,
					MOD_module_decodeLowData &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_decodeLowData::vcd_defs(tVCDDumpType dt, MOD_module_decodeLowData &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 119u);
    vcd_write_x(sim_hdl, num++, 73u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 83u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 173u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 173u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_decodeLowData) != DEF_CAN_FIRE_decodeLowData)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_decodeLowData, 1u);
	backing.DEF_CAN_FIRE_decodeLowData = DEF_CAN_FIRE_decodeLowData;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27) != DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27, 119u);
	backing.DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27 = DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BITS_72_TO_0___d25) != DEF_decodeLowData_pdInst_BITS_72_TO_0___d25)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BITS_72_TO_0___d25, 73u);
	backing.DEF_decodeLowData_pdInst_BITS_72_TO_0___d25 = DEF_decodeLowData_pdInst_BITS_72_TO_0___d25;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28) != DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28, 129u);
	backing.DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28 = DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26) != DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26, 83u);
	backing.DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26 = DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26;
      }
      ++num;
      if ((backing.PORT_RDY_decodeLowData) != PORT_RDY_decodeLowData)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_decodeLowData, 1u);
	backing.PORT_RDY_decodeLowData = PORT_RDY_decodeLowData;
      }
      ++num;
      if ((backing.PORT_decodeLowData) != PORT_decodeLowData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeLowData, 173u);
	backing.PORT_decodeLowData = PORT_decodeLowData;
      }
      ++num;
      if ((backing.PORT_decodeLowData_lowData) != PORT_decodeLowData_lowData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeLowData_lowData, 8u);
	backing.PORT_decodeLowData_lowData = PORT_decodeLowData_lowData;
      }
      ++num;
      if ((backing.PORT_decodeLowData_pdInst) != PORT_decodeLowData_pdInst)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeLowData_pdInst, 173u);
	backing.PORT_decodeLowData_pdInst = PORT_decodeLowData_pdInst;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_decodeLowData, 1u);
      backing.DEF_CAN_FIRE_decodeLowData = DEF_CAN_FIRE_decodeLowData;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27, 119u);
      backing.DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27 = DEF__0_CONCAT_DONTCARE_CONCAT_decodeLowData_lowData_ETC___d27;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BITS_72_TO_0___d25, 73u);
      backing.DEF_decodeLowData_pdInst_BITS_72_TO_0___d25 = DEF_decodeLowData_pdInst_BITS_72_TO_0___d25;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28, 129u);
      backing.DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28 = DEF_decodeLowData_pdInst_BIT_128_CONCAT_IF_decodeL_ETC___d28;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26, 83u);
      backing.DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26 = DEF_decodeLowData_pdInst_BIT_82_8_CONCAT_IF_decode_ETC___d26;
      vcd_write_val(sim_hdl, num++, PORT_RDY_decodeLowData, 1u);
      backing.PORT_RDY_decodeLowData = PORT_RDY_decodeLowData;
      vcd_write_val(sim_hdl, num++, PORT_decodeLowData, 173u);
      backing.PORT_decodeLowData = PORT_decodeLowData;
      vcd_write_val(sim_hdl, num++, PORT_decodeLowData_lowData, 8u);
      backing.PORT_decodeLowData_lowData = PORT_decodeLowData_lowData;
      vcd_write_val(sim_hdl, num++, PORT_decodeLowData_pdInst, 173u);
      backing.PORT_decodeLowData_pdInst = PORT_decodeLowData_pdInst;
    }
}
