/*
 * Generated by Bluespec Compiler, version 2014.06.A (build 33987, 2014-06-24)
 * 
 * On Wed Nov 26 13:26:23 EST 2014
 * 
 */
#include "bluesim_primitives.h"
#include "module_decodeLowData.h"


/* Constructor */
MOD_module_decodeLowData::MOD_module_decodeLowData(tSimStateHdl simHdl,
						   char const *name,
						   Module *parent)
  : Module(simHdl, name, parent),
    DEF_decodeLowData_pdInst_BITS_105_TO_0___d51(106u),
    DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56(215u),
    DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55(205u),
    DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54(169u),
    DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53(147u),
    DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52(123u)
{
  PORT_decodeLowData_pdInst.setSize(260u);
  PORT_decodeLowData_pdInst.clear();
  PORT_decodeLowData_lowData = 0u;
  PORT_decodeLowData.setSize(260u);
  PORT_decodeLowData.clear();
  PORT_RDY_decodeLowData = false;
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_decodeLowData::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_decodeLowData", SYM_DEF, &DEF_CAN_FIRE_decodeLowData, 1u);
  init_symbol(&symbols[1u], "decodeLowData", SYM_PORT, &PORT_decodeLowData, 260u);
  init_symbol(&symbols[2u], "decodeLowData_lowData", SYM_PORT, &PORT_decodeLowData_lowData, 8u);
  init_symbol(&symbols[3u], "decodeLowData_pdInst", SYM_PORT, &PORT_decodeLowData_pdInst, 260u);
  init_symbol(&symbols[4u], "RDY_decodeLowData", SYM_PORT, &PORT_RDY_decodeLowData, 1u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_decodeLowData::METH_decodeLowData(tUWide ARG_decodeLowData_pdInst,
						    tUInt8 ARG_decodeLowData_lowData)
{
  tUInt8 DEF_decodeLowData_pdInst_BIT_219_CONCAT_IF_decodeL_ETC___d5;
  tUInt8 DEF_NOT_decodeLowData_pdInst_BITS_259_TO_252_3_EQ__ETC___d17;
  tUInt8 DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14;
  tUInt32 DEF_IF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0_ETC___d49;
  tUInt8 DEF_decodeLowData_pdInst_BIT_122___d43;
  tUInt8 DEF_decodeLowData_pdInst_BIT_141___d39;
  tUInt8 DEF_decodeLowData_pdInst_BIT_146___d36;
  tUInt8 DEF_decodeLowData_pdInst_BIT_151___d32;
  tUInt8 DEF_decodeLowData_pdInst_BIT_168___d29;
  tUInt8 DEF_decodeLowData_pdInst_BIT_187___d25;
  tUInt8 DEF_decodeLowData_pdInst_BIT_204___d15;
  tUInt8 DEF_decodeLowData_pdInst_BIT_209___d9;
  tUInt8 DEF_decodeLowData_pdInst_BIT_214___d6;
  tUInt8 DEF_decodeLowData_pdInst_BIT_219___d2;
  tUInt8 DEF_decodeLowData_pdInst_BITS_145_TO_142___d37;
  tUInt8 DEF_decodeLowData_pdInst_BITS_150_TO_147___d33;
  tUInt8 DEF_decodeLowData_pdInst_BITS_208_TO_205___d10;
  tUInt8 DEF_decodeLowData_pdInst_BITS_213_TO_210___d7;
  tUInt8 DEF_decodeLowData_pdInst_BITS_218_TO_215___d3;
  tUInt8 DEF_pdInst_opcode__h53;
  tUInt32 DEF_x__h1122;
  tUInt32 DEF_decodeLowData_pdInst_BITS_167_TO_152___d30;
  tUInt32 DEF_decodeLowData_pdInst_BITS_140_TO_123___d40;
  tUInt32 DEF_decodeLowData_pdInst_BITS_186_TO_169___d26;
  tUInt64 DEF_decodeLowData_pdInst_BITS_259_TO_220___d1;
  PORT_decodeLowData_pdInst = ARG_decodeLowData_pdInst;
  PORT_decodeLowData_lowData = ARG_decodeLowData_lowData;
  wop_primExtractWide(106u,
		      260u,
		      ARG_decodeLowData_pdInst,
		      32u,
		      105u,
		      32u,
		      0u,
		      DEF_decodeLowData_pdInst_BITS_105_TO_0___d51);
  DEF_decodeLowData_pdInst_BITS_259_TO_220___d1 = primExtract64(40u,
								260u,
								ARG_decodeLowData_pdInst,
								32u,
								259u,
								32u,
								220u);
  DEF_decodeLowData_pdInst_BITS_186_TO_169___d26 = ARG_decodeLowData_pdInst.get_bits_in_word32(5u,
											       9u,
											       18u);
  DEF_decodeLowData_pdInst_BITS_140_TO_123___d40 = primExtract32(18u,
								 260u,
								 ARG_decodeLowData_pdInst,
								 32u,
								 140u,
								 32u,
								 123u);
  DEF_x__h1122 = ARG_decodeLowData_pdInst.get_bits_in_word32(3u, 10u, 16u);
  DEF_decodeLowData_pdInst_BITS_167_TO_152___d30 = primExtract32(16u,
								 260u,
								 ARG_decodeLowData_pdInst,
								 32u,
								 167u,
								 32u,
								 152u);
  DEF_pdInst_opcode__h53 = primExtract8(8u, 260u, ARG_decodeLowData_pdInst, 32u, 259u, 32u, 252u);
  DEF_decodeLowData_pdInst_BITS_218_TO_215___d3 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u,
											     23u,
											     4u);
  DEF_decodeLowData_pdInst_BITS_213_TO_210___d7 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u,
											     18u,
											     4u);
  DEF_decodeLowData_pdInst_BITS_208_TO_205___d10 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u,
											      13u,
											      4u);
  DEF_decodeLowData_pdInst_BITS_150_TO_147___d33 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u,
											      19u,
											      4u);
  DEF_decodeLowData_pdInst_BITS_145_TO_142___d37 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u,
											      14u,
											      4u);
  DEF_decodeLowData_pdInst_BIT_214___d6 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u, 22u, 1u);
  DEF_decodeLowData_pdInst_BIT_219___d2 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u, 27u, 1u);
  DEF_decodeLowData_pdInst_BIT_209___d9 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u, 17u, 1u);
  DEF_decodeLowData_pdInst_BIT_204___d15 = ARG_decodeLowData_pdInst.get_bits_in_word8(6u, 12u, 1u);
  DEF_decodeLowData_pdInst_BIT_168___d29 = ARG_decodeLowData_pdInst.get_bits_in_word8(5u, 8u, 1u);
  DEF_decodeLowData_pdInst_BIT_187___d25 = ARG_decodeLowData_pdInst.get_bits_in_word8(5u, 27u, 1u);
  DEF_decodeLowData_pdInst_BIT_151___d32 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u, 23u, 1u);
  DEF_decodeLowData_pdInst_BIT_146___d36 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u, 18u, 1u);
  DEF_decodeLowData_pdInst_BIT_122___d43 = ARG_decodeLowData_pdInst.get_bits_in_word8(3u, 26u, 1u);
  DEF_decodeLowData_pdInst_BIT_141___d39 = ARG_decodeLowData_pdInst.get_bits_in_word8(4u, 13u, 1u);
  DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14 = DEF_pdInst_opcode__h53 == (tUInt8)230u;
  DEF_IF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0_ETC___d49 = DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14 ? 65535u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(ARG_decodeLowData_lowData)) : DEF_x__h1122;
  DEF_NOT_decodeLowData_pdInst_BITS_259_TO_252_3_EQ__ETC___d17 = !DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14;
  DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52.set_bits_in_word(134217727u & (((((tUInt32)(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14 || DEF_decodeLowData_pdInst_BIT_122___d43)) << 26u) | ((DEF_NOT_decodeLowData_pdInst_BITS_259_TO_252_3_EQ__ETC___d17 && !DEF_decodeLowData_pdInst_BIT_122___d43 ? DEF_IF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0_ETC___d49 : DEF_IF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0_ETC___d49) << 10u)) | DEF_decodeLowData_pdInst_BITS_105_TO_0___d51.get_bits_in_word32(3u,
																																																																	      0u,
																																																																	      10u)),
										3u,
										0u,
										27u).set_whole_word(DEF_decodeLowData_pdInst_BITS_105_TO_0___d51.get_whole_word(2u),
												    2u).set_whole_word(DEF_decodeLowData_pdInst_BITS_105_TO_0___d51.get_whole_word(1u),
														       1u).set_whole_word(DEF_decodeLowData_pdInst_BITS_105_TO_0___d51.get_whole_word(0u),
																	  0u);
  DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53.set_bits_in_word(524287u & ((((((tUInt32)(DEF_decodeLowData_pdInst_BIT_146___d36)) << 18u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_146___d36 ? DEF_decodeLowData_pdInst_BITS_145_TO_142___d37 : DEF_decodeLowData_pdInst_BITS_145_TO_142___d37)) << 14u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_141___d39)) << 13u)) | (tUInt32)((DEF_decodeLowData_pdInst_BIT_141___d39 ? DEF_decodeLowData_pdInst_BITS_140_TO_123___d40 : DEF_decodeLowData_pdInst_BITS_140_TO_123___d40) >> 5u)),
										4u,
										0u,
										19u).set_whole_word((((tUInt32)((tUInt8)((tUInt8)31u & (DEF_decodeLowData_pdInst_BIT_141___d39 ? DEF_decodeLowData_pdInst_BITS_140_TO_123___d40 : DEF_decodeLowData_pdInst_BITS_140_TO_123___d40)))) << 27u) | DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52.get_bits_in_word32(3u,
																																													       0u,
																																													       27u),
												    3u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52.get_whole_word(2u),
														       2u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52.get_whole_word(1u),
																	  1u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52.get_whole_word(0u),
																			     0u);
  DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.set_bits_in_word(511u & ((((tUInt32)(DEF_decodeLowData_pdInst_BIT_168___d29)) << 8u) | (tUInt32)((tUInt8)((DEF_decodeLowData_pdInst_BIT_168___d29 ? DEF_decodeLowData_pdInst_BITS_167_TO_152___d30 : DEF_decodeLowData_pdInst_BITS_167_TO_152___d30) >> 8u))),
										5u,
										0u,
										9u).set_whole_word((((((tUInt32)((tUInt8)((tUInt8)255u & (DEF_decodeLowData_pdInst_BIT_168___d29 ? DEF_decodeLowData_pdInst_BITS_167_TO_152___d30 : DEF_decodeLowData_pdInst_BITS_167_TO_152___d30)))) << 24u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_151___d32)) << 23u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_151___d32 ? DEF_decodeLowData_pdInst_BITS_150_TO_147___d33 : DEF_decodeLowData_pdInst_BITS_150_TO_147___d33)) << 19u)) | DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53.get_bits_in_word32(4u,
																																																																										   0u,
																																																																										   19u),
												   4u).set_whole_word(DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53.get_whole_word(3u),
														      3u).set_whole_word(DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53.get_whole_word(2u),
																	 2u).set_whole_word(DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53.get_whole_word(1u),
																			    1u).set_whole_word(DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53.get_whole_word(0u),
																					       0u);
  DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.set_bits_in_word(8191u & ((((tUInt32)(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14 && DEF_decodeLowData_pdInst_BIT_204___d15)) << 12u) | (tUInt32)((DEF_NOT_decodeLowData_pdInst_BITS_259_TO_252_3_EQ__ETC___d17 || !DEF_decodeLowData_pdInst_BIT_204___d15 ? 65535u & ((((tUInt32)((tUInt8)170u)) << 8u) | (tUInt32)(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14 ? primExtract8(8u,
																																																									 260u,
																																																									 ARG_decodeLowData_pdInst,
																																																									 32u,
																																																									 195u,
																																																									 32u,
																																																									 188u) : ARG_decodeLowData_lowData)) : primExtract32(16u,
																																																															     260u,
																																																															     ARG_decodeLowData_pdInst,
																																																															     32u,
																																																															     203u,
																																																															     32u,
																																																															     188u)) >> 4u)),
										6u,
										0u,
										13u).set_whole_word((((((tUInt32)((tUInt8)((tUInt8)15u & (DEF_NOT_decodeLowData_pdInst_BITS_259_TO_252_3_EQ__ETC___d17 || !DEF_decodeLowData_pdInst_BIT_204___d15 ? 65535u & ((((tUInt32)((tUInt8)170u)) << 8u) | (tUInt32)(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6___d14 ? primExtract8(8u,
																																														    260u,
																																														    ARG_decodeLowData_pdInst,
																																														    32u,
																																														    195u,
																																														    32u,
																																														    188u) : ARG_decodeLowData_lowData)) : primExtract32(16u,
																																																					260u,
																																																					ARG_decodeLowData_pdInst,
																																																					32u,
																																																					203u,
																																																					32u,
																																																					188u))))) << 28u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_187___d25)) << 27u)) | ((DEF_decodeLowData_pdInst_BIT_187___d25 ? DEF_decodeLowData_pdInst_BITS_186_TO_169___d26 : DEF_decodeLowData_pdInst_BITS_186_TO_169___d26) << 9u)) | DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.get_bits_in_word32(5u,
																																																																																												  0u,
																																																																																												  9u),
												    5u).set_whole_word(DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.get_whole_word(4u),
														       4u).set_whole_word(DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.get_whole_word(3u),
																	  3u).set_whole_word(DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.get_whole_word(2u),
																			     2u).set_whole_word(DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.get_whole_word(1u),
																						1u).set_whole_word(DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54.get_whole_word(0u),
																								   0u);
  DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.set_bits_in_word(8388607u & (((((((tUInt32)(DEF_decodeLowData_pdInst_BIT_214___d6)) << 22u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_214___d6 ? DEF_decodeLowData_pdInst_BITS_213_TO_210___d7 : DEF_decodeLowData_pdInst_BITS_213_TO_210___d7)) << 18u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_209___d9)) << 17u)) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_209___d9 ? DEF_decodeLowData_pdInst_BITS_208_TO_205___d10 : DEF_decodeLowData_pdInst_BITS_208_TO_205___d10)) << 13u)) | DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_bits_in_word32(6u,
																																																																													    0u,
																																																																													    13u)),
										6u,
										0u,
										23u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_whole_word(5u),
												    5u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_whole_word(4u),
														       4u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_whole_word(3u),
																	  3u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_whole_word(2u),
																			     2u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_whole_word(1u),
																						1u).set_whole_word(DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55.get_whole_word(0u),
																								   0u);
  DEF_decodeLowData_pdInst_BIT_219_CONCAT_IF_decodeL_ETC___d5 = (tUInt8)31u & ((DEF_decodeLowData_pdInst_BIT_219___d2 << 4u) | (DEF_decodeLowData_pdInst_BIT_219___d2 ? DEF_decodeLowData_pdInst_BITS_218_TO_215___d3 : DEF_decodeLowData_pdInst_BITS_218_TO_215___d3));
  PORT_decodeLowData.set_bits_in_word((tUInt8)(DEF_decodeLowData_pdInst_BITS_259_TO_220___d1 >> 36u),
				      8u,
				      0u,
				      4u).set_whole_word((tUInt32)(DEF_decodeLowData_pdInst_BITS_259_TO_220___d1 >> 4u),
							 7u).set_whole_word(((((tUInt32)((tUInt8)((tUInt8)15u & DEF_decodeLowData_pdInst_BITS_259_TO_220___d1))) << 28u) | (((tUInt32)(DEF_decodeLowData_pdInst_BIT_219_CONCAT_IF_decodeL_ETC___d5)) << 23u)) | DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_bits_in_word32(6u,
																																										0u,
																																										23u),
									    6u).set_whole_word(DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_whole_word(5u),
											       5u).set_whole_word(DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_whole_word(4u),
														  4u).set_whole_word(DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_whole_word(3u),
																     3u).set_whole_word(DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_whole_word(2u),
																			2u).set_whole_word(DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_whole_word(1u),
																					   1u).set_whole_word(DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56.get_whole_word(0u),
																							      0u);
  return PORT_decodeLowData;
}

tUInt8 MOD_module_decodeLowData::METH_RDY_decodeLowData()
{
  DEF_CAN_FIRE_decodeLowData = (tUInt8)1u;
  PORT_RDY_decodeLowData = DEF_CAN_FIRE_decodeLowData;
  return PORT_RDY_decodeLowData;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_decodeLowData::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_decodeLowData::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 11u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_decodeLowData", 1u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BITS_105_TO_0___d51", 106u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52", 123u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55", 205u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53", 147u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54", 169u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56", 215u);
  vcd_write_def(sim_hdl, num++, "RDY_decodeLowData", 1u);
  vcd_write_def(sim_hdl, num++, "decodeLowData", 260u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_lowData", 8u);
  vcd_write_def(sim_hdl, num++, "decodeLowData_pdInst", 260u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_decodeLowData::dump_VCD(tVCDDumpType dt,
					unsigned int levels,
					MOD_module_decodeLowData &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_decodeLowData::vcd_defs(tVCDDumpType dt, MOD_module_decodeLowData &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 106u);
    vcd_write_x(sim_hdl, num++, 123u);
    vcd_write_x(sim_hdl, num++, 205u);
    vcd_write_x(sim_hdl, num++, 147u);
    vcd_write_x(sim_hdl, num++, 169u);
    vcd_write_x(sim_hdl, num++, 215u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 260u);
    vcd_write_x(sim_hdl, num++, 8u);
    vcd_write_x(sim_hdl, num++, 260u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_decodeLowData) != DEF_CAN_FIRE_decodeLowData)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_decodeLowData, 1u);
	backing.DEF_CAN_FIRE_decodeLowData = DEF_CAN_FIRE_decodeLowData;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BITS_105_TO_0___d51) != DEF_decodeLowData_pdInst_BITS_105_TO_0___d51)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BITS_105_TO_0___d51, 106u);
	backing.DEF_decodeLowData_pdInst_BITS_105_TO_0___d51 = DEF_decodeLowData_pdInst_BITS_105_TO_0___d51;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52) != DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52, 123u);
	backing.DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52 = DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55) != DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55, 205u);
	backing.DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55 = DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53) != DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53, 147u);
	backing.DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53 = DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54) != DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54, 169u);
	backing.DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54 = DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54;
      }
      ++num;
      if ((backing.DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56) != DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56)
      {
	vcd_write_val(sim_hdl, num, DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56, 215u);
	backing.DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56 = DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56;
      }
      ++num;
      if ((backing.PORT_RDY_decodeLowData) != PORT_RDY_decodeLowData)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_decodeLowData, 1u);
	backing.PORT_RDY_decodeLowData = PORT_RDY_decodeLowData;
      }
      ++num;
      if ((backing.PORT_decodeLowData) != PORT_decodeLowData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeLowData, 260u);
	backing.PORT_decodeLowData = PORT_decodeLowData;
      }
      ++num;
      if ((backing.PORT_decodeLowData_lowData) != PORT_decodeLowData_lowData)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeLowData_lowData, 8u);
	backing.PORT_decodeLowData_lowData = PORT_decodeLowData_lowData;
      }
      ++num;
      if ((backing.PORT_decodeLowData_pdInst) != PORT_decodeLowData_pdInst)
      {
	vcd_write_val(sim_hdl, num, PORT_decodeLowData_pdInst, 260u);
	backing.PORT_decodeLowData_pdInst = PORT_decodeLowData_pdInst;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_decodeLowData, 1u);
      backing.DEF_CAN_FIRE_decodeLowData = DEF_CAN_FIRE_decodeLowData;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BITS_105_TO_0___d51, 106u);
      backing.DEF_decodeLowData_pdInst_BITS_105_TO_0___d51 = DEF_decodeLowData_pdInst_BITS_105_TO_0___d51;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52, 123u);
      backing.DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52 = DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d52;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55, 205u);
      backing.DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55 = DEF_decodeLowData_pdInst_BITS_259_TO_252_3_EQ_0xE6_ETC___d55;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53, 147u);
      backing.DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53 = DEF_decodeLowData_pdInst_BIT_146_6_CONCAT_IF_decod_ETC___d53;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54, 169u);
      backing.DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54 = DEF_decodeLowData_pdInst_BIT_168_9_CONCAT_IF_decod_ETC___d54;
      vcd_write_val(sim_hdl, num++, DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56, 215u);
      backing.DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56 = DEF_decodeLowData_pdInst_BIT_214_CONCAT_IF_decodeL_ETC___d56;
      vcd_write_val(sim_hdl, num++, PORT_RDY_decodeLowData, 1u);
      backing.PORT_RDY_decodeLowData = PORT_RDY_decodeLowData;
      vcd_write_val(sim_hdl, num++, PORT_decodeLowData, 260u);
      backing.PORT_decodeLowData = PORT_decodeLowData;
      vcd_write_val(sim_hdl, num++, PORT_decodeLowData_lowData, 8u);
      backing.PORT_decodeLowData_lowData = PORT_decodeLowData_lowData;
      vcd_write_val(sim_hdl, num++, PORT_decodeLowData_pdInst, 260u);
      backing.PORT_decodeLowData_pdInst = PORT_decodeLowData_pdInst;
    }
}
