// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  Clocks::ClkNextRdy
// Generated on: Sat Nov 22 09:18:14 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<1> to ClkNextRdy
typedef BitT<1> ClkNextRdy ;

