// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  NoCUtils::CreditCount
// Generated on: Wed Nov 26 12:58:49 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<4> to CreditCount
typedef BitT<4> CreditCount ;

