// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  SceMiLayer::FromHost
// Generated on: Wed Nov 26 13:26:56 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<32> to FromHost
typedef BitT<32> FromHost ;

