// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  All SceMi types
// Generated on: Sat Nov 22 09:18:14 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#pragma once

#include "PowerStruct.h" 
#include "PowerAssoc.h" 
#include "Tuple2_Bit_5_Bit_32.h" 
#include "ProbeControl.h" 
#include "PrbNum.h" 
#include "CosimStruct.h" 
#include "MemInit.h" 
#include "MemInitLoad.h" 
#include "PowerProbe.h" 
#include "PwPrbKind.h" 
#include "ToHost.h" 
#include "FromHost.h" 
#include "SimulationControlReq.h" 
#include "SimulationStatusResp.h" 
#include "Tag.h" 
#include "RIndx.h" 
#include "Exception.h" 
#include "Line.h" 
#include "Data.h" 
#include "Addr.h" 
#include "LongWord.h" 
#include "DevNumber.h" 
#include "CreditCount.h" 
#include "ClkNextRdy.h" 
