// This file automatically generated by SceMiParams::genProbeFile
// DO NOT EDIT
// Generated on: Tue Nov 25 02:07:54 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#include "bsv_scemi.h"


BSVType *ProbesXactor::createData(unsigned int probeNum, Packet *data, SceMiU64 cycle)
{
  BSVType *type = NULL;
 // No probes are defined!

  return type;
}

unsigned int ProbesXactor::getBitSize(unsigned int probeNum)
{
  return 0;
}

