// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  SceMiSharedMemory::Tag
// Generated on: Tue Nov 25 02:07:54 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<7> to Tag
typedef BitT<7> Tag ;

