// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  SceMiLayer::ToHost
// Generated on: Wed Nov 26 13:26:56 EST 2014
// Bluespec version: 2014.06.A 2014-06-24 33987

#pragma once

#include "bsv_scemi.h"
#include "Tuple2_Bit_5_Bit_32.h"


/// An alias or typedef name for Tuple2_Bit_5_Bit_32 to ToHost
typedef Tuple2_Bit_5_Bit_32 ToHost ;

